window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'lop', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'lich', name: 'Lịch và buổi học', depends: ['lop'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien', 'lich'] },
    { id: 'quan-tri', name: 'Báo cáo và quản trị', depends: ['diem-danh', 'goi-hoc'] },
  ],
  screens: [
    // Web quản trị
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true, zones: ['Form đăng nhập'] },
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'lich', roles: ['le-tan'],
      bands: [
        { name: 'Việc ở quầy', items: ['F-24', 'F-23', 'F-07', 'F-43'] },
        { name: 'Yêu cầu đổi lịch chờ xử lý', items: ['F-46', 'F-47', 'F-48'] },
        { name: 'Chờ xác nhận chuyển khoản', items: ['F-08'] },
        { name: 'Sắp hết buổi, cần gọi', items: ['F-16', 'F-17'] },
        { name: 'Cuối ngày', items: ['F-11'] },
      ] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      bands: [
        { name: 'Cần duyệt', items: ['F-60', 'F-19'] },
        { name: 'Báo nội bộ', items: ['F-86', 'F-52'] },
        { name: 'Tháng này', items: ['F-70', 'F-69'] },
        { name: 'Lớp đông, nhiều bé chờ', items: ['F-57'] },
      ] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [
        { name: 'Buổi đang dạy', items: ['F-01'] },
        { name: 'Các buổi còn lại hôm nay', items: ['F-40'] },
        { name: 'Học thử cần ghi cấp độ', items: ['F-66'] },
      ] },
    { id: 'lich', name: 'Lịch tuần', surface: 'web', module: 'lich', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Ngăn chi tiết lớp'], tabs: ['Theo làn', 'Theo HLV'] },
    { id: 'lich-day', name: 'Lịch dạy của tôi', surface: 'web', module: 'lich', roles: ['hlv'], zones: ['Tuần của tôi'] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Thanh công cụ', 'Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Gói và thu tiền', 'Lịch và điểm danh'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Thanh công cụ', 'Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop', roles: ['quan-ly', 'le-tan', 'hlv'], parent: 'lop', pick: true,
      zones: ['Đầu lớp', 'Học viên trong lớp', 'Danh sách chờ'] },
    { id: 'goi-hoc', name: 'Gói và thu tiền', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ'], tabs: ['Gói học', 'Khoản thu hôm nay'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Đề nghị hoàn tiền'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Thông báo đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Tìm và lọc'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch'] },
    { id: 'tai-khoan', name: 'Tài khoản của tôi', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], zones: ['Mật khẩu'] },
    // App phụ huynh
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'hoc-vien', roles: ['phu-huynh'], entry: true, zones: ['Số điện thoại và mã'] },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'lich', roles: ['phu-huynh'],
      bands: [
        { name: 'Con đang xem', items: ['F-31'] },
        { name: 'Buổi sắp tới', items: ['F-41', 'F-42', 'F-44'] },
        { name: 'Số buổi còn lại', items: ['F-33'] },
        { name: 'Yêu cầu đổi lịch', items: ['F-45'] },
      ] },
    { id: 'app-goi', name: 'Buổi và gói', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'],
      zones: ['Gói đang dùng', 'Buổi đã học', 'Lịch sử đóng tiền'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'], zones: ['Hộp thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'hoc-vien', roles: ['phu-huynh'], zones: ['Con của tôi', 'Cài đặt thông báo'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['quay', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Tiền', items: ['goi-hoc', 'hoan-tien'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Cá nhân', items: ['tai-khoan'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Tiền', items: ['goi-hoc', 'hoan-tien'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'nhat-ky', 'cai-dat', 'tai-khoan'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'lich-day', 'lop', 'hoc-vien', 'tai-khoan'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    // Điểm danh
    'F-01': { screen: 'buoi-day', zone: 'Buổi đang dạy', tier: 1, mo: 'tai-cho' },
    'F-02': { screen: 'lich-day', zone: 'Tuần của tôi', tier: 4, mo: 'ngan-truot' },
    'F-04': { screen: 'app-goi', zone: 'Buổi đã học', tier: 2, mo: 'tai-cho' },
    'F-05': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'hop-thoai' },
    // Gói học và thu tiền
    'F-06': { screen: 'cai-dat', tab: 'Bảng giá', tier: 2, mo: 'tai-cho' },
    'F-07': { screen: 'goi-hoc', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-08': { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'hop-thoai' },
    'F-09': { screen: 'ho-so', tab: 'Gói và thu tiền', tier: 2, mo: 'tai-cho' },
    'F-10': { screen: 'goi-hoc', tab: 'Gói học', tier: 2, mo: 'tai-cho' },
    'F-11': { screen: 'goi-hoc', tab: 'Khoản thu hôm nay', tier: 2, mo: 'tai-cho' },
    'F-12': { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'hop-thoai' },
    'F-16': { screen: 'quay', zone: 'Sắp hết buổi, cần gọi', tier: 2, mo: 'tai-cho' },
    'F-17': { screen: 'quay', zone: 'Sắp hết buổi, cần gọi', tier: 4, mo: 'hop-thoai' },
    'F-18': { screen: 'hoan-tien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-19': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-20': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-21': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 2, mo: 'tai-cho' },
    'F-22': { screen: 'goi-hoc', zone: 'Thanh công cụ', tier: 4, mo: 'tai-cho' },
    // Học viên
    'F-23': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-24': [{ screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' }, { screen: 'quay', zone: 'Việc ở quầy', tier: 2, mo: 'tai-cho' }],
    'F-25': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'tai-cho' },
    'F-26': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-27': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'ngan-truot' },
    'F-28': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-30': { screen: 'app-dang-nhap', zone: 'Số điện thoại và mã', tier: 1, mo: 'tai-cho' },
    'F-31': { screen: 'app-lich', zone: 'Con đang xem', tier: 2, mo: 'tai-cho' },
    'F-33': [{ screen: 'app-goi', zone: 'Gói đang dùng', tier: 1, mo: 'tai-cho' }, { screen: 'app-lich', zone: 'Số buổi còn lại', tier: 2, mo: 'tai-cho' }],
    'F-34': { screen: 'app-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-35': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 4, mo: 'ngan-truot' },
    'F-36': { screen: 'app-tai-khoan', zone: 'Con của tôi', tier: 2, mo: 'tai-cho' },
    // Lịch và buổi học
    'F-38': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'tai-cho' },
    'F-39': { screen: 'lich', tab: 'Theo làn', tier: 1, mo: 'tai-cho' },
    'F-40': [{ screen: 'lich', tab: 'Theo HLV', tier: 2, mo: 'tai-cho' }, { screen: 'lich-day', zone: 'Tuần của tôi', tier: 1, mo: 'tai-cho' }, { screen: 'buoi-day', zone: 'Các buổi còn lại hôm nay', tier: 2, mo: 'tai-cho' }],
    'F-41': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-42': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-43': { screen: 'ho-so', tab: 'Lịch và điểm danh', tier: 4, mo: 'hop-thoai' },
    'F-44': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-45': { screen: 'app-lich', zone: 'Yêu cầu đổi lịch', tier: 2, mo: 'tai-cho' },
    'F-46': { screen: 'quay', zone: 'Yêu cầu đổi lịch chờ xử lý', tier: 2, mo: 'tai-cho' },
    'F-47': { screen: 'quay', zone: 'Yêu cầu đổi lịch chờ xử lý', tier: 4, mo: 'ngan-truot' },
    'F-48': { screen: 'quay', zone: 'Yêu cầu đổi lịch chờ xử lý', tier: 4, mo: 'hop-thoai' },
    'F-50': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'hop-thoai' },
    'F-52': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'hop-thoai' },
    'F-53': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'hop-thoai' },
    'F-54': { screen: 'lich', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    // Khoá học và lớp
    'F-56': { screen: 'lop', zone: 'Thanh công cụ', tier: 3, mo: 'ngan-truot' },
    'F-57': { screen: 'lop', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-58': { screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'tai-cho' },
    'F-59': { screen: 'lop-chi-tiet', zone: 'Đầu lớp', tier: 1, mo: 'ngan-truot' },
    'F-60': { screen: 'tong-quan', zone: 'Cần duyệt', tier: 2, mo: 'hop-thoai' },
    'F-61': { screen: 'lop-chi-tiet', zone: 'Danh sách chờ', tier: 4, mo: 'hop-thoai' },
    'F-62': { screen: 'lop-chi-tiet', zone: 'Danh sách chờ', tier: 4, mo: 'hop-thoai' },
    'F-63': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 2, mo: 'tai-cho' },
    'F-64': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'ngan-truot' },
    'F-65': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-66': { screen: 'buoi-day', zone: 'Học thử cần ghi cấp độ', tier: 2, mo: 'hop-thoai' },
    'F-67': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 4, mo: 'hop-thoai' },
    // Báo cáo và quản trị
    'F-69': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-70': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-71': { screen: 'bao-cao', zone: 'Thanh công cụ', tier: 2, mo: 'hop-thoai' },
    'F-72': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-73': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'ngan-truot' },
    'F-74': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-75': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-76': { screen: 'dang-nhap', zone: 'Form đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-77': { screen: 'tai-khoan', zone: 'Mật khẩu', tier: 2, mo: 'hop-thoai' },
    'F-78': { screen: 'nhat-ky', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' },
    // Thông báo
    'F-80': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-81': { screen: 'thong-bao', zone: 'Thông báo đã gửi', tier: 2, mo: 'tai-cho' },
    'F-82': { screen: 'app-thong-bao', zone: 'Hộp thông báo', tier: 1, mo: 'tai-cho' },
    'F-83': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 2, mo: 'tai-cho' },
    'F-84': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 2, mo: 'tai-cho' },
    'F-86': { screen: 'tong-quan', zone: 'Báo nội bộ', tier: 2, mo: 'tai-cho' },
  },
  shortcuts: [
    // Quầy hôm nay: việc ở quầy mở ngay trên trang chủ
    { from: 'quay', to: 'F-23', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-07', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-43', mo: 'hop-thoai' },
    { from: 'quay', to: 'F-08', mo: 'hop-thoai' },
    { from: 'quay', to: 'F-11', mo: 'ngan-truot' },
    // Tổng quan của quản lý
    { from: 'tong-quan', to: 'F-19', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-52', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-57', mo: 'ngan-truot' },
    // Hồ sơ học viên: mở việc của module khác ngay trên hồ sơ, không rời hồ sơ
    { from: 'ho-so', to: 'F-07', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-59', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-47', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-64', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-12', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-05', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-18', mo: 'ngan-truot' },
    // Lịch tuần: bấm ô lớp mở danh sách học viên ở ngăn bên phải (tương tác đặc trưng của concept)
    { from: 'lich', to: 'F-63', mo: 'ngan-truot' },
    { from: 'lich', to: 'F-01', mo: 'ngan-truot' },
    { from: 'lich', to: 'F-02', mo: 'ngan-truot' },
    // Chi tiết lớp: bấm tên bé mở hồ sơ ở ngăn bên phải, không rời lớp
    { from: 'lop-chi-tiet', to: 'F-25', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Phụ huynh dắt bé tới đăng ký học lần đầu', steps: ['F-24', 'F-23', 'F-59', 'F-07'] },
    { role: 'le-tan', name: 'Xử lý yêu cầu đổi lịch phụ huynh gửi qua app', steps: ['F-46', 'F-47'] },
    { role: 'le-tan', name: 'Gọi mời gia hạn bé sắp hết buổi', steps: ['F-16', 'F-17', 'F-07'] },
    { role: 'quan-ly', name: 'Mở thêm lớp khi danh sách chờ dài', steps: ['F-58', 'F-57', 'F-62'] },
    { role: 'quan-ly', name: 'Đầu tháng xem số liệu tháng trước', steps: ['F-70', 'F-69', 'F-71'] },
    { role: 'hlv', name: 'Một buổi dạy ở thành bể', steps: ['F-40', 'F-01', 'F-66'] },
    { role: 'phu-huynh', name: 'Con ốm, không đi học buổi tới', steps: ['F-31', 'F-41', 'F-42', 'F-33'] },
    { role: 'phu-huynh', name: 'Xin cho con học buổi khác trong tuần', steps: ['F-41', 'F-44', 'F-45'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một phụ huynh dắt bé 6 tuổi tới quầy, muốn cho bé học bơi; trung tâm chưa có thông tin gì về bé.', feature: 'F-23' },
    { role: 'le-tan', say: 'Mẹ bé Minh Anh tới quầy, muốn đóng tiền cho 12 buổi tiếp theo.', feature: 'F-07' },
    { role: 'le-tan', say: 'Sáng nay có phụ huynh nhắn qua app xin cho con học lớp tối thứ Sáu thay cho lớp thứ Năm; xử lý tin đó.', feature: 'F-47' },
    { role: 'le-tan', say: 'Một phụ huynh gọi điện: bé bị sốt, chiều nay không tới được.', feature: 'F-43' },
    { role: 'le-tan', say: 'Kế toán nhắn: tài khoản ngân hàng của trung tâm vừa nhận 1.380.000 ₫ của mẹ bé An.', feature: 'F-08' },
    { role: 'hlv', say: 'Lớp 17:00 vừa xuống nước; ghi lại bé nào tới, bé nào không.', feature: 'F-01' },
    { role: 'quan-ly', say: 'Cuối tháng, chủ trung tâm muốn biết tháng này thu được bao nhiêu.', feature: 'F-70' },
    { role: 'quan-ly', say: 'Bể nhỏ hỏng máy lọc, mọi lớp chiều nay phải nghỉ.', feature: 'F-54' },
    { role: 'phu-huynh', say: 'Bé nhà bạn bị cảm; bạn muốn trung tâm biết thứ Năm này bé không tới.', feature: 'F-42' },
    { role: 'phu-huynh', say: 'Bạn muốn biết với số tiền đã đóng, con còn học được mấy lần nữa.', feature: 'F-33' },
  ],
};
