window.PART = {
  module: 'diem-danh',
  features: [
    { name: 'Điểm danh buổi học', src: ['UC-05', 'BR-DD-01', 'BR-DD-03', 'BR-DD-04', 'XD-01', 'A-02', 'A-05', 'A-10', 'D4:111', 'D8:99-105', 'M-04'], roles: ['hlv', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh', 'trang_thai_diem_danh.co_mat', 'trang_thai_diem_danh.vang_co_phep', 'trang_thai_diem_danh.vang_khong_phep', 'trang_thai_diem_danh.da_hoc_bu'], spec: 'HLV chọn buổi đang dạy hôm nay trên máy tính bảng (cả buổi dạy thay, A-02); quản lý chọn được mọi buổi trên web. Bé đã báo nghỉ hiện sẵn vắng có phép (báo trước ít nhất 2 giờ, theo XD-01). Bấm Có mặt tất cả rồi đổi từng bé vắng; lưu thì trừ buổi theo BR-DD-03/04. Bé hết buổi, hết hạn không chọn Có mặt được (A-05). Bé học bù có mặt thì buổi vắng gốc thành đã học bù.', notes: 'A-10: mất mạng khi lưu thì lưu tạm trên máy, tự gửi khi có mạng; hỏi: mạng về sau 23:00 thì bản lưu tạm hay trạng thái vắng không phép tự chốt (BR-DD-02) thắng? A-05: lễ tân bán gói mới xong thì mở lại Có mặt cho bé, buổi hôm nay tính vào gói mới; hỏi: phụ huynh không mua gói thì bé ghi trạng thái gì? Hỏi: lần vắng có phép thứ 4 trong gói (BR-DD-04) hiện nhãn vắng không phép hay giữ nhãn có phép mà vẫn trừ? Học viên học thử (la_hoc_thu, BR-LH-06) có trong danh sách. BR-DD-03 và YC-08 ghi 24 giờ, đã bị XD-01 đè.' },
    { name: 'Sửa điểm danh đã lưu', src: ['BR-DD-05', 'UC-05', 'D8:114-115', 'M-04'], roles: ['hlv', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'HLV sửa trạng thái học viên của buổi mình dạy trong 24 giờ sau buổi; quá 24 giờ chỉ quản lý sửa được và bắt buộc ghi lý do. Lưu người sửa, lý do sửa; số buổi còn lại tính lại theo BR-DD-03. Sửa được cả trạng thái do hệ thống tự chốt.' },
    { name: 'Tự chốt điểm danh cuối ngày', src: ['BR-DD-02', 'BR-DD-03', 'UC-05', 'D4:29', 'M-04'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_khong_phep'], spec: '23:00 mỗi ngày, học viên còn chưa điểm danh trong buổi đã qua được ghi vắng không phép và trừ một buổi. Giờ chốt cố định, tài liệu không nêu việc cấu hình.' },
    { name: 'Xem các buổi đã học của con', src: ['UC-05', 'D4:233', 'M-04'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'Trên app, phụ huynh thấy các buổi con đã học kèm trạng thái điểm danh (có mặt, vắng có phép, vắng không phép, đã học bù) và buổi đó có bị trừ hay không.', notes: 'UC-05 chỉ ghi phụ huynh thấy buổi đã học; có thể trùng màn lịch và số buổi còn lại của UC-06 (module khác): gộp ở merge nếu trùng.' },
    { name: 'Xếp buổi học bù cho buổi vắng có phép', src: ['D8:104', 'D8:112'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Chọn một buổi vắng có phép của học viên, xếp bé vào một buổi của lớp cùng cấp độ; bé hiện trong danh sách điểm danh buổi đó, có mặt thì buổi vắng gốc chuyển đã học bù.', notes: 'Chỉ có trong schema (note da_hoc_bu, buoi_bu_id). Hỏi: ai xếp học bù, hạn học bù bao lâu, buổi bù có trừ buổi không, thuộc M-04 hay hạng mục khác? Có thể thuộc module lịch hay lớp: gộp ở merge nếu trùng.' },
  ],
  skip: [],
};
