window.PART = {
  module: 'hoc-vien',
  features: [
    { name: 'Đăng ký học viên mới', src: ['UC-01', 'BR-HV-01', 'BR-HV-02', 'BR-HV-04', 'YC-01', 'D4:106', 'M-01'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Tìm phụ huynh theo số điện thoại: có rồi thì hiện phụ huynh và các con, gắn học viên mới vào đó; chưa có thì tạo phụ huynh (họ tên, SĐT, quan hệ). Nhập học viên; dưới 6 tuổi trống ghi chú sức khoẻ thì không lưu. Hệ thống sinh mã SX-0001, rồi bán gói hoặc dừng.', notes: 'mâu thuẫn: D4:139 có giới tính, D8:25-34 không có cột giới tính; trạng thái lúc tạo khi phụ huynh chưa mua gói (D4:141) chưa nêu: học thử hay đang học' },
    { name: 'Tìm học viên', src: ['D4:151', 'YC-01', 'D4:105', 'M-01'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Tìm theo tên, mã học viên hoặc số điện thoại phụ huynh, trả kết quả từ ký tự thứ ba; kết quả có nhãn trạng thái học thử, đang học, ngừng học. HLV chỉ thấy học viên lớp mình.' },
    { name: 'Xem hồ sơ học viên', src: ['D4:150', 'D4:105', 'BR-HV-05', 'M-01'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Trang chi tiết: thông tin học viên, phụ huynh, ghi chú sức khoẻ, trạng thái, gói học, các buổi đã học; học viên ngừng học vẫn xem đủ lịch sử. HLV chỉ xem học viên lớp mình.', notes: 'OQ-03: HLV có thấy số điện thoại phụ huynh lớp mình không (BR-QT-02)' },
    { name: 'Sửa hồ sơ học viên', src: ['D4:106', 'BR-HV-01', 'BR-HV-04', 'M-01'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sửa họ tên, ngày sinh, ghi chú sức khoẻ; mã học viên không sửa được. Học viên dưới 6 tuổi không được để trống ghi chú sức khoẻ.', notes: 'A-08: lễ tân ghi chú yêu cầu hoàn tiền vào hồ sơ, nhưng D8:25-34 chỉ có ghi chú sức khoẻ, chưa có trường ghi chú chung' },
    { name: 'Sửa hồ sơ phụ huynh', src: ['D8:11-17', 'BR-HV-02', 'D4:106', 'M-01'], roles: ['quan-ly', 'le-tan'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Sửa họ tên, số điện thoại, quan hệ của phụ huynh; số điện thoại mới trùng phụ huynh khác thì không lưu. Các con của phụ huynh vẫn gắn với hồ sơ này.', notes: 'tài liệu không nêu việc sửa phụ huynh; đổi số điện thoại là đổi số đăng nhập app (NF-05): có cần xác nhận lại không?' },
    { name: 'Chuyển học viên sang ngừng học', src: ['BR-HV-05', 'D8:22', 'D4:106', 'M-01'], roles: ['quan-ly', 'le-tan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.ngung_hoc'], spec: 'Học viên nghỉ hẳn: chuyển trạng thái ngừng học, không xoá hồ sơ, giữ lịch sử học và đóng tiền; mã học viên không dùng lại.', notes: 'chưa nêu học viên ngừng học quay lại thì đưa về đang học thế nào' },
    { name: 'Tự chuyển học viên sang đang học khi có gói', src: ['D8:19-23', 'D4:141', 'M-01'], roles: [], freq: 'ngay', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_hoc_vien.dang_hoc'], spec: 'Hệ thống chuyển học viên mới đăng ký hoặc đang học thử sang đang học khi học viên có gói học đầu tiên.', notes: 'D8:19-23 chỉ có enum học thử, đang học, ngừng học; không tài liệu nào nêu việc gì đưa học viên tới học thử hay đang học' },
    { name: 'Đăng nhập app bằng số điện thoại và mã OTP', src: ['D4:263', 'NF-05', 'D8:14', 'M-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhập số điện thoại đã đăng ký ở quầy, nhận mã OTP rồi đăng nhập; chỉ số đã có hồ sơ phụ huynh mới vào được.' },
    { name: 'Chọn con đang xem trên app', src: ['BR-HV-03', 'UC-06', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh có nhiều con chọn một con để xem; lịch, gói học chỉ hiện của con đang chọn, không trộn lịch các con.' },
    { name: 'Xem các buổi học sắp tới trên app', src: ['UC-06', 'D4:269', 'D4:275', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Màn đầu của app: các buổi học sắp tới của con đang chọn, buổi gần nhất ở trên. Chưa có gói nào thì hiện số điện thoại quầy và giờ làm việc.' },
    { name: 'Xem gói học và số buổi còn lại trên app', src: ['UC-06', 'D4:270', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Số buổi còn lại, hạn dùng của gói, gói đang bảo lưu nếu có, của con đang chọn.' },
    { name: 'Xem lịch sử đóng tiền trên app', src: ['UC-06', 'D4:271', 'M-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Danh sách các lần đóng tiền: ngày, gói, số tiền, mã biên lai.', notes: 'BR-HV-03 chỉ nói lịch xem từng con; lịch sử đóng tiền theo từng con hay gộp mọi con của phụ huynh?' },
    { name: 'Ghi nhận xét tiến bộ cuối cấp độ', src: ['S-04'], roles: ['hlv'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'HLV ghi nhận xét kỹ năng của học viên khi xong mỗi cấp độ; giai đoạn 2.', notes: 'HLV chưa thống nhất mẫu nhận xét (D5:37)' },
    { name: 'Xem nhận xét tiến bộ trên app', src: ['S-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'Phụ huynh xem nhận xét kỹ năng HLV ghi cho con sau mỗi cấp độ; giai đoạn 2.' },
  ],
  skip: [
    { src: 'D7:52-55', why: 'Khoá học, xếp lớp, lịch toàn trung tâm, học thử: việc của module lớp và lịch' },
    { src: 'D8:33', why: 'Cấp độ gợi ý HLV ghi sau buổi học thử (BR-LH-06): việc của module lớp' },
  ],
};
