window.PART = {
  module: 'lop',
  features: [
    { name: 'Tạo khoá học', src: ['UC-03', 'BR-LH-01', 'BR-LH-05', 'XD-03', 'D8:44-49', 'M-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tạo hoặc chọn khoá có sẵn: tên, cấp độ (Làm quen nước, Cơ bản, Nâng cao), số buổi một tuần, sĩ số tối đa. Làm quen nước 6 bé theo XD-03 (không phải 8 như SOP), các cấp khác 10 bé. Chỉ Quản lý.' },
    { name: 'Mở lớp', src: ['UC-03', 'BR-LH-02', 'D4:196-202', 'M-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoá, HLV chính, các ngày trong tuần, giờ bắt đầu (buổi 45 phút), bể, làn. Trùng HLV hoặc làn với lớp khác thì chỉ ra lớp trùng để đổi giờ, đổi làn. Lưu xong hệ thống sinh buổi học (BR-LI-01, module lịch).' },
    { name: 'Xem danh sách lớp', src: ['UC-04', 'D4:217-218', 'D4:188', 'M-02'], roles: ['quan-ly', 'le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Lọc theo cấp độ, ngày, giờ. Mỗi lớp hiện HLV, khung giờ, sĩ số hiện tại, số chỗ còn trống và số bé đang chờ; Quản lý dựa vào số chờ theo cấp độ để mở thêm lớp.' },
    { name: 'Xếp học viên vào lớp', src: ['UC-04', 'BR-LH-03', 'A-01', 'A-06', 'M-02'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc'], spec: 'Chỉ học viên có gói còn buổi; chọn lớp còn chỗ, đúng cấp độ. Anh chị em trùng giờ ở hai lớp: cảnh báo, vẫn lưu nếu phụ huynh đồng ý. Hai người cùng xếp chỗ cuối: người lưu sau nhận báo lớp vừa đủ, gợi ý danh sách chờ. Lưu xong sinh buổi của học viên đến hết gói.' },
    { name: 'Duyệt xếp học viên xuống lớp thấp hơn một bậc', src: ['BR-LH-03', 'D4:108', 'M-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Xếp vào lớp thấp hơn cấp độ của bé một bậc chỉ khi Quản lý cho phép; thấp hơn hai bậc trở lên thì không xếp được.', notes: 'Hỏi: Quản lý cho phép bằng cách nào (lễ tân gửi yêu cầu để Quản lý duyệt trên hệ thống, hay chỉ Quản lý tự xếp)?' },
    { name: 'Đưa học viên vào danh sách chờ', src: ['BR-LH-04', 'UC-04', 'A-01', 'D8:61-74', 'M-02'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.cho_cho'], spec: 'Lớp đủ sĩ số thì ghi bé vào danh sách chờ của đúng lớp đó, lưu thời điểm đăng ký và thứ tự chờ.' },
    { name: 'Gọi phụ huynh theo danh sách chờ', src: ['BR-LH-04', 'M-02'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc'], spec: 'Lớp có chỗ trống thì lễ tân thấy danh sách chờ theo thứ tự đăng ký, người đăng ký trước được gọi trước; phụ huynh đồng ý thì chuyển bé từ chờ sang đang học (vẫn theo luật xếp lớp).', notes: 'Hỏi: phụ huynh từ chối hay không liên lạc được thì bé giữ chỗ chờ, xuống cuối hay rời danh sách? Tài liệu chưa nói cách rút khỏi danh sách chờ.' },
    { name: 'Xem danh sách học viên của lớp', src: ['UC-04', 'D4:209', 'D4:105', 'M-02'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop'], spec: 'Danh sách bé của một lớp kèm nhãn đang học, đang chờ (theo thứ tự), đã rời. HLV chỉ xem lớp mình và thấy học viên mới được xếp; Quản lý, Lễ tân xem mọi lớp.' },
    { name: 'Chuyển học viên sang lớp khác', src: ['UC-04', 'D4:210', 'A-07', 'M-02'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.da_roi'], spec: 'Chọn lớp mới còn chỗ, đúng cấp độ; lớp cũ ghi đã rời, lớp mới đang học. Số buổi còn lại của gói giữ nguyên, buổi chưa học sinh lại theo lớp mới. Chỗ trống ở lớp cũ mở cho danh sách chờ.', notes: 'Hỏi: lên cấp độ giữa chừng có thu chênh lệch giá không (OQ-02, A-07). UC-08 (module lịch) cũng chạm chuyển lớp: gộp khi merge nếu trùng.' },
    { name: 'Đặt buổi học thử', src: ['BR-LH-06', 'S-03'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Mỗi bé được một buổi học thử miễn phí ở một lớp còn chỗ, đúng độ tuổi; bé đã học thử thì không đặt thêm. Tạo hồ sơ học thử của bé.', notes: 'Hỏi: "đúng độ tuổi" đối chiếu với gì? Bảng lop, khoa_hoc không có độ tuổi (D8:44-59). Bé học thử có tính vào sĩ số buổi đó không?' },
    { name: 'Ghi cấp độ gợi ý sau buổi học thử', src: ['BR-LH-06', 'S-03'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sau buổi học thử, HLV ghi cấp độ gợi ý cho bé; lễ tân dùng kết quả này để chọn lớp khi bé thành học viên chính thức.' },
    { name: 'Chuyển bé học thử thành học viên chính thức', src: ['BR-LH-06', 'S-03'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh mua gói thì hồ sơ học thử thành học viên chính thức, giữ cấp độ gợi ý và kết quả học thử.', notes: 'Xảy ra trong luồng bán gói (module gói học); gộp nếu module kia đã có.' },
    { name: 'Tự xoá hồ sơ học thử quá 60 ngày', src: ['BR-LH-06', 'S-03'], roles: [], freq: 'ngay', evidence: 'suy', status: 'pham-vi', spec: 'Hồ sơ học thử không mua gói được giữ 60 ngày kể từ buổi học thử; quá hạn thì hệ thống tự xoá.', notes: 'Tài liệu chỉ nói giữ 60 ngày; xoá hẳn hay ẩn là suy ra.' },
  ],
  skip: [],
};
