window.PART = {
  module: 'thong-bao',
  features: [
    { name: 'Gửi thông báo cho phụ huynh', src: ['UC-10', 'YC-12', 'BR-TB-01', 'BR-TB-03', 'M-09', 'D4:114'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn người nhận: cả trung tâm, theo lớp, theo cấp độ hoặc chọn nhiều phụ huynh; soạn tiêu đề, nội dung; gửi ngay hoặc hẹn giờ trong khung 7:00–21:00. Đánh dấu khẩn thì gửi ngay, bỏ khung giờ. HLV không gửi.', notes: 'Thông báo đi qua app (BR-TB-01). Thông báo khẩn khi huỷ buổi, dạy thay do module lịch kích hoạt (A-02, A-03).' },
    { name: 'Xem thông báo đã gửi', src: ['D8:209-222', 'UC-10', 'M-09'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Danh sách thông báo đã gửi và đang chờ giờ hẹn: tiêu đề, người gửi, giờ gửi, khẩn hay không, số phụ huynh đã đọc; huỷ thông báo hẹn giờ trước khi gửi.', notes: 'câu hỏi: tài liệu không có bước xem lại hay huỷ thông báo hẹn giờ; schema có gui_boi, hen_gio, da_doc (D8:214-221).' },
    { name: 'Đọc thông báo trong app', src: ['D4:356', 'D4:364', 'M-06', 'M-09', 'D8:218-222'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhận thông báo đẩy và đọc lại trong mục Thông báo của app; thông báo đã mở được đánh dấu đã đọc.' },
    { name: 'Cài đặt nhận thông báo', src: ['BR-TB-04', 'M-09'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Phụ huynh tắt hoặc bật nhận thông báo thường như nhắc lịch; thông báo khẩn luôn nhận, không có nút tắt.', notes: 'câu hỏi: BR-TB-04 chỉ ở độ tin cậy I, ngụ ý phụ huynh tắt được thông báo khác nhưng không nói loại nào.' },
    { name: 'Cấu hình nhắc lịch', src: ['BR-TB-02', 'D8:224-229', 'M-09'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý bật hoặc tắt nhắc lịch tự động và sửa mẫu nội dung tin nhắc; nhắc trước giờ học 2 tiếng (truoc_phut mặc định 120).', notes: 'câu hỏi: schema có truoc_phut nhưng BR-TB-02 không nói quản lý đổi được thời gian nhắc.' },
    { name: 'Gửi nhắc lịch trước giờ học', src: ['BR-TB-02', 'D4:29', 'D8:224-229', 'M-09'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Khi nhắc lịch đang bật, hệ thống gửi thông báo đẩy cho phụ huynh trước mỗi buổi học 2 tiếng, theo mẫu nội dung quản lý đã đặt.', notes: 'mâu thuẫn: buổi trước 9:00 thì giờ nhắc rơi ngoài khung 7:00–21:00 (D1:89 với D1:90); câu hỏi ở cổng. Ca vi mô (suy): buổi đã huỷ hay đã báo nghỉ thì không nhắc; phụ huynh nhiều con nhận nhắc theo từng bé.' },
    { name: 'Xem thông báo nội bộ', src: ['XD-04', 'XD-02', 'M-03'], roles: ['quan-ly'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Quản lý xem các báo nội bộ trên web quản trị: lễ tân vừa huỷ buổi vì sự cố, yêu cầu đổi lịch quá 24 giờ chưa xử lý.', notes: 'câu hỏi: XD-04, XD-02 nói quản lý được báo nhưng không nói qua kênh nào (web quản trị, email, app).' },
    { name: 'Gửi SMS cho phụ huynh chưa cài app', src: ['CO-02', 'BR-TB-01'], roles: [], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'Phụ huynh chưa cài app (khoảng 15 %) nhận thông báo qua SMS; giai đoạn 2.', notes: 'Chưa rõ hệ thống tự gửi SMS thay hay người gửi chọn kênh.' },
  ],
  skip: [],
};
