window.PART = {
  module: 'diem-danh',
  features: [
    { name: 'Điểm danh buổi học', src: ['UC-05', 'M-04', 'YC-06', 'BR-DD-01', 'BR-DD-03', 'A-05', 'A-10', 'D4:111', 'D8:99-113'], roles: ['hlv', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh', 'trang_thai_diem_danh.co_mat', 'trang_thai_diem_danh.vang_khong_phep'], spec: 'Máy tính bảng ở thành bể: chọn buổi đang diễn ra; bé đã báo nghỉ hiện sẵn vắng có phép, bé học thử có nhãn; Có mặt tất cả rồi đổi từng bé vắng; lưu thì trừ buổi. Bé hết buổi/hết hạn bị đánh dấu, không chọn Có mặt được, đưa ra quầy mua gói (A-05). Mất mạng: lưu tạm, tự gửi lại (A-10). Quản lý cũng điểm danh được.', notes: 'ca vi mô: HLV có được chọn vắng có phép tại bể không, khi XD-01 chỉ tính báo trước 2 giờ?; máy gửi bù sau 23:00 khi buổi đã bị chốt vắng không phép (A-10 chồng BR-DD-02): bản gửi bù đè hay phải sửa theo BR-DD-05?; HLV dạy thay (A-02) điểm danh buổi dạy thay' },
    { name: 'Sửa điểm danh', src: ['BR-DD-05', 'UC-05', 'M-04', 'D8:114-115'], roles: ['hlv', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'Đổi trạng thái của bé sau khi đã lưu. HLV: buổi mình dạy, trong 24 giờ sau buổi. Quá 24 giờ chỉ Quản lý sửa, bắt buộc ghi lý do; lưu người sửa. Số buổi trừ tính lại theo BR-DD-03.' },
    { name: 'Chốt điểm danh cuối ngày', src: ['BR-DD-02', 'UC-05', 'M-04', 'D4:29'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_khong_phep'], spec: '23:00 hằng ngày hệ thống ghi vắng không phép cho bé chưa có trạng thái trong các buổi đã qua, trừ một buổi (BR-DD-03). HLV vẫn sửa được trong 24 giờ sau buổi (BR-DD-05).' },
    { name: 'Báo nghỉ một buổi', src: ['UC-07', 'M-06', 'YC-08', 'BR-DD-03', 'BR-DD-04', 'XD-01', 'A-04'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep', 'trang_thai_diem_danh.vang_khong_phep'], spec: 'App: chọn buổi sắp tới, Báo nghỉ, lý do ốm/bận/khác không bắt buộc. Báo trước giờ học ít nhất 2 giờ (theo XD-01) và chưa quá 3 lần mỗi gói thì vắng có phép, không trừ buổi; báo muộn hay lần thứ 4 vẫn nhận, ghi vắng không phép, app nói rõ bị trừ (A-04). Lễ tân, HLV thấy trên danh sách buổi.', notes: 'mâu thuẫn: D4:284 (tiền điều kiện: buổi chưa bắt đầu) với D2:31 (A-04: app vẫn nhận khi buổi đã bắt đầu)' },
    { name: 'Ghi báo nghỉ thay phụ huynh tại quầy', src: ['XD-01', 'D6:18', 'CO-02', 'D4:111'], roles: ['le-tan'], freq: 'ngay', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep'], spec: 'Phụ huynh gọi điện hay nói ở quầy: lễ tân chọn bé, chọn buổi, ghi báo nghỉ theo cùng luật 2 giờ và 3 lần mỗi gói như trên app.', notes: 'suy từ XD-01 (quầy thực tế nhận báo nghỉ sát giờ) và CO-02 (khoảng 15 % phụ huynh chưa dùng app); UC-07 chỉ có app, ma trận quyền không cho Lễ tân điểm danh: lễ tân có được ghi báo nghỉ không?' },
    { name: 'Xếp buổi học bù cho buổi vắng có phép', src: ['D8:104', 'D8:112'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_diem_danh.da_hoc_bu'], spec: 'Chọn buổi vắng có phép của bé, xếp vào một buổi ở lớp cùng cấp độ; khi bé học buổi bù, buổi vắng chuyển sang đã học bù.', notes: 'chỉ có ở schema (D8:104, 112), không UC, không quy tắc: ai xếp, mỗi gói được bù mấy buổi, buổi bù có trừ buổi không?' },
    { name: 'Xem các buổi đã học của con', src: ['UC-05', 'M-06', 'D4:233'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'App phụ huynh: các buổi đã qua của con kèm trạng thái có mặt, vắng có phép, vắng không phép, đã học bù, và buổi đó có bị trừ không. Phụ huynh nhiều con thì chọn con.' },
  ],
  skip: [],
};
