window.PART = {
  module: 'hoc-vien',
  features: [
    { name: 'Tìm học viên', src: ['YC-01', 'M-01', 'D4:151', 'D4:105'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Gõ tên, mã SX-0001 hoặc SĐT phụ huynh, có kết quả từ ký tự thứ ba. Danh sách có nhãn trạng thái học thử, đang học, ngừng học và lọc theo trạng thái. HLV chỉ thấy học viên lớp mình.' },
    { name: 'Xem hồ sơ học viên', src: ['M-01', 'D4:150', 'D4:105', 'BR-HV-03'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Trang chi tiết: thông tin, ghi chú sức khoẻ, trạng thái, phụ huynh và anh chị em cùng phụ huynh, gói học, các buổi đã học. HLV chỉ xem học viên lớp mình.', notes: 'câu hỏi mở OQ-03 (D2:45): HLV có được xem SĐT phụ huynh của lớp mình không' },
    { name: 'Đăng ký học viên mới', src: ['UC-01', 'M-01', 'YC-01', 'BR-HV-01', 'BR-HV-02', 'BR-HV-04', 'S-03', 'YC-05'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.hoc_thu'], spec: 'Tìm phụ huynh theo SĐT: có rồi thì hiện phụ huynh và các con, gắn học viên mới vào; chưa có thì tạo phụ huynh (họ tên, SĐT, quan hệ). Nhập họ tên, ngày sinh, giới tính, ghi chú sức khoẻ; dưới 6 tuổi bỏ trống thì không lưu. Hệ thống sinh mã SX-0001. Khách học thử lưu trạng thái học thử. Xong thì sang bán gói hoặc dừng.', notes: 'mâu thuẫn: D4:139 nhập giới tính, D8:25-34 bảng hoc_vien không có cột giới tính' },
    { name: 'Sửa hồ sơ học viên', src: ['D4:106', 'BR-HV-01', 'BR-HV-04', 'A-08'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sửa thông tin, ghi chú sức khoẻ, ghi chú chung. Mã học viên không đổi. Dưới 6 tuổi không được xoá trống ghi chú sức khoẻ. HLV không sửa được.', notes: 'A-08: lễ tân ghi chú yêu cầu hoàn tiền vào hồ sơ; bảng hoc_vien (D8:25-34) chưa có cột ghi chú chung' },
    { name: 'Sửa hồ sơ phụ huynh', src: ['YC-01', 'M-01', 'BR-HV-02', 'D8:11-17'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Sửa họ tên, SĐT, quan hệ với học viên. SĐT là duy nhất và là tài khoản đăng nhập app; đổi SĐT thì phụ huynh đăng nhập bằng số mới.', notes: 'câu hỏi: SĐT mới trùng một phụ huynh khác thì chặn hay gộp hai hồ sơ' },
    { name: 'Chuyển học viên sang ngừng học', src: ['BR-HV-05', 'D8:22'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.ngung_hoc'], spec: 'Không có nút xoá học viên. Học viên nghỉ hẳn thì chuyển trạng thái ngừng học, giữ nguyên lịch sử gói, buổi học, điểm danh; mã không dùng lại cho người khác.', notes: 'câu hỏi: ngừng học có tự rút khỏi lớp, trả chỗ và bỏ các buổi sắp tới không; gói còn buổi: xem A-08, OQ-01' },
    { name: 'Chuyển học viên sang đang học khi mua gói', src: ['D8:19-23', 'UC-02', 'S-03'], roles: [], freq: 'tuan', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_hoc_vien.dang_hoc'], spec: 'Học viên học thử hoặc đã ngừng học được bán gói thì hệ thống chuyển sang đang học; học lại vẫn giữ mã và lịch sử cũ.', notes: 'câu hỏi: nguồn chưa nói trạng thái ban đầu khi đăng ký không qua học thử, và ai chuyển sang đang học; giả định tự chuyển khi bán gói (UC-02)' },
    { name: 'Chọn con đang xem trên app', src: ['BR-HV-03', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhiều con chọn một con để xem; lịch, gói, số buổi, thông báo chỉ hiện của con đó, không trộn lịch các con. Chỉ một con thì vào thẳng.' },
    { name: 'Đăng nhập app bằng số điện thoại', src: ['D8:14', 'BR-HV-02', 'M-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhập SĐT đã khai ở quầy, nhận mã OTP. Tài khoản chính là hồ sơ phụ huynh, không có bước đăng ký riêng; vào xong thấy các con gắn với SĐT đó.', notes: 'suy: SĐT chưa có hồ sơ phụ huynh thì báo liên hệ quầy' },
  ],
  skip: [
    { src: 'D8:1-7', why: 'Đầu file schema, khai báo dự án; không có việc' },
  ],
};
