window.PART = {
  module: 'quan-tri',
  features: [
    { name: 'Xem báo cáo chuyên cần', src: ['UC-11', 'S-01', 'YC-13', 'D4:115'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoảng thời gian (mặc định tháng hiện tại); tỉ lệ đi học theo lớp và theo HLV, kèm số buổi vắng không phép. Quản lý và Lễ tân xem được, HLV không.' },
    { name: 'Xem báo cáo doanh thu', src: ['UC-11', 'S-01', 'YC-13', 'BR-QT-03', 'D4:116'], roles: ['quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoảng thời gian (mặc định tháng hiện tại); tổng thu theo tháng, theo loại gói, theo hình thức thanh toán. Chỉ Quản lý; Lễ tân không thấy doanh thu (BR-QT-03).' },
    { name: 'Xuất báo cáo ra file Excel', src: ['D4:117', 'UC-11', 'S-01'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Xuất báo cáo chuyên cần hoặc doanh thu theo khoảng thời gian đang chọn ra file Excel để gửi kế toán. Chỉ Quản lý (ma trận quyền); use case không có bước này.' },
    { name: 'Đăng nhập web quản trị', src: ['BR-QT-01', 'BR-QT-02', 'YC-14', 'M-08'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Mỗi nhân viên đăng nhập bằng tài khoản riêng; chỉ ba vai Quản lý, Lễ tân, HLV vào web quản trị, mỗi vai thấy đúng phần theo ma trận quyền; HLV chỉ thấy lớp mình phụ trách và học viên các lớp đó.' },
    { name: 'Đăng nhập app bằng số điện thoại và mã OTP', src: ['NF-05', 'BR-QT-01', 'M-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhập số điện thoại, nhận mã OTP, không cần mật khẩu. Phụ huynh chỉ dùng app, không vào web quản trị (BR-QT-01).' },
    { name: 'Thêm tài khoản nhân viên', src: ['UC-12', 'M-08', 'BR-QT-01', 'BR-QT-02', 'YC-14', 'D8:239-245'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhập họ tên, số điện thoại (không trùng), vai Quản lý, Lễ tân hoặc HLV; với HLV chọn các lớp phụ trách (BR-QT-02). Lưu xong hệ thống gửi mật khẩu tạm qua SMS cho nhân viên.', notes: 'câu hỏi mở OQ-03: HLV có được xem số điện thoại phụ huynh của lớp mình không (chặn BR-QT-02)' },
    { name: 'Sửa tài khoản nhân viên', src: ['UC-12', 'M-08', 'D4:118'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Đổi họ tên, số điện thoại, vai, và lớp phụ trách của HLV khi phân công thay đổi. UC-12 chỉ có thêm, khoá, mở khoá; suy từ "quản lý tài khoản và phân quyền".' },
    { name: 'Khoá tài khoản nhân viên nghỉ việc', src: ['UC-12', 'M-08', 'D4:411', 'D8:244'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhân viên nghỉ việc: Quản lý khoá tài khoản, không xoá, để giữ lịch sử và nhật ký thao tác; tài khoản bị khoá không đăng nhập được.' },
    { name: 'Mở khoá tài khoản nhân viên', src: ['UC-12', 'M-08', 'BR-QT-05', 'D4:412'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý mở khoá tài khoản bị khoá do nhập sai mật khẩu nhiều lần (nhánh 1b); nhân viên đăng nhập lại được.', notes: 'chưa rõ mở khoá có cấp lại mật khẩu tạm qua SMS không, và nhân viên quên mật khẩu thì làm gì' },
    { name: 'Tự khoá tài khoản khi nhập sai mật khẩu 5 lần', src: ['BR-QT-05', 'M-08', 'D8:244'], roles: [], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Nhân viên nhập sai mật khẩu 5 lần liền thì hệ thống khoá tài khoản; chỉ Quản lý mở khoá được.', notes: 'BR-QT-05 mức tin cậy I: BA suy ra, chưa xác nhận với chủ trung tâm' },
    { name: 'Đổi mật khẩu', src: ['BR-QT-05', 'UC-12', 'D4:407'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Nhân viên đổi mật khẩu tạm nhận qua SMS sang mật khẩu riêng, tối thiểu 8 ký tự (BR-QT-05). Suy từ "mật khẩu tạm"; tài liệu không có bước này.' },
    { name: 'Ghi nhật ký thao tác', src: ['BR-QT-04', 'M-08', 'D8:247-255'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Hệ thống tự ghi mỗi lần sửa điểm danh, duyệt hoàn tiền, tạm dừng gói, xoá học viên khỏi lớp: nhân viên nào, lúc nào, đối tượng, giá trị trước và sau.' },
    { name: 'Tra cứu nhật ký thao tác', src: ['BR-QT-04', 'M-08', 'D8:247-255'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý tra cứu nhật ký khi có khiếu nại: lọc theo nhân viên, loại thao tác, đối tượng, khoảng thời gian; xem ai làm, lúc nào, giá trị trước và sau.' },
  ],
  skip: [
    { src: 'D7:85-88', why: 'Yêu cầu phi chức năng NF-01 đến NF-04 (tốc độ, nền tảng, sao lưu tự động, định dạng): ràng buộc, không sinh việc' },
  ],
};
