window.PART = {
  module: 'thong-bao',
  features: [
    { name: 'Gửi thông báo cho phụ huynh', src: ['UC-10', 'YC-12', 'M-09', 'BR-TB-01', 'BR-TB-03', 'D4:114', 'D8:209-222'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn người nhận: cả trung tâm, theo lớp, theo cấp độ hay chọn nhiều phụ huynh; soạn tiêu đề, nội dung; gửi ngay hay hẹn giờ trong khung 7:00–21:00. Đánh dấu khẩn thì gửi ngay, ngoài khung giờ. HLV không gửi được.' },
    { name: 'Nhắc lịch học cho phụ huynh', src: ['BR-TB-02', 'BR-TB-01', 'M-09', 'D8:224-229'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Hệ thống tự gửi tin nhắc qua app cho phụ huynh trước giờ học (mặc định 120 phút), theo nội dung mẫu, chỉ khi Quản lý đang bật nhắc lịch.', notes: 'câu hỏi: buổi học sớm làm giờ nhắc rơi ngoài khung 7:00–21:00 của BR-TB-01, gửi lúc nào hay bỏ?' },
    { name: 'Cấu hình nhắc lịch', src: ['BR-TB-02', 'M-09', 'D8:224-229'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý bật hay tắt nhắc lịch tự động và sửa nội dung mẫu của tin nhắc; thời gian nhắc trước giờ học mặc định 120 phút.', notes: 'câu hỏi: BR-TB-02 chỉ nói bật, tắt và sửa mẫu; schema có truoc_phut, Quản lý có sửa được thời gian nhắc không?' },
    { name: 'Xem thông báo trên app', src: ['UC-10', 'M-06', 'M-09', 'D4:356', 'D8:218-222'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhận thông báo đẩy; mục Thông báo trên app liệt kê thông báo đã nhận, đọc lại được; thông báo chưa đọc được đánh dấu, mở ra thì thành đã đọc.' },
    { name: 'Gửi thông báo khẩn khi huỷ buổi', src: ['BR-TB-03', 'A-02', 'A-03', 'M-09', 'D8:213'], roles: [], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Khi buổi bị huỷ (từng buổi hay hàng loạt khi bể sự cố) hay có HLV dạy thay, hệ thống gửi ngay cho phụ huynh của các buổi đó, không theo khung 7:00–21:00; tin dạy thay ghi tên HLV thay.', notes: 'A-02 dẫn BR-TB-03: coi thông báo dạy thay là khẩn' },
    { name: 'Tắt nhận thông báo trên app', src: ['BR-TB-04', 'M-09'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Phụ huynh tắt được thông báo thường trên app; thông báo khẩn (huỷ buổi) luôn nhận, không tắt được.', notes: 'câu hỏi: BR-TB-04 còn 🟡 I; phụ huynh tắt được loại nào (nhắc lịch, thông báo chung), tắt đẩy hay tắt hẳn?' },
    { name: 'Xem thông báo trên web quản trị', src: ['XD-02', 'XD-04', 'D6:24', 'D6:35'], roles: ['quan-ly'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Quản lý nhận báo ngay khi lễ tân huỷ buổi vì sự cố (theo XD-04) và khi yêu cầu đổi lịch quá 24 giờ chưa xử lý (theo XD-02).', notes: 'câu hỏi: Quản lý nhận báo qua kênh nào? thong_bao_nguoi_nhan chỉ có phụ huynh làm người nhận' },
    { name: 'Xem thông báo đã gửi', src: ['UC-10', 'D8:209-222'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Danh sách thông báo đã gửi và đang hẹn giờ: tiêu đề, người nhận, người gửi, giờ gửi, khẩn hay không, số phụ huynh đã đọc.' },
    { name: 'Huỷ thông báo đã hẹn giờ', src: ['UC-10', 'BR-TB-01', 'D8:214'], roles: ['quan-ly', 'le-tan'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Thông báo hẹn giờ chưa tới giờ gửi thì người gửi huỷ được trước khi hệ thống gửi đi.' },
    { name: 'Gửi SMS cho phụ huynh chưa cài app', src: ['CO-02', 'BR-TB-01'], roles: [], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'Thông báo gửi thêm qua SMS cho phụ huynh chưa dùng app (khoảng 15 % phụ huynh lớn tuổi); GĐ2.', notes: 'hệ thống tự gửi SMS hay người gửi chọn: chưa rõ' },
  ],
  skip: [],
};
