window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'hom-nay-lt' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'hom-nay-ql' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'hom-nay-hlv' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'ph-trang-chu' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'quan-tri', name: 'Nhân viên và cài đặt', depends: [] },
    { id: 'lop-hoc', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'lich-buoi', name: 'Lịch và buổi học', depends: ['lop-hoc'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich-buoi', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien', 'lich-buoi'] },
    { id: 'app-phu-huynh', name: 'App phụ huynh', depends: ['lich-buoi', 'goi-hoc', 'thong-bao'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
  ],
  screens: [
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['le-tan', 'quan-ly', 'hlv'], entry: true, zones: ['Đăng nhập', 'Đổi mật khẩu lần đầu'] },
    { id: 'hom-nay-lt', name: 'Hôm nay', surface: 'web', module: 'hoc-vien', roles: ['le-tan'],
      bands: [{ name: 'Cần xử lý hôm nay', items: ['F-23', 'F-36'] }, { name: 'Việc nhanh', items: ['F-30', 'F-02', 'F-01', 'F-13'] }] },
    { id: 'hom-nay-ql', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      bands: [{ name: 'Số liệu tháng', items: ['F-64', 'F-63'] }, { name: 'Cần xử lý hôm nay', items: ['F-39'] }, { name: 'Việc nhanh', items: ['F-43', 'F-26'] }] },
    { id: 'hom-nay-hlv', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [{ name: 'Buổi hôm nay', items: ['F-28'] }, { name: 'Việc nhanh', items: ['F-02', 'F-29'] }] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Tìm và lọc', 'Công cụ', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Thông tin', 'Gói học', 'Thanh toán'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop-hoc', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop-hoc', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'lop', pick: true,
      zones: ['Đầu lớp'], tabs: ['Học viên', 'Danh sách chờ'] },
    { id: 'lich', name: 'Lịch trung tâm', surface: 'web', module: 'lich-buoi', roles: ['le-tan', 'quan-ly'], zones: ['Lưới lịch'] },
    { id: 'lich-day', name: 'Lịch dạy', surface: 'web', module: 'lich-buoi', roles: ['hlv'], zones: ['Lịch dạy', 'Buổi học thử'] },
    { id: 'doi-lich', name: 'Đổi lịch', surface: 'web', module: 'lich-buoi', roles: ['le-tan'], zones: ['Yêu cầu chờ xử lý', 'Đổi lịch'] },
    { id: 'diem-danh', name: 'Điểm danh', surface: 'web', module: 'diem-danh', roles: ['quan-ly', 'hlv'], zones: ['Danh sách buổi'] },
    { id: 'goi-hoc', name: 'Gói học', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], tabs: ['Gói đang dùng', 'Cần gọi gia hạn'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Đề nghị hoàn tiền'] },
    { id: 'gui-thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['le-tan', 'quan-ly'], zones: ['Soạn thông báo'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['le-tan', 'quan-ly'], tabs: ['Chuyên cần', 'Doanh thu', 'Gói đang bảo lưu'] },
    { id: 'khoa-hoc-lop', name: 'Khoá học và mở lớp', surface: 'web', module: 'lop-hoc', roles: ['quan-ly'], zones: ['Khoá học', 'Lớp'] },
    { id: 'tai-khoan', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch'] },
    { id: 'ph-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], entry: true, zones: ['Đăng nhập'] },
    { id: 'ph-trang-chu', name: 'Trang chủ', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'],
      bands: [{ name: 'Con đang xem', items: ['F-47'] }, { name: 'Buổi sắp tới', items: ['F-48', 'F-51', 'F-52'] }, { name: 'Yêu cầu của bạn', items: ['F-53'] }] },
    { id: 'ph-goi', name: 'Gói học', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Số buổi còn lại', 'Lịch sử đóng tiền'] },
    { id: 'ph-thong-bao', name: 'Thông báo', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'ph-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Tiến bộ của con'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: '', items: ['hom-nay-lt'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'lich', 'doi-lich'] },
      { name: 'Tiền', items: ['goi-hoc', 'hoan-tien'] },
      { name: 'Trung tâm', items: ['gui-thong-bao', 'bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: '', items: ['hom-nay-ql'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'lich', 'diem-danh'] },
      { name: 'Tiền', items: ['goi-hoc', 'hoan-tien', 'bao-cao'] },
      { name: 'Trung tâm', items: ['gui-thong-bao', 'khoa-hoc-lop', 'tai-khoan', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['hom-nay-hlv', 'lich-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['ph-trang-chu', 'ph-goi', 'ph-thong-bao', 'ph-tai-khoan'] }] },
  ],
  place: {
    'F-01': [{ screen: 'hoc-vien', zone: 'Công cụ', tier: 2, mo: 'ngan-truot' }, { screen: 'hom-nay-lt', zone: 'Việc nhanh', tier: 2, mo: 'ngan-truot' }],
    'F-02': [{ screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }, { screen: 'hom-nay-lt', zone: 'Việc nhanh', tier: 2, mo: 'tai-cho' }, { screen: 'hom-nay-hlv', zone: 'Việc nhanh', tier: 2, mo: 'tai-cho' }],
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'trang' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-06': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-07': { screen: 'hoc-vien', zone: 'Công cụ', tier: 2, mo: 'ngan-truot' },
    'F-08': { screen: 'lich-day', zone: 'Buổi học thử', tier: 2, mo: 'ngan-truot' },
    'F-09': { screen: 'lop-chi-tiet', zone: 'Đầu lớp', tier: 3, mo: 'hop-thoai' },
    'F-10': { screen: 'khoa-hoc-lop', zone: 'Khoá học', tier: 2, mo: 'ngan-truot' },
    'F-11': { screen: 'khoa-hoc-lop', zone: 'Lớp', tier: 1, mo: 'ngan-truot' },
    'F-12': { screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'tai-cho' },
    'F-13': [{ screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'ngan-truot' }, { screen: 'hom-nay-lt', zone: 'Việc nhanh', tier: 2, mo: 'ngan-truot' }],
    'F-14': { screen: 'lop', zone: 'Bảng lớp', tier: 3, mo: 'hop-thoai' },
    'F-15': { screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'hop-thoai' },
    'F-16': { screen: 'lop-chi-tiet', tab: 'Danh sách chờ', tier: 2, mo: 'tai-cho' },
    'F-17': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 3, mo: 'hop-thoai' },
    'F-18': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 1, mo: 'tai-cho' },
    'F-19': { screen: 'lich', zone: 'Lưới lịch', tier: 1, mo: 'tai-cho' },
    'F-20': [{ screen: 'lich-day', zone: 'Lịch dạy', tier: 1, mo: 'tai-cho' }, { screen: 'lich', zone: 'Lưới lịch', tier: 2, mo: 'tai-cho' }],
    'F-21': { screen: 'doi-lich', zone: 'Đổi lịch', tier: 2, mo: 'ngan-truot' },
    'F-22': { screen: 'doi-lich', zone: 'Đổi lịch', tier: 2, mo: 'ngan-truot' },
    'F-23': [{ screen: 'doi-lich', zone: 'Yêu cầu chờ xử lý', tier: 1, mo: 'ngan-truot' }, { screen: 'hom-nay-lt', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' }],
    'F-24': { screen: 'lich', zone: 'Lưới lịch', tier: 2, mo: 'ngan-truot' },
    'F-25': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 3, mo: 'tai-cho' },
    'F-26': { screen: 'lich', zone: 'Lưới lịch', tier: 3, mo: 'ngan-truot' },
    'F-27': { screen: 'lich', zone: 'Lưới lịch', tier: 3, mo: 'hop-thoai' },
    'F-28': { screen: 'diem-danh', zone: 'Danh sách buổi', tier: 1, mo: 'ngan-truot' },
    'F-29': { screen: 'diem-danh', zone: 'Danh sách buổi', tier: 2, mo: 'ngan-truot' },
    'F-30': [{ screen: 'goi-hoc', tab: 'Gói đang dùng', tier: 1, mo: 'ngan-truot' }, { screen: 'hom-nay-lt', zone: 'Việc nhanh', tier: 1, mo: 'ngan-truot' }],
    'F-31': { screen: 'goi-hoc', tab: 'Gói đang dùng', tier: 2, mo: 'tai-cho' },
    'F-32': { screen: 'ho-so', tab: 'Thanh toán', tier: 2, mo: 'tai-cho' },
    'F-33': { screen: 'ho-so', tab: 'Gói học', tier: 2, mo: 'tai-cho' },
    'F-34': { screen: 'goi-hoc', tab: 'Gói đang dùng', tier: 2, mo: 'hop-thoai' },
    'F-35': { screen: 'bao-cao', tab: 'Gói đang bảo lưu', tier: 3, mo: 'tai-cho' },
    'F-36': [{ screen: 'goi-hoc', tab: 'Cần gọi gia hạn', tier: 2, mo: 'tai-cho' }, { screen: 'hom-nay-lt', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' }],
    'F-37': { screen: 'goi-hoc', tab: 'Cần gọi gia hạn', tier: 2, mo: 'hop-thoai' },
    'F-38': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 1, mo: 'ngan-truot' },
    'F-39': [{ screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' }, { screen: 'hom-nay-ql', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'hop-thoai' }],
    'F-40': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-41': { screen: 'cai-dat', tab: 'Bảng giá', tier: 3, mo: 'tai-cho' },
    'F-42': { screen: 'goi-hoc', tab: 'Gói đang dùng', tier: 3, mo: 'hop-thoai' },
    'F-43': [{ screen: 'gui-thong-bao', zone: 'Soạn thông báo', tier: 1, mo: 'ngan-truot' }, { screen: 'hom-nay-ql', zone: 'Việc nhanh', tier: 2, mo: 'ngan-truot' }],
    'F-44': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 3, mo: 'tai-cho' },
    'F-45': { screen: 'gui-thong-bao', zone: 'Soạn thông báo', tier: 3, mo: 'hop-thoai' },
    'F-46': { screen: 'ph-dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'trang' },
    'F-47': { screen: 'ph-trang-chu', zone: 'Con đang xem', tier: 2, mo: 'sheet' },
    'F-48': { screen: 'ph-trang-chu', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-49': { screen: 'ph-goi', zone: 'Số buổi còn lại', tier: 1, mo: 'tai-cho' },
    'F-50': { screen: 'ph-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-51': { screen: 'ph-trang-chu', zone: 'Buổi sắp tới', tier: 2, mo: 'sheet' },
    'F-52': { screen: 'ph-trang-chu', zone: 'Buổi sắp tới', tier: 2, mo: 'sheet' },
    'F-53': { screen: 'ph-trang-chu', zone: 'Yêu cầu của bạn', tier: 2, mo: 'tai-cho' },
    'F-54': { screen: 'ph-thong-bao', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-55': { screen: 'ph-tai-khoan', zone: 'Tiến bộ của con', tier: 3, mo: 'tai-cho' },
    'F-56': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'trang' },
    'F-57': { screen: 'dang-nhap', zone: 'Đổi mật khẩu lần đầu', tier: 2, mo: 'hop-thoai' },
    'F-58': { screen: 'tai-khoan', zone: 'Nhân viên', tier: 1, mo: 'ngan-truot' },
    'F-59': { screen: 'tai-khoan', zone: 'Nhân viên', tier: 2, mo: 'ngan-truot' },
    'F-60': { screen: 'tai-khoan', zone: 'Nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-61': { screen: 'tai-khoan', zone: 'Nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-62': { screen: 'nhat-ky', zone: 'Nhật ký', tier: 1, mo: 'tai-cho' },
    'F-63': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }, { screen: 'hom-nay-ql', zone: 'Số liệu tháng', tier: 2, mo: 'tai-cho' }],
    'F-64': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'hom-nay-ql', zone: 'Số liệu tháng', tier: 1, mo: 'tai-cho' }],
    'F-65': { screen: 'bao-cao', tab: 'Doanh thu', tier: 3, mo: 'hop-thoai' },
  },
  shortcuts: [
    { from: 'ho-so', to: 'F-30', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-34', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-21', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-22', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-13', mo: 'ngan-truot' },
    { from: 'hom-nay-hlv', to: 'F-28', mo: 'ngan-truot' },
    { from: 'hom-nay-hlv', to: 'F-29', mo: 'ngan-truot' },
    { from: 'hom-nay-ql', to: 'F-26', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới đến học thử rồi đăng ký', steps: ['F-07', 'F-01', 'F-30', 'F-13'] },
    { role: 'le-tan', name: 'Phụ huynh xin đổi lịch trên app', steps: ['F-23', 'F-21'] },
    { role: 'le-tan', name: 'Gọi mời gia hạn', steps: ['F-36', 'F-37', 'F-30'] },
    { role: 'quan-ly', name: 'Bể sự cố đột xuất', steps: ['F-26', 'F-43'] },
    { role: 'quan-ly', name: 'Có HLV mới', steps: ['F-58', 'F-59'] },
    { role: 'hlv', name: 'Một buổi dạy', steps: ['F-20', 'F-28', 'F-29'] },
    { role: 'phu-huynh', name: 'Con ốm, báo nghỉ', steps: ['F-46', 'F-47', 'F-48', 'F-51'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một phụ huynh dắt con đến lần đầu, muốn cho bé học bơi.', feature: 'F-01' },
    { role: 'le-tan', say: 'Một phụ huynh đến quầy đóng tiền cho con học tiếp.', feature: 'F-30' },
    { role: 'le-tan', say: 'Phụ huynh nhắn rằng chiều thứ Tư bé bận, xin học vào hôm khác.', feature: 'F-21' },
    { role: 'le-tan', say: 'Đầu ca sáng, xem phụ huynh nào đã nhờ đổi buổi qua app để trả lời.', feature: 'F-23' },
    { role: 'le-tan', say: 'Có bé chỉ còn một buổi, cần nhắc phụ huynh học tiếp.', feature: 'F-36' },
    { role: 'le-tan', say: 'Lớp Cơ bản tối thứ Ba đã đầy mà vẫn có một bé muốn vào.', feature: 'F-15' },
    { role: 'quan-ly', say: 'Cuối tháng, chủ trung tâm muốn biết tháng này thu được bao nhiêu.', feature: 'F-64' },
    { role: 'quan-ly', say: 'Sáng thứ Hai, muốn nhìn cả tuần xem làn nào còn trống.', feature: 'F-19' },
    { role: 'hlv', say: 'Đến giờ dạy 17:30, tay ướt, cần ghi bé nào đến, bé nào nghỉ.', feature: 'F-28' },
    { role: 'phu-huynh', say: 'Sáng nay bé sốt, chiều có buổi bơi.', feature: 'F-51' },
  ],
};
