// Kiểm kê chức năng (M1) · Sóng Xanh · nguồn: docs/yeu-cau (D1–D7, xem map/sources.json)
window.FEATURES = {
  project: 'Sóng Xanh',
  features: [
    // ===== Học viên, phụ huynh =====
    { id: 'F-01', name: 'Tìm học viên', module: 'hoc-vien', src: ['UC-01', 'YC-01', 'M-01'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Tìm theo tên, mã học viên hoặc số điện thoại phụ huynh, ra kết quả từ ký tự thứ ba. HLV chỉ thấy học viên lớp mình (BR-QT-02).' },
    { id: 'F-02', name: 'Đăng ký học viên mới', module: 'hoc-vien', src: ['UC-01', 'BR-HV-01', 'BR-HV-02', 'BR-HV-04', 'M-01'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Tìm phụ huynh theo số điện thoại; có rồi thì gắn con mới vào, chưa có thì tạo. Nhập học viên; dưới 6 tuổi bắt buộc ghi chú sức khoẻ. Hệ thống sinh mã SX-0001. Xong thì sang bán gói hoặc dừng.' },
    { id: 'F-03', name: 'Xem hồ sơ học viên', module: 'hoc-vien', src: ['UC-01', 'UC-02', 'BR-QT-02', 'OQ-03', 'D3:105'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Thông tin, phụ huynh và các con khác, gói học, các buổi đã học, các lần đóng tiền và biên lai, trạng thái học thử, đang học, ngừng học. HLV chỉ xem học viên lớp mình.', notes: 'câu hỏi: HLV có xem số điện thoại phụ huynh không (OQ-03)' },
    { id: 'F-04', name: 'Sửa hồ sơ học viên và phụ huynh', module: 'hoc-vien', src: ['D3:106', 'M-01'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sửa thông tin học viên, ghi chú sức khoẻ, thông tin phụ huynh. Số điện thoại phụ huynh vẫn phải duy nhất (BR-HV-02). Mã học viên không đổi.' },
    { id: 'F-05', name: 'Cho học viên ngừng học', module: 'hoc-vien', src: ['BR-HV-05'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.ngung_hoc'], spec: 'Không xoá hồ sơ: chuyển sang ngừng học, giữ nguyên lịch sử gói, điểm danh, đóng tiền.' },
    { id: 'F-06', name: 'Chọn con đang xem', module: 'hoc-vien', src: ['BR-HV-03'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhiều con xem từng con một trên app, không trộn lịch các con; đổi con ở mọi màn của app.' },

    // ===== Học thử =====
    { id: 'F-07', name: 'Đặt buổi học thử', module: 'hoc-thu', src: ['BR-LH-06', 'S-03', 'YC-05'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.hoc_thu'], spec: 'Mỗi bé một buổi miễn phí, ở lớp còn chỗ đúng độ tuổi. Hồ sơ học thử không mua gói thì giữ 60 ngày. Mua gói thì thành học viên chính thức, giữ kết quả học thử.' },
    { id: 'F-08', name: 'Ghi cấp độ gợi ý sau buổi học thử', module: 'hoc-thu', src: ['BR-LH-06', 'S-03'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sau buổi học thử, HLV chọn cấp độ gợi ý (Làm quen nước, Cơ bản, Nâng cao); lễ tân dùng khi bán gói và xếp lớp.' },

    // ===== Khoá học, lớp =====
    { id: 'F-09', name: 'Tạo khoá học', module: 'lop', src: ['UC-03', 'BR-LH-01', 'BR-LH-05', 'XD-03', 'M-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tên, cấp độ, số buổi một tuần, sĩ số tối đa: Làm quen nước 6 bé (theo XD-03), các lớp khác 10 bé.' },
    { id: 'F-10', name: 'Mở lớp', module: 'lop', src: ['UC-03', 'BR-LH-02', 'BR-LI-01', 'YC-02', 'M-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoá, HLV chính, ngày trong tuần, giờ bắt đầu, bể và làn. Trùng HLV hay trùng làn thì chỉ ra lớp bị trùng để đổi giờ, đổi làn. Lưu xong hệ thống sinh buổi học.', notes: 'HLV phụ trách lớp gán ở hai chỗ: mở lớp (UC-03 bước 2) và tài khoản HLV (UC-12 bước 2)' },
    { id: 'F-11', name: 'Xem lớp: sĩ số, học viên, danh sách chờ', module: 'lop', src: ['UC-04', 'YC-03', 'BR-QT-02'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop'], spec: 'Danh sách lớp lọc theo cấp độ, ngày, giờ; sĩ số và chỗ trống từng lớp. Chi tiết lớp: học viên đang học, danh sách chờ theo thứ tự đăng ký. HLV chỉ thấy lớp mình.' },
    { id: 'F-12', name: 'Xếp học viên vào lớp', module: 'lop', src: ['UC-04', 'BR-LH-03', 'A-01', 'A-06', 'M-02'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc'], spec: 'Chọn lớp còn chỗ đúng cấp độ; sinh buổi học tới hết gói. Lưu sau người khác vào chỗ cuối thì báo lớp vừa đủ, gợi ý danh sách chờ. Anh chị em trùng giờ thì cảnh báo, vẫn lưu được.', notes: 'xếp xuống một bậc cần quản lý cho phép (BR-LH-03): tài liệu không nói cho phép bằng cách nào' },
    { id: 'F-13', name: 'Đưa học viên vào danh sách chờ', module: 'lop', src: ['BR-LH-04', 'UC-04'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.cho_cho'], spec: 'Lớp đủ sĩ số thì học viên vào danh sách chờ của lớp đó, ghi thứ tự theo giờ đăng ký.' },
    { id: 'F-14', name: 'Gọi học viên trong danh sách chờ khi lớp có chỗ', module: 'lop', src: ['BR-LH-04', 'M-02'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Lớp có chỗ trống thì lễ tân thấy danh sách chờ theo thứ tự đăng ký, gọi phụ huynh người đăng ký trước, rồi xếp vào lớp.' },
    { id: 'F-15', name: 'Xoá học viên khỏi lớp', module: 'lop', src: ['BR-QT-04'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.da_roi'], spec: 'Học viên rời lớp, giữ lịch sử; ghi nhật ký ai làm, lúc nào, trước và sau (BR-QT-04).' },

    // ===== Lịch, buổi học =====
    { id: 'F-16', name: 'Xem lịch tuần toàn trung tâm', module: 'lich', src: ['YC-04', 'D3:109'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi'], spec: 'Lưới làn × giờ theo ngày và theo tuần: lớp nào, làn nào, HLV nào, còn bao nhiêu chỗ; buổi bị huỷ, buổi dạy thay. Bấm một lớp mở ngăn chi tiết lớp.' },
    { id: 'F-17', name: 'Xem lịch dạy của tôi', module: 'lich', src: ['UC-05', 'D3:110', 'BR-QT-02'], roles: ['hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Các buổi dạy hôm nay và trong tuần của HLV, buổi đang diễn ra lên đầu; chỉ lớp mình phụ trách. Quản lý, lễ tân xem lịch dạy của HLV bất kỳ trên lịch tuần.' },
    { id: 'F-18', name: 'Sinh buổi học theo khung giờ lớp', module: 'lich', src: ['BR-LI-01', 'BR-LI-04', 'M-03'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi.du_kien'], spec: 'Hệ thống sinh buổi từ ngày khai giảng tới hết đợt; ngày nghỉ lễ không sinh, buổi rơi vào ngày lễ dời sang tuần sau.' },
    { id: 'F-19', name: 'Khai báo ngày nghỉ lễ', module: 'lich', src: ['BR-LI-04'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Thêm, sửa danh sách ngày nghỉ lễ của trung tâm; buổi rơi vào ngày lễ tự dời sang tuần sau. Tài liệu có danh sách nhưng không nói ai khai báo.' },
    { id: 'F-20', name: 'Đổi lịch học', module: 'lich', src: ['UC-08', 'BR-LI-02', 'XD-02', 'A-07', 'OQ-02', 'M-03'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Từ hồ sơ học viên: đổi một buổi hoặc chuyển lớp cố định. Gợi ý lớp cùng cấp độ còn chỗ, lớp cùng HLV lên trước. HLV hai lớp thấy thay đổi. Phụ huynh không tự đổi (theo XD-02).', notes: 'HLV đề xuất lên cấp độ giữa chừng (A-07): chuyển lớp giữ số buổi; chưa rõ thu chênh lệch giá (OQ-02)' },
    { id: 'F-21', name: 'Gửi yêu cầu đổi lịch', module: 'lich', src: ['XD-02', 'YC-07', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_yeu_cau_doi.cho_xu_ly'], spec: 'Theo XD-02 (thay việc tự đổi của YC-07): chọn buổi muốn đổi, gợi ý ngày hoặc khung giờ, ghi chú. Thấy trạng thái yêu cầu: chờ xử lý, đã đổi, bị từ chối kèm lý do.' },
    { id: 'F-22', name: 'Xử lý yêu cầu đổi lịch', module: 'lich', src: ['XD-02', 'UC-08', 'M-03'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_yeu_cau_doi', 'trang_thai_yeu_cau_doi.da_doi', 'trang_thai_yeu_cau_doi.tu_choi'], spec: 'Danh sách yêu cầu chờ xử lý, cũ nhất trên đầu. Đổi theo luồng đổi lịch học, hoặc từ chối kèm lý do. Quá 24 giờ chưa xử lý thì quản lý được báo.' },
    { id: 'F-23', name: 'Huỷ buổi học do trung tâm', module: 'lich', src: ['A-03', 'XD-04', 'BR-TT-07', 'BR-TB-03', 'YC-14'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi.huy_do_trung_tam'], spec: 'Theo XD-04 lễ tân huỷ, quản lý cũng huỷ được. Chọn khoảng giờ bị ảnh hưởng, huỷ mọi buổi một lần, chọn lý do sự cố. Mỗi gói được cộng một buổi; phụ huynh nhận thông báo khẩn; quản lý được báo ngay.' },
    { id: 'F-24', name: 'Phân HLV dạy thay', module: 'lich', src: ['A-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'HLV báo nghỉ đột xuất: chọn HLV khác dạy thay các buổi trong ngày, lớp vẫn thuộc HLV cũ; phụ huynh nhận thông báo tên HLV dạy thay. Không ai thay thì huỷ buổi do trung tâm.', notes: 'mâu thuẫn: D2:29 với D1:99 (HLV dạy thay cần thấy học viên để điểm danh, nhưng HLV chỉ thấy lớp mình phụ trách và lớp vẫn thuộc HLV cũ)' },
    { id: 'F-25', name: 'Xem lịch học của con', module: 'lich', src: ['UC-06', 'YC-11', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Màn đầu của app: các buổi sắp tới, buổi gần nhất ở trên; buổi đã học kèm trạng thái điểm danh, buổi bị huỷ, HLV dạy thay. Chưa có gói thì hiện số điện thoại quầy và giờ làm việc.' },

    // ===== Điểm danh =====
    { id: 'F-26', name: 'Điểm danh buổi học', module: 'diem-danh', src: ['UC-05', 'BR-DD-01', 'BR-DD-03', 'BR-TT-04', 'A-05', 'A-10', 'YC-06', 'M-04'], roles: ['hlv', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh', 'trang_thai_diem_danh.co_mat', 'trang_thai_buoi.da_dien_ra'], spec: 'Mở buổi đang diễn ra; ai báo nghỉ hiện sẵn vắng có phép. Có mặt tất cả rồi đổi bé vắng; lưu thì trừ buổi. Bé hết buổi, hết hạn bị đánh dấu, không điểm danh có mặt được. Mất mạng thì lưu tạm, tự gửi lại.' },
    { id: 'F-27', name: 'Sửa điểm danh', module: 'diem-danh', src: ['BR-DD-05', 'BR-QT-04', 'M-04'], roles: ['hlv', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'HLV sửa buổi mình dạy trong 24 giờ sau buổi. Quá 24 giờ chỉ quản lý sửa, bắt buộc ghi lý do. Mỗi lần sửa ghi nhật ký trước và sau.' },
    { id: 'F-28', name: 'Chốt điểm danh cuối ngày', module: 'diem-danh', src: ['BR-DD-02', 'M-04'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_khong_phep'], spec: '23:00 mỗi ngày, học viên chưa có trạng thái trong buổi đã qua được ghi vắng không phép, trừ buổi.' },
    { id: 'F-29', name: 'Báo nghỉ một buổi', module: 'diem-danh', src: ['UC-07', 'BR-DD-03', 'BR-DD-04', 'XD-01', 'A-04', 'YC-08', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep'], spec: 'Chọn buổi sắp tới, lý do (ốm, bận, khác) không bắt buộc. Báo trước 2 giờ là vắng có phép (theo XD-01), tối đa 3 lần mỗi gói; muộn hơn hay quá số lần thì vắng không phép. App nói rõ buổi có bị trừ không.', notes: 'mâu thuẫn: D3:284 với D2:31 (tiền điều kiện UC-07 là buổi chưa bắt đầu; A-04 cho app nhận báo nghỉ cả khi buổi đã bắt đầu)' },
    { id: 'F-30', name: 'Ghi báo nghỉ thay phụ huynh', module: 'diem-danh', src: ['XD-01', 'CO-02'], roles: ['le-tan'], freq: 'ngay', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep'], spec: 'Phụ huynh gọi quầy báo nghỉ (quầy vẫn nhận tới sát giờ, khoảng 15 % phụ huynh chưa dùng app): lễ tân ghi báo nghỉ cho buổi đó theo cùng luật 2 giờ và 3 lần mỗi gói.' },
    { id: 'F-31', name: 'Xếp buổi học bù', module: 'diem-danh', src: ['D7:104'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.da_hoc_bu'], spec: 'Buổi vắng có phép được bù bằng một buổi ở lớp cùng cấp độ còn chỗ; học xong buổi bù thì buổi vắng chuyển sang đã học bù.', notes: 'chỉ có ở schema (D7:104): UC, BR không nói ai xếp buổi bù, có giới hạn thời gian hay không' },

    // ===== Gói học, thanh toán =====
    { id: 'F-32', name: 'Bán gói học và thu tiền', module: 'goi-hoc', src: ['UC-02', 'BR-TT-01', 'BR-TT-02', 'BR-TT-03', 'A-05', 'A-09', 'BR-LH-06', 'YC-10', 'M-05'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.dang_dung', 'trang_thai_goi.cho_xac_nhan_tien', 'trang_thai_hoc_vien.dang_hoc'], spec: 'Gói 8, 12, 24 buổi theo cấp độ, giá hiện hành. Tiền mặt hay chuyển khoản; sinh mã biên lai, in. Còn gói thì nối tiếp. Bấm hai lần chỉ ghi một khoản. Bé học thử mua gói thì thành học viên chính thức.' },
    { id: 'F-33', name: 'Xác nhận tiền chuyển khoản đã về', module: 'goi-hoc', src: ['UC-02', 'M-05'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.dang_dung'], spec: 'Gói chờ xác nhận tiền chưa dùng được; lễ tân xác nhận tiền đã về thì gói chuyển sang đang dùng.' },
    { id: 'F-34', name: 'Xem danh sách gói học theo trạng thái', module: 'goi-hoc', src: ['UC-09', 'BR-TT-04'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi'], spec: 'Lọc gói chờ xác nhận tiền, đang dùng, bảo lưu, hết buổi, hết hạn. Quản lý xem gói đang bảo lưu. Gói hết buổi hay hết hạn thì học viên không vào lớp được tới khi mua gói mới.' },
    { id: 'F-35', name: 'Bảo lưu gói học', module: 'goi-hoc', src: ['UC-09', 'BR-TT-05', 'BR-QT-04', 'YC-09', 'M-07'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.bao_luu'], spec: 'Còn gọi là tạm dừng gói. Mỗi gói một lần, tối đa 30 ngày; chọn ngày bắt đầu, số ngày. Giữ chỗ trong lớp, ngừng sinh buổi, hạn cộng thêm đúng số ngày. Hết bảo lưu sinh lại buổi; lớp cũ đủ thì xếp lớp khác.' },
    { id: 'F-36', name: 'Gọi mời gia hạn', module: 'goi-hoc', src: ['BR-TT-06', 'S-02'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Danh sách học viên còn từ 2 buổi trở xuống; lễ tân gọi phụ huynh và ghi kết quả cuộc gọi, rồi bán gói tiếp nếu đồng ý.' },
    { id: 'F-37', name: 'Lập đề nghị hoàn tiền', module: 'goi-hoc', src: ['BR-TT-08', 'A-08', 'OQ-01'], roles: ['le-tan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien.cho_duyet'], spec: 'Gói đã hết hạn còn buổi do trung tâm huỷ chưa bù được: quy ra tiền theo giá một buổi của gói, lập đề nghị chờ quản lý duyệt.', notes: 'không có hạng mục riêng trong bảng ưu tiên; coi là GĐ1 vì BR-QT-04 (thuộc M-08) ghi nhật ký duyệt hoàn tiền. Phụ huynh xin hoàn vì chuyển nhà (A-08): chưa có chính sách (OQ-01), tạm ghi chú hồ sơ, báo quản lý' },
    { id: 'F-38', name: 'Duyệt đề nghị hoàn tiền', module: 'goi-hoc', src: ['BR-TT-08', 'BR-QT-04'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien', 'trang_thai_hoan_tien.da_duyet', 'trang_thai_hoan_tien.tu_choi'], spec: 'Danh sách đề nghị theo trạng thái; quản lý duyệt hoặc từ chối, ghi nhật ký.' },
    { id: 'F-39', name: 'Ghi ngày đã chi hoàn tiền', module: 'goi-hoc', src: ['BR-TT-08'], roles: ['le-tan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien.da_chi'], spec: 'Kế toán chi ngoài hệ thống; lễ tân ghi ngày đã chi cho đề nghị đã duyệt.' },
    { id: 'F-40', name: 'Sửa bảng giá gói học', module: 'goi-hoc', src: ['BR-TT-03', 'D6:106', 'M-05'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Giá theo cấp độ và gói 8, 12, 24 buổi, kèm ngày áp dụng. Giá mới chỉ áp cho gói bán từ ngày đó; gói đã bán giữ giá cũ. Đổi khoảng hai lần một năm, có giá riêng đợt hè.' },
    { id: 'F-41', name: 'Xem gói học và số buổi còn lại', module: 'goi-hoc', src: ['UC-06', 'YC-11', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Số buổi còn lại, hạn dùng, số lần vắng có phép đã dùng, gói đang bảo lưu nếu có.' },
    { id: 'F-42', name: 'Xem lịch sử đóng tiền', module: 'goi-hoc', src: ['UC-06', 'YC-11'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Mỗi lần đóng: ngày, gói, số tiền, mã biên lai.' },
    { id: 'F-43', name: 'Đối chiếu tiền thu cuối ngày', module: 'goi-hoc', src: ['M-05', 'D6:24'], roles: ['le-tan'], freq: 'ngay', evidence: 'suy', status: 'pham-vi', spec: 'Cuối ca, lễ tân xem các khoản mình đã thu trong ngày theo tiền mặt và chuyển khoản để đối chiếu với tiền trong két.', notes: 'lễ tân không xem doanh thu (BR-QT-03): đối chiếu chỉ gồm khoản thu trong ca' },
    { id: 'F-44', name: 'Áp mã khuyến mãi khi bán gói', module: 'goi-hoc', src: ['CO-01'], roles: ['le-tan'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'GĐ2. Nhập mã khuyến mãi lúc bán gói thay cho giảm tay đợt hè; cách tạo mã chưa đặc tả.' },

    // ===== Thông báo =====
    { id: 'F-45', name: 'Gửi thông báo cho phụ huynh', module: 'thong-bao', src: ['UC-10', 'BR-TB-01', 'BR-TB-03', 'YC-12', 'M-09'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Người nhận: cả trung tâm, theo lớp, theo cấp độ, hay chọn nhiều phụ huynh. Tiêu đề, nội dung; gửi ngay hay hẹn giờ trong 7:00–21:00. Thông báo khẩn gửi ngay, ngoài khung giờ.' },
    { id: 'F-46', name: 'Cài đặt nhắc lịch tự động', module: 'thong-bao', src: ['BR-TB-02', 'M-09'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Bật hoặc tắt nhắc lịch, sửa nội dung mẫu của tin nhắc; nhắc trước giờ học 2 tiếng.' },
    { id: 'F-47', name: 'Gửi nhắc lịch trước giờ học', module: 'thong-bao', src: ['BR-TB-02'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Hệ thống tự gửi tin nhắc cho phụ huynh trước giờ học 2 tiếng khi việc nhắc đang bật.' },
    { id: 'F-48', name: 'Xem thông báo', module: 'thong-bao', src: ['UC-10', 'M-06', 'M-09'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Mục Thông báo của app: đọc lại thông báo đẩy, đánh dấu đã đọc; thông báo khẩn (huỷ buổi, dạy thay) nổi bật.' },
    { id: 'F-49', name: 'Tắt thông báo không khẩn', module: 'thong-bao', src: ['BR-TB-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Phụ huynh tắt thông báo thường hay tin nhắc lịch; thông báo khẩn không tắt được (BR-TB-04 còn 🟡 I).' },
    { id: 'F-50', name: 'Xem cảnh báo vận hành', module: 'thong-bao', src: ['XD-02', 'XD-04'], roles: ['quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý được báo ngay khi lễ tân huỷ buổi do sự cố, và khi yêu cầu đổi lịch quá 24 giờ chưa xử lý; mở thẳng tới buổi hay yêu cầu đó.' },
    { id: 'F-51', name: 'Gửi SMS cho phụ huynh chưa cài app', module: 'thong-bao', src: ['CO-02'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'GĐ2. Khoảng 15 % phụ huynh lớn tuổi chưa dùng app: thông báo đi kèm SMS.' },

    // ===== Báo cáo =====
    { id: 'F-52', name: 'Xem báo cáo chuyên cần', module: 'bao-cao', src: ['UC-11', 'S-01', 'YC-13'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoảng thời gian, mặc định tháng này. Tỉ lệ đi học theo lớp và theo HLV, kèm số buổi vắng không phép.' },
    { id: 'F-53', name: 'Xem báo cáo doanh thu', module: 'bao-cao', src: ['UC-11', 'BR-QT-03', 'S-01'], roles: ['quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Tổng thu theo tháng, theo loại gói, theo hình thức thanh toán. Lễ tân không thấy.' },
    { id: 'F-54', name: 'Xuất báo cáo ra Excel', module: 'bao-cao', src: ['D3:117', 'S-01'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Xuất báo cáo đang xem ra file Excel để gửi kế toán; chỉ quản lý.' },

    // ===== Tài khoản, quản trị =====
    { id: 'F-55', name: 'Thêm, sửa tài khoản nhân viên', module: 'tai-khoan', src: ['UC-12', 'BR-QT-01', 'BR-QT-02', 'YC-14', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Họ tên, số điện thoại, vai (Quản lý, Lễ tân, HLV); với HLV chọn các lớp phụ trách. Hệ thống gửi mật khẩu tạm qua SMS.' },
    { id: 'F-56', name: 'Khoá, mở khoá tài khoản nhân viên', module: 'tai-khoan', src: ['UC-12', 'BR-QT-05', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhân viên nghỉ việc thì khoá, không xoá, giữ lịch sử. Tài khoản bị khoá do sai mật khẩu 5 lần thì quản lý mở khoá.' },
    { id: 'F-57', name: 'Tra cứu nhật ký thao tác', module: 'tai-khoan', src: ['BR-QT-04', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Khi có khiếu nại: lọc theo học viên, người làm, loại việc (sửa điểm danh, duyệt hoàn tiền, bảo lưu gói, xoá khỏi lớp); xem ai làm, lúc nào, trước và sau.' },
    { id: 'F-58', name: 'Đăng nhập web quản trị', module: 'tai-khoan', src: ['BR-QT-01', 'BR-QT-05'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Ba vai đăng nhập web; mỗi vai vào trang chủ của mình. Mật khẩu tối thiểu 8 ký tự; sai 5 lần liền thì khoá tài khoản.' },
    { id: 'F-59', name: 'Đổi mật khẩu', module: 'tai-khoan', src: ['UC-12'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Nhân viên nhận mật khẩu tạm qua SMS thì đổi sang mật khẩu riêng ở lần đăng nhập đầu, và đổi lại khi cần.' },
    { id: 'F-60', name: 'Đăng nhập app bằng số điện thoại', module: 'tai-khoan', src: ['NF-05', 'UC-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Số điện thoại đã đăng ký ở quầy và mã OTP, không mật khẩu.' },

    // ===== Tiến bộ (GĐ2) =====
    { id: 'F-61', name: 'Ghi nhận xét kỹ năng cuối cấp độ', module: 'tien-bo', src: ['S-04'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'GĐ2. HLV ghi nhận xét kỹ năng của từng bé cuối mỗi cấp độ; mẫu nhận xét chưa thống nhất.' },
    { id: 'F-62', name: 'Xem nhận xét tiến bộ của con', module: 'tien-bo', src: ['S-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'GĐ2. Phụ huynh xem nhận xét kỹ năng của HLV trên app.' },
  ],
  skip: [
    { src: 'D1:28-31', why: 'Tóm tắt số quy tắc, không có việc' },
    { src: 'D1:104-107', why: 'Phát hiện đã chuyển sang XD-01, XD-02; chức năng theo quyết định' },
    { src: 'D2:20-23', why: 'Tóm tắt số ca biên, không có việc' },
    { src: 'D3:21-30', why: 'Danh sách actor: thành mã vai trong roles' },
    { src: 'D3:31-79', why: 'Bảng tóm tắt use case; mỗi UC có chức năng trỏ tới đặc tả ở mục 5' },
    { src: 'D3:33-38', why: 'Bảng tóm tắt UC-01; đặc tả ở mục 5' },
    { src: 'D3:39-45', why: 'Bảng tóm tắt UC-03, UC-04; đặc tả ở mục 5' },
    { src: 'D3:46-53', why: 'Bảng tóm tắt UC-06 tới UC-08; đặc tả ở mục 5' },
    { src: 'D3:54-59', why: 'Bảng tóm tắt UC-05; đặc tả ở mục 5' },
    { src: 'D3:60-66', why: 'Bảng tóm tắt UC-02, UC-09; đặc tả ở mục 5' },
    { src: 'D3:67-72', why: 'Bảng tóm tắt UC-10; đặc tả ở mục 5' },
    { src: 'D3:73-79', why: 'Bảng tóm tắt UC-11, UC-12; đặc tả ở mục 5' },
    { src: 'D3:80-98', why: 'Ma trận actor × UC: vai chính, vai phụ đã ghi vào roles và spec' },
    { src: 'D4:17-20', why: 'Tóm tắt cách xếp ưu tiên, không có việc' },
    { src: 'D4:42-45', why: 'Phát hiện: học thử không có UC (đã có F-07, F-08), M-06 theo XD-02 (đã có F-21)' },
    { src: 'D6:29-35', why: 'Mục tiêu, không có việc' },
    { src: 'D6:36-44', why: 'Bề mặt và thiết bị: dùng cho bố cục, không có việc' },
    { src: 'D6:91-97', why: 'Ngoài phạm vi: bán đồ bơi, tính lương HLV' },
  ],
};
