// Bố cục (M2) · Sóng Xanh
window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'HLV', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'tai-khoan', name: 'Tài khoản', depends: [] },
    { id: 'lop', name: 'Lớp', depends: ['hoc-vien', 'tai-khoan'] },
    { id: 'lich', name: 'Lịch', depends: ['lop'] },
    { id: 'goi-hoc', name: 'Gói học', depends: ['hoc-vien', 'lich'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['lich'] },
    { id: 'hoc-thu', name: 'Học thử', depends: ['hoc-vien', 'lop'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
    { id: 'tien-bo', name: 'Tiến bộ', depends: ['hoc-vien', 'lop'] },
  ],
  screens: [
    // ----- Web: trang chủ theo vai -----
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'hoc-vien', roles: ['le-tan'],
      bands: [
        { name: 'Tìm học viên', items: ['F-01'] },
        { name: 'Việc nhanh', items: ['F-02', 'F-32', 'F-30'] },
        { name: 'Cần xử lý hôm nay', items: ['F-22', 'F-33', 'F-36'] },
      ] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'lich', roles: ['quan-ly'],
      bands: [
        { name: 'Cần chú ý', items: ['F-50', 'F-38'] },
        { name: 'Tháng này', items: ['F-52', 'F-53'] },
        { name: 'Việc nhanh', items: ['F-24', 'F-45'] },
      ] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [
        { name: 'Buổi đang dạy', items: ['F-26', 'F-08'] },
        { name: 'Các buổi hôm nay', items: ['F-17', 'F-27'] },
      ] },
    // ----- Web: lịch, buổi -----
    { id: 'lich', name: 'Lịch tuần', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Lưới làn × giờ'] },
    { id: 'buoi-hoc', name: 'Buổi học', surface: 'web', module: 'diem-danh', roles: ['le-tan', 'quan-ly'], parent: 'lich', pick: true, zones: ['Đầu buổi', 'Danh sách học viên'] },
    { id: 'yeu-cau-doi', name: 'Yêu cầu đổi lịch', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly'], zones: ['Lọc trạng thái', 'Danh sách yêu cầu'] },
    // ----- Web: học viên, lớp -----
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Gói học', 'Lịch học', 'Đóng tiền'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Lọc', 'Bảng lớp'] },
    { id: 'chi-tiet-lop', name: 'Chi tiết lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'lop', pick: true,
      zones: ['Đầu lớp'], tabs: ['Học viên', 'Danh sách chờ', 'Buổi học'] },
    // ----- Web: gói, tiền -----
    { id: 'goi-hoc', name: 'Gói học', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Lọc trạng thái'], tabs: ['Tất cả gói', 'Cần gia hạn'] },
    { id: 'thu-chi', name: 'Thu chi', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], tabs: ['Thu trong ngày', 'Hoàn tiền'] },
    // ----- Web: liên lạc, báo cáo, quản trị -----
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['le-tan', 'quan-ly'], zones: ['Khoảng thời gian'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], zones: ['Lọc', 'Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch'] },
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'tai-khoan', roles: ['le-tan', 'quan-ly', 'hlv'], entry: true, zones: ['Đăng nhập'] },
    // ----- App phụ huynh -----
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'tai-khoan', roles: ['phu-huynh'], entry: true, zones: ['Đăng nhập'] },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'lich', roles: ['phu-huynh'],
      bands: [
        { name: 'Con đang xem', items: ['F-06'] },
        { name: 'Buổi sắp tới', items: ['F-25', 'F-29', 'F-21'] },
        { name: 'Số buổi còn lại', items: ['F-41'] },
      ] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'], zones: ['Số buổi còn lại', 'Lịch sử đóng tiền', 'Nhận xét của HLV'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'tai-khoan', roles: ['phu-huynh'], zones: ['Con của tôi', 'Cài đặt thông báo'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['quay', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Gói và tiền', items: ['goi-hoc', 'thu-chi'] },
      { name: 'Phụ huynh', items: ['yeu-cau-doi', 'thong-bao'] },
      { name: 'Báo cáo', items: ['bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Gói và tiền', items: ['goi-hoc', 'thu-chi'] },
      { name: 'Phụ huynh', items: ['yeu-cau-doi', 'thong-bao'] },
      { name: 'Quản trị', items: ['bao-cao', 'nhan-vien', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    'F-01': [{ screen: 'quay', zone: 'Tìm học viên', tier: 1, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }],
    'F-02': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'trang' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'ngan-truot' },
    'F-05': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 4, mo: 'hop-thoai' },
    'F-06': { screen: 'app-lich', zone: 'Con đang xem', tier: 2, mo: 'tai-cho' },
    'F-07': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-08': { screen: 'buoi-day', zone: 'Buổi đang dạy', tier: 4, mo: 'tai-cho' },
    'F-09': { screen: 'lop', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-10': { screen: 'lop', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-11': [{ screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'trang' }, { screen: 'lich', zone: 'Lưới làn × giờ', tier: 4, mo: 'ngan-truot' }],
    'F-12': [{ screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' }, { screen: 'chi-tiet-lop', tab: 'Học viên', tier: 2, mo: 'ngan-truot' }],
    'F-13': { screen: 'chi-tiet-lop', tab: 'Danh sách chờ', tier: 2, mo: 'hop-thoai' },
    'F-14': { screen: 'chi-tiet-lop', tab: 'Danh sách chờ', tier: 4, mo: 'tai-cho' },
    'F-15': { screen: 'chi-tiet-lop', tab: 'Học viên', tier: 4, mo: 'hop-thoai' },
    'F-16': { screen: 'lich', zone: 'Lưới làn × giờ', tier: 1, mo: 'trang' },
    'F-17': { screen: 'buoi-day', zone: 'Các buổi hôm nay', tier: 2, mo: 'tai-cho' },
    'F-19': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'hop-thoai' },
    'F-20': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-21': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-22': { screen: 'yeu-cau-doi', zone: 'Danh sách yêu cầu', tier: 1, mo: 'ngan-truot' },
    'F-23': { screen: 'lich', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-24': { screen: 'lich', zone: 'Thanh công cụ', tier: 2, mo: 'hop-thoai' },
    'F-25': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-26': [{ screen: 'buoi-day', zone: 'Buổi đang dạy', tier: 1, mo: 'tai-cho' }, { screen: 'buoi-hoc', zone: 'Danh sách học viên', tier: 1, mo: 'tai-cho' }],
    'F-27': [{ screen: 'buoi-day', zone: 'Các buổi hôm nay', tier: 4, mo: 'tai-cho' }, { screen: 'buoi-hoc', zone: 'Danh sách học viên', tier: 4, mo: 'hop-thoai' }],
    'F-29': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-30': { screen: 'buoi-hoc', zone: 'Danh sách học viên', tier: 4, mo: 'hop-thoai' },
    'F-31': { screen: 'buoi-hoc', zone: 'Đầu buổi', tier: 2, mo: 'hop-thoai' },
    'F-32': [{ screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'ngan-truot' }, { screen: 'goi-hoc', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' }],
    'F-33': { screen: 'thu-chi', tab: 'Thu trong ngày', tier: 4, mo: 'tai-cho' },
    'F-34': { screen: 'goi-hoc', tab: 'Tất cả gói', tier: 1, mo: 'trang' },
    'F-35': { screen: 'goi-hoc', tab: 'Tất cả gói', tier: 4, mo: 'ngan-truot' },
    'F-36': { screen: 'goi-hoc', tab: 'Cần gia hạn', tier: 2, mo: 'tai-cho' },
    'F-37': { screen: 'thu-chi', tab: 'Hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-38': { screen: 'thu-chi', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-39': { screen: 'thu-chi', tab: 'Hoàn tiền', tier: 4, mo: 'tai-cho' },
    'F-40': { screen: 'cai-dat', tab: 'Bảng giá', tier: 2, mo: 'ngan-truot' },
    'F-41': [{ screen: 'app-goi', zone: 'Số buổi còn lại', tier: 1, mo: 'tai-cho' }, { screen: 'app-lich', zone: 'Số buổi còn lại', tier: 2, mo: 'tai-cho' }],
    'F-42': { screen: 'app-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-43': { screen: 'thu-chi', tab: 'Thu trong ngày', tier: 1, mo: 'trang' },
    'F-44': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 4, mo: 'tai-cho' },
    'F-45': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-46': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 2, mo: 'tai-cho' },
    'F-48': { screen: 'app-thong-bao', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-49': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 2, mo: 'tai-cho' },
    'F-50': { screen: 'tong-quan', zone: 'Cần chú ý', tier: 1, mo: 'tai-cho' },
    'F-51': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 3, mo: 'tai-cho' },
    'F-52': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'trang' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-53': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'trang' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-54': { screen: 'bao-cao', zone: 'Khoảng thời gian', tier: 3, mo: 'tai-cho' },
    'F-55': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-56': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-57': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 1, mo: 'trang' },
    'F-58': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-59': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 2, mo: 'hop-thoai' },
    'F-60': { screen: 'app-dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-61': { screen: 'chi-tiet-lop', tab: 'Học viên', tier: 4, mo: 'ngan-truot' },
    'F-62': { screen: 'app-goi', zone: 'Nhận xét của HLV', tier: 2, mo: 'tai-cho' },
  },
  shortcuts: [
    { from: 'quay', to: 'F-02', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-32', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-30', mo: 'hop-thoai' },
    { from: 'quay', to: 'F-22', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-33', mo: 'hop-thoai' },
    { from: 'quay', to: 'F-36', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-38', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-24', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-45', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-35', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới tới quầy cho con học', steps: ['F-01', 'F-02', 'F-32', 'F-12'] },
    { role: 'le-tan', name: 'Phụ huynh xin đổi buổi qua app', steps: ['F-22', 'F-20'] },
    { role: 'le-tan', name: 'Cuối ca', steps: ['F-33', 'F-43'] },
    { role: 'quan-ly', name: 'Mở lớp đầu đợt', steps: ['F-09', 'F-10', 'F-16'] },
    { role: 'quan-ly', name: 'Phụ huynh khiếu nại số buổi', steps: ['F-01', 'F-03', 'F-57', 'F-27'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số', steps: ['F-52', 'F-53', 'F-54'] },
    { role: 'hlv', name: 'Một buổi dạy ở thành bể', steps: ['F-17', 'F-26', 'F-27'] },
    { role: 'hlv', name: 'Buổi học thử', steps: ['F-26', 'F-08'] },
    { role: 'phu-huynh', name: 'Bé ốm, xin nghỉ', steps: ['F-06', 'F-25', 'F-29'] },
    { role: 'phu-huynh', name: 'Xin sang buổi khác', steps: ['F-25', 'F-21', 'F-48'] },
    { role: 'phu-huynh', name: 'Trước khi đóng tiền tiếp', steps: ['F-41', 'F-42'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một mẹ dẫn bé 5 tuổi tới quầy, muốn cho bé học bơi; nhà chưa có ai học ở trung tâm.', feature: 'F-02' },
    { role: 'le-tan', say: 'Anh Minh tới quầy đóng thêm 12 buổi cho con, bé đang học lớp Cơ bản.', feature: 'F-32' },
    { role: 'le-tan', say: 'Chị Lan gọi điện: bé Na sốt, chiều nay không tới bể được.', feature: 'F-30' },
    { role: 'le-tan', say: 'Sáng nay ba phụ huynh nhờ chuyển con sang hôm khác qua app, chưa ai được trả lời.', feature: 'F-22' },
    { role: 'le-tan', say: 'Mẹ bé Bin chuyển khoản hôm qua, giờ tiền đã vào tài khoản trung tâm.', feature: 'F-33' },
    { role: 'le-tan', say: 'Mẹ bé Tôm gọi hỏi lớp Cơ bản tối thứ Ba còn nhận thêm bé không.', feature: 'F-11' },
    { role: 'hlv', say: 'Lớp 17:30 vừa bắt đầu, các bé đã xuống nước; thầy cần ghi lại bé nào tới.', feature: 'F-26' },
    { role: 'quan-ly', say: '7 giờ sáng, thầy Hùng nhắn bị sốt, hôm nay không dạy được.', feature: 'F-24' },
    { role: 'phu-huynh', say: 'Bé Su ốm từ sáng, mẹ muốn cho trung tâm biết chiều nay bé không tới.', feature: 'F-29' },
    { role: 'phu-huynh', say: 'Bố muốn biết bao giờ thì phải đóng tiền tiếp cho con.', feature: 'F-41' },
  ],
};
