window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'hom-nay' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'lich-con' },
  ],
  modules: [
    { id: 'quan-tri', name: 'Tài khoản và nhật ký', depends: [] },
    { id: 'hoc-vien', name: 'Học viên và phụ huynh', depends: [] },
    { id: 'lop', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'lich', name: 'Lịch và buổi học', depends: ['lop', 'goi-hoc'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
  ],
  screens: [
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true },
    { id: 'dang-nhap-app', name: 'Đăng nhập', surface: 'app', module: 'quan-tri', roles: ['phu-huynh'], entry: true },

    { id: 'hom-nay', name: 'Hôm nay', surface: 'web', module: 'lich', roles: ['le-tan'],
      zones: ['Yêu cầu đổi lịch', 'Cần gọi gia hạn', 'Tìm học viên'],
      bands: [{ name: 'Cần xử lý hôm nay', items: ['F-22', 'F-44'] }, { name: 'Việc nhanh', items: ['F-01', 'F-35', 'F-12', 'F-02'] }] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      zones: ['Cần quyết định', 'Số liệu tháng'],
      bands: [{ name: 'Cần quyết định', items: ['F-47', 'F-27'] }, { name: 'Số liệu tháng', items: ['F-58', 'F-57'] }, { name: 'Việc nhanh', items: ['F-52', 'F-10'] }] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      zones: ['Buổi hôm nay', 'Buổi đã qua'],
      bands: [{ name: 'Buổi dạy hôm nay', items: ['F-19', 'F-31'] }, { name: 'Cần bổ sung', items: ['F-32', 'F-07'] }] },

    { id: 'lich', name: 'Lịch trung tâm', surface: 'web', module: 'lich', roles: ['quan-ly', 'le-tan'],
      zones: ['Chọn ngày', 'Lưới lịch', 'Ngăn chi tiết lớp'] },
    { id: 'diem-danh', name: 'Điểm danh và sửa điểm danh', surface: 'web', module: 'diem-danh', roles: ['quan-ly'], parent: 'lich', pick: true,
      zones: ['Danh sách học viên của buổi'] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Gói học', 'Buổi học'] },
    { id: 'lop', name: 'Lớp học', surface: 'web', module: 'lop', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Bảng lớp', 'Danh sách chờ'] },
    { id: 'mo-lop', name: 'Khoá học và mở lớp', surface: 'web', module: 'lop', roles: ['quan-ly'],
      zones: ['Khoá học', 'Lớp'] },
    { id: 'goi-hoc', name: 'Gói và thu tiền', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Thu trong ngày', 'Chờ xác nhận', 'Lịch sử thu'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Đề nghị hoàn tiền'] },
    { id: 'thong-bao', name: 'Thông báo cho phụ huynh', surface: 'web', module: 'thong-bao', roles: ['quan-ly', 'le-tan'],
      zones: ['Soạn thông báo'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['quan-ly', 'le-tan'],
      zones: ['Chọn khoảng thời gian'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      zones: ['Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      zones: ['Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'goi-hoc', roles: ['quan-ly'],
      tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch'] },

    { id: 'lich-con', name: 'Lịch học', surface: 'app', module: 'lich', roles: ['phu-huynh'],
      zones: ['Chọn con', 'Buổi sắp tới'],
      bands: [{ name: 'Buổi sắp tới', items: ['F-30', 'F-34'] }, { name: 'Việc nhanh', items: ['F-23', 'F-08'] }] },
    { id: 'goi-con', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'],
      zones: ['Gói đang dùng', 'Lịch sử đóng tiền', 'Tiến bộ của con'] },
    { id: 'thong-bao-app', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'],
      zones: ['Danh sách thông báo'] },
  ],
  nav: [
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Gói và tiền', items: ['goi-hoc', 'hoan-tien', 'bao-cao'] },
      { name: 'Phụ huynh', items: ['thong-bao'] },
      { name: 'Quản trị', items: ['mo-lop', 'nhan-vien', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['le-tan'], groups: [{ name: 'Hằng ngày', items: ['hom-nay', 'lich', 'hoc-vien', 'lop'] }, { name: 'Gói, tiền và phụ huynh', items: ['goi-hoc', 'hoan-tien', 'thong-bao', 'bao-cao'] }] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['lich-con', 'goi-con', 'thong-bao-app'] }] },
  ],
  place: {
    'F-01': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 1, mo: 'ngan-truot' },
    'F-02': [{ screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' }, { screen: 'hom-nay', zone: 'Tìm học viên', tier: 2, mo: 'tai-cho' }],
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'tai-cho' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-06': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 2, mo: 'ngan-truot' },
    'F-07': { screen: 'buoi-day', zone: 'Buổi hôm nay', tier: 2, mo: 'hop-thoai' },
    'F-08': { screen: 'lich-con', zone: 'Chọn con', tier: 2, mo: 'tai-cho' },
    'F-09': { screen: 'mo-lop', zone: 'Khoá học', tier: 2, mo: 'hop-thoai' },
    'F-10': { screen: 'mo-lop', zone: 'Lớp', tier: 1, mo: 'ngan-truot' },
    'F-11': { screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'tai-cho' },
    'F-12': { screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'ngan-truot' },
    'F-13': { screen: 'lop', zone: 'Bảng lớp', tier: 3, mo: 'hop-thoai' },
    'F-14': { screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'hop-thoai' },
    'F-15': { screen: 'lop', zone: 'Danh sách chờ', tier: 2, mo: 'tai-cho' },
    'F-16': { screen: 'lop', zone: 'Bảng lớp', tier: 3, mo: 'hop-thoai' },
    'F-17': { screen: 'buoi-day', zone: 'Buổi hôm nay', tier: 4, mo: 'hop-thoai' },
    'F-18': { screen: 'lich', zone: 'Lưới lịch', tier: 1, mo: 'tai-cho' },
    'F-19': [{ screen: 'lich', zone: 'Lưới lịch', tier: 2, mo: 'tai-cho' }, { screen: 'buoi-day', zone: 'Buổi hôm nay', tier: 2, mo: 'tai-cho' }],
    'F-20': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 2, mo: 'ngan-truot' },
    'F-21': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 2, mo: 'ngan-truot' },
    'F-22': { screen: 'hom-nay', zone: 'Yêu cầu đổi lịch', tier: 1, mo: 'tai-cho' },
    'F-23': { screen: 'lich-con', zone: 'Buổi sắp tới', tier: 2, mo: 'sheet' },
    'F-25': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 3, mo: 'hop-thoai' },
    'F-26': { screen: 'lich', zone: 'Lưới lịch', tier: 3, mo: 'hop-thoai' },
    'F-27': { screen: 'tong-quan', zone: 'Cần quyết định', tier: 2, mo: 'hop-thoai' },
    'F-28': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 2, mo: 'ngan-truot' },
    'F-30': { screen: 'lich-con', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-31': [{ screen: 'buoi-day', zone: 'Buổi hôm nay', tier: 1, mo: 'ngan-truot' }, { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 1, mo: 'trang' }],
    'F-32': [{ screen: 'buoi-day', zone: 'Buổi đã qua', tier: 2, mo: 'ngan-truot' }, { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 2, mo: 'tai-cho' }],
    'F-34': { screen: 'lich-con', zone: 'Buổi sắp tới', tier: 2, mo: 'sheet' },
    'F-35': { screen: 'goi-hoc', zone: 'Thu trong ngày', tier: 1, mo: 'ngan-truot' },
    'F-36': { screen: 'goi-hoc', zone: 'Chờ xác nhận', tier: 2, mo: 'tai-cho' },
    'F-37': { screen: 'goi-hoc', zone: 'Lịch sử thu', tier: 2, mo: 'tai-cho' },
    'F-38': { screen: 'ho-so', tab: 'Gói học', tier: 2, mo: 'tai-cho' },
    'F-39': { screen: 'ho-so', tab: 'Gói học', tier: 2, mo: 'hop-thoai' },
    'F-40': { screen: 'goi-con', zone: 'Gói đang dùng', tier: 1, mo: 'tai-cho' },
    'F-41': { screen: 'goi-con', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-42': { screen: 'goi-hoc', zone: 'Thu trong ngày', tier: 2, mo: 'tai-cho' },
    'F-43': { screen: 'cai-dat', tab: 'Bảng giá', tier: 3, mo: 'tai-cho' },
    'F-44': { screen: 'hom-nay', zone: 'Cần gọi gia hạn', tier: 2, mo: 'tai-cho' },
    'F-45': { screen: 'hom-nay', zone: 'Cần gọi gia hạn', tier: 2, mo: 'hop-thoai' },
    'F-46': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-47': [{ screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 1, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Cần quyết định', tier: 1, mo: 'tai-cho' }],
    'F-48': { screen: 'hoan-tien', zone: 'Đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-49': { screen: 'goi-hoc', zone: 'Thu trong ngày', tier: 4, mo: 'hop-thoai' },
    'F-50': { screen: 'ho-so', tab: 'Buổi học', tier: 4, mo: 'ngan-truot' },
    'F-51': { screen: 'goi-con', zone: 'Tiến bộ của con', tier: 2, mo: 'tai-cho' },
    'F-52': { screen: 'thong-bao', zone: 'Soạn thông báo', tier: 1, mo: 'trang' },
    'F-53': { screen: 'thong-bao', zone: 'Soạn thông báo', tier: 2, mo: 'tai-cho' },
    'F-54': { screen: 'thong-bao-app', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-55': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 3, mo: 'ngan-truot' },
    'F-57': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Số liệu tháng', tier: 2, mo: 'tai-cho' }],
    'F-58': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Số liệu tháng', tier: 2, mo: 'tai-cho' }],
    'F-59': { screen: 'bao-cao', zone: 'Chọn khoảng thời gian', tier: 3, mo: 'tai-cho' },
    'F-60': { screen: 'dang-nhap', tier: 1, mo: 'trang' },
    'F-61': { screen: 'dang-nhap-app', tier: 1, mo: 'trang' },
    'F-62': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 1, mo: 'ngan-truot' },
    'F-63': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 2, mo: 'ngan-truot' },
    'F-64': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-65': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-66': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 1, mo: 'trang' },
    'F-67': { screen: 'dang-nhap', tier: 2, mo: 'hop-thoai' },
  },
  shortcuts: [
    { from: 'hom-nay', to: 'F-01', mo: 'ngan-truot' },
    { from: 'hom-nay', to: 'F-35', mo: 'ngan-truot' },
    { from: 'hom-nay', to: 'F-12', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-52', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-10', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-35', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-37', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-12', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-20', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Phụ huynh mới đến đăng ký cho con', steps: ['F-02', 'F-01', 'F-35', 'F-12'] },
    { role: 'le-tan', name: 'Đầu ca gọi mời gia hạn', steps: ['F-44', 'F-45', 'F-35'] },
    { role: 'le-tan', name: 'Xử lý yêu cầu đổi lịch từ app', steps: ['F-22', 'F-20'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số liệu', steps: ['F-58', 'F-57', 'F-59'] },
    { role: 'quan-ly', name: 'Bể có sự cố', steps: ['F-26', 'F-52'] },
    { role: 'hlv', name: 'Dạy một buổi', steps: ['F-19', 'F-31', 'F-32'] },
    { role: 'phu-huynh', name: 'Con ốm, xin nghỉ buổi chiều', steps: ['F-08', 'F-30', 'F-34'] },
    { role: 'phu-huynh', name: 'Xin dời buổi học', steps: ['F-30', 'F-23', 'F-54'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một phụ huynh dắt bé đến quầy, muốn cho bé học bơi từ tuần sau, bé chưa có hồ sơ.', feature: 'F-01' },
    { role: 'le-tan', say: 'Phụ huynh đưa tiền mặt, muốn mua tiếp 12 buổi cho bé đang học.', feature: 'F-35' },
    { role: 'le-tan', say: 'Lớp Cơ bản tối thứ Ba vừa có một bé nghỉ, cần biết ai đang đợi lớp đó để gọi.', feature: 'F-15' },
    { role: 'le-tan', say: 'Đầu ca, cần biết hôm nay gọi những bé nào sắp học hết số buổi.', feature: 'F-44' },
    { role: 'hlv', say: 'Buổi 17:30 bắt đầu, đang đứng ở thành bể, cần ghi bé nào đến lớp.', feature: 'F-31' },
    { role: 'hlv', say: 'Sáng nay nhớ ra hôm qua ghi nhầm một bé vắng, cần sửa lại.', feature: 'F-32' },
    { role: 'quan-ly', say: 'Bơm lọc hỏng lúc 15:00, chiều nay không bé nào xuống bể được.', feature: 'F-26' },
    { role: 'quan-ly', say: 'Chủ trung tâm hỏi tháng này thu được bao nhiêu.', feature: 'F-58' },
    { role: 'phu-huynh', say: 'Bé sốt sáng nay, chiều nay không đến lớp được.', feature: 'F-34' },
    { role: 'phu-huynh', say: 'Muốn biết bé còn mấy buổi và tới khi nào thì hết hạn.', feature: 'F-40' },
  ],
};
