window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'day-hom-nay' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'quan-tri', name: 'Quản trị', depends: [] },
    { id: 'lop', name: 'Lớp', depends: ['hoc-vien', 'quan-tri'] },
    { id: 'lich', name: 'Lịch', depends: ['lop'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'hoc-thu', name: 'Học thử', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['lop'] },
    { id: 'app-phu-huynh', name: 'App phụ huynh', depends: ['lich', 'goi-hoc', 'diem-danh', 'thong-bao'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
    { id: 'danh-gia', name: 'Đánh giá tiến bộ', depends: ['lop', 'app-phu-huynh'] },
  ],
  screens: [
    // Web quản trị
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true },
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'lich', roles: ['le-tan'],
      bands: [
        { name: 'Tìm học viên', items: ['F-01', 'F-02'] },
        { name: 'Cần xử lý hôm nay', items: ['F-20', 'F-29', 'F-33'] },
        { name: 'Phụ huynh gọi tới', items: ['F-27', 'F-19'] },
      ] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'lich', roles: ['quan-ly'],
      bands: [
        { name: 'Cần quản lý xử lý', items: ['F-67', 'F-35'] },
        { name: 'HLV nghỉ hôm nay', items: ['F-22'] },
        { name: 'Tháng này', items: ['F-57', 'F-58'] },
      ] },
    { id: 'day-hom-nay', name: 'Hôm nay', surface: 'web', module: 'lich', roles: ['hlv'],
      bands: [
        { name: 'Buổi dạy hôm nay', items: ['F-16'] },
        { name: 'Bé học thử chờ ghi cấp độ', items: ['F-41'] },
      ] },
    { id: 'lich-tuan', name: 'Lịch', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Lưới làn × giờ', 'Ngăn lớp'] },
    { id: 'lich-day', name: 'Lịch dạy', surface: 'web', module: 'lich', roles: ['hlv'], zones: ['Tuần này'] },
    { id: 'diem-danh', name: 'Điểm danh', surface: 'web', module: 'diem-danh', roles: ['hlv', 'quan-ly'], parent: 'day-hom-nay', pick: true, zones: ['Đầu buổi', 'Danh sách học viên'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'lop', pick: true, zones: ['Đầu lớp', 'Học viên đang học', 'Hàng chờ'] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Tổng quan', 'Buổi học', 'Gói và thanh toán'] },
    { id: 'hoc-thu', name: 'Học thử', surface: 'web', module: 'hoc-thu', roles: ['le-tan'], zones: ['Thanh công cụ', 'Khách học thử'] },
    { id: 'thu-tien', name: 'Thu tiền', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Thu hôm nay', 'Chờ xác nhận chuyển khoản', 'Đối chiếu cuối ca'] },
    { id: 'goi-hoc', name: 'Gói học', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Lọc theo trạng thái', 'Bảng gói'], tabs: ['Gói học', 'Đề nghị hoàn tiền'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch', 'Nhật ký thao tác'] },
    // App phụ huynh
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], entry: true },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'],
      bands: [
        { name: 'Con đang xem', items: ['F-49'] },
        { name: 'Buổi sắp tới', items: ['F-50', 'F-53', 'F-54'] },
      ] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], tabs: ['Gói đang dùng', 'Lịch sử đóng tiền', 'Nhận xét của HLV'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Cài đặt thông báo'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['quay', 'lich-tuan', 'lop', 'hoc-vien', 'hoc-thu'] },
      { name: 'Gói và tiền', items: ['thu-tien', 'goi-hoc'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich-tuan', 'lop', 'hoc-vien'] },
      { name: 'Gói và tiền', items: ['thu-tien', 'goi-hoc'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['day-hom-nay', 'lich-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    // Học viên
    'F-01': [{ screen: 'quay', zone: 'Tìm học viên', tier: 1, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }],
    'F-02': { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 2, mo: 'ngan-truot' },
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'tai-cho' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    // Lớp
    'F-06': { screen: 'lop', zone: 'Thanh công cụ', tier: 3, mo: 'ngan-truot' },
    'F-07': { screen: 'lop', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-08': { screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'tai-cho' },
    'F-09': { screen: 'lop-chi-tiet', zone: 'Đầu lớp', tier: 1, mo: 'ngan-truot' },
    'F-10': { screen: 'lop-chi-tiet', zone: 'Hàng chờ', tier: 2, mo: 'hop-thoai' },
    'F-11': { screen: 'lop-chi-tiet', zone: 'Hàng chờ', tier: 4, mo: 'tai-cho' },
    'F-12': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'ngan-truot' },
    'F-13': { screen: 'lop-chi-tiet', zone: 'Học viên đang học', tier: 4, mo: 'hop-thoai' },
    'F-14': { screen: 'lop-chi-tiet', zone: 'Học viên đang học', tier: 4, mo: 'hop-thoai' },
    // Lịch
    'F-15': { screen: 'lich-tuan', zone: 'Lưới làn × giờ', tier: 1, mo: 'tai-cho' },
    'F-16': [{ screen: 'day-hom-nay', zone: 'Buổi dạy hôm nay', tier: 1, mo: 'tai-cho' }, { screen: 'lich-day', zone: 'Tuần này', tier: 1, mo: 'tai-cho' }, { screen: 'lich-tuan', zone: 'Thanh công cụ', tier: 2, mo: 'tai-cho' }],
    'F-18': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'hop-thoai' },
    'F-19': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-20': { screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' },
    'F-21': { screen: 'lich-tuan', zone: 'Thanh công cụ', tier: 2, mo: 'hop-thoai' },
    'F-22': { screen: 'lich-tuan', zone: 'Ngăn lớp', tier: 4, mo: 'ngan-truot' },
    'F-23': { screen: 'lich-tuan', zone: 'Ngăn lớp', tier: 4, mo: 'ngan-truot' },
    'F-67': { screen: 'tong-quan', zone: 'Cần quản lý xử lý', tier: 1, mo: 'tai-cho' },
    // Điểm danh
    'F-24': { screen: 'diem-danh', zone: 'Danh sách học viên', tier: 1, mo: 'trang' },
    'F-25': { screen: 'diem-danh', zone: 'Đầu buổi', tier: 2, mo: 'tai-cho' },
    'F-27': { screen: 'quay', zone: 'Phụ huynh gọi tới', tier: 2, mo: 'hop-thoai' },
    // Gói học và thu tiền
    'F-28': { screen: 'thu-tien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-29': [{ screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'tai-cho' }, { screen: 'thu-tien', zone: 'Chờ xác nhận chuyển khoản', tier: 2, mo: 'tai-cho' }],
    'F-30': { screen: 'goi-hoc', zone: 'Bảng gói', tier: 1, mo: 'tai-cho' },
    'F-31': { screen: 'goi-hoc', zone: 'Bảng gói', tier: 4, mo: 'hop-thoai' },
    'F-33': { screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'tai-cho' },
    'F-34': { screen: 'goi-hoc', zone: 'Bảng gói', tier: 4, mo: 'hop-thoai' },
    'F-35': { screen: 'goi-hoc', tab: 'Đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-36': { screen: 'goi-hoc', tab: 'Đề nghị hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-37': { screen: 'cai-dat', tab: 'Bảng giá', tier: 2, mo: 'tai-cho' },
    'F-38': { screen: 'thu-tien', zone: 'Đối chiếu cuối ca', tier: 2, mo: 'tai-cho' },
    'F-39': { screen: 'thu-tien', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    // Học thử
    'F-40': { screen: 'hoc-thu', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-41': { screen: 'day-hom-nay', zone: 'Bé học thử chờ ghi cấp độ', tier: 2, mo: 'hop-thoai' },
    'F-42': { screen: 'hoc-thu', zone: 'Khách học thử', tier: 2, mo: 'tai-cho' },
    // Thông báo
    'F-44': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-46': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 2, mo: 'tai-cho' },
    // App phụ huynh
    'F-48': { screen: 'app-dang-nhap', tier: 1, mo: 'trang' },
    'F-49': { screen: 'app-lich', zone: 'Con đang xem', tier: 2, mo: 'tai-cho' },
    'F-50': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-51': { screen: 'app-goi', tab: 'Gói đang dùng', tier: 1, mo: 'tai-cho' },
    'F-52': { screen: 'app-goi', tab: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-53': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-54': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-55': { screen: 'app-thong-bao', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-56': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 2, mo: 'tai-cho' },
    // Báo cáo
    'F-57': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-58': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-59': { screen: 'bao-cao', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    // Quản trị
    'F-60': { screen: 'dang-nhap', tier: 1, mo: 'trang' },
    'F-61': [{ screen: 'quay', tier: 3, mo: 'hop-thoai' }, { screen: 'tong-quan', tier: 3, mo: 'hop-thoai' }, { screen: 'day-hom-nay', tier: 3, mo: 'hop-thoai' }],
    'F-62': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-63': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'ngan-truot' },
    'F-64': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-65': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-66': { screen: 'cai-dat', tab: 'Nhật ký thao tác', tier: 2, mo: 'tai-cho' },
    // Đánh giá tiến bộ (giai đoạn sau)
    'F-68': { screen: 'lop-chi-tiet', zone: 'Học viên đang học', tier: 4, mo: 'ngan-truot' },
    'F-69': { screen: 'app-goi', tab: 'Nhận xét của HLV', tier: 2, mo: 'tai-cho' },
  },
  shortcuts: [
    { from: 'quay', to: 'F-02', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-19', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-28', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-28', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-09', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-31', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-27', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-23', mo: 'ngan-truot' },
    { from: 'hoc-thu', to: 'F-28', mo: 'ngan-truot' },
    { from: 'lich-tuan', to: 'F-09', mo: 'ngan-truot' },
    { from: 'lich-tuan', to: 'F-20', mo: 'ngan-truot' },
    { from: 'lich-tuan', to: 'F-25', mo: 'ngan-truot' },
    { from: 'lich-tuan', to: 'F-24', mo: 'trang', ve: 'Lưu điểm danh xong thì về Lịch đúng tuần và ô lớp đang chọn, báo đã lưu; có nút Quay lại giữ nguyên tuần đang xem' },
    { from: 'tong-quan', to: 'F-35', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-22', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Phụ huynh mới đưa con tới đăng ký học', steps: ['F-01', 'F-02', 'F-28', 'F-09'] },
    { role: 'le-tan', name: 'Phụ huynh gọi xin nghỉ hay xin đổi buổi', steps: ['F-01', 'F-27', 'F-19', 'F-20'] },
    { role: 'le-tan', name: 'Bể có sự cố giữa buổi chiều', steps: ['F-15', 'F-21'] },
    { role: 'quan-ly', name: 'Đầu đợt mở lớp mới', steps: ['F-06', 'F-07', 'F-15'] },
    { role: 'quan-ly', name: 'Buổi sáng xem việc đang chờ', steps: ['F-67', 'F-22', 'F-35'] },
    { role: 'hlv', name: 'Dạy một buổi ở thành bể', steps: ['F-16', 'F-24', 'F-25'] },
    { role: 'hlv', name: 'Sau buổi học thử', steps: ['F-16', 'F-41'] },
    { role: 'phu-huynh', name: 'Con ốm, báo nghỉ buổi chiều', steps: ['F-49', 'F-50', 'F-53'] },
    { role: 'phu-huynh', name: 'Xin chuyển sang buổi khác', steps: ['F-50', 'F-54'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một phụ huynh mới tới quầy muốn cho bé 5 tuổi học bơi; bé chưa có hồ sơ ở trung tâm.', feature: 'F-02' },
    { role: 'le-tan', say: 'Mẹ bé Minh Anh chuyển khoản tiền gói 12 buổi từ sáng, ngân hàng vừa báo tiền đã về.', feature: 'F-29' },
    { role: 'le-tan', say: 'Một phụ huynh gọi điện: bé sốt, chiều nay không đi học được.', feature: 'F-27' },
    { role: 'le-tan', say: 'Có ba phụ huynh nhắn qua app xin chuyển buổi học tuần này sang ngày khác.', feature: 'F-20' },
    { role: 'le-tan', say: 'Bé Gia Bảo vừa mua gói, cần cho bé vào một lớp Cơ bản còn chỗ chiều thứ Ba.', feature: 'F-09' },
    { role: 'le-tan', say: 'Hết ca chiều, cần khớp tiền mặt trong két với số tiền đã thu trong ca.', feature: 'F-38' },
    { role: 'hlv', say: 'Lớp 17:30 vừa xuống nước, cần ghi bé nào có mặt, bé nào vắng.', feature: 'F-24' },
    { role: 'quan-ly', say: 'Sáng nay HLV Tuấn nhắn bị ốm, các lớp của anh ấy hôm nay cần người đứng thay.', feature: 'F-22' },
    { role: 'phu-huynh', say: 'Bé ốm từ sáng, muốn cho trung tâm biết chiều nay bé ở nhà.', feature: 'F-53' },
    { role: 'phu-huynh', say: 'Định mua gói tiếp cho con, muốn biết gói đang học còn dùng được bao lâu nữa.', feature: 'F-51' },
  ],
};
