// Kiểm kê chức năng (M1) — Sóng Xanh. Khuôn: sketch-to-map/templates/features.js.
// Kiểm: node <skills>/sketch-to-map/scripts/map.mjs check <thư-mục-prototype>.
window.FEATURES = {
  project: 'Sóng Xanh',
  features: [
    // ===== Học viên, phụ huynh =====
    { id: 'F-01', name: 'Tìm học viên', module: 'hoc-vien', src: ['UC-01', 'YC-01', 'M-01', 'D3:151', 'BR-QT-02'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Gõ tên, mã SX-0001 hay số điện thoại phụ huynh, có kết quả từ ký tự thứ ba; lọc học thử, đang học, ngừng học. HLV chỉ thấy học viên các lớp mình phụ trách.' },
    { id: 'F-02', name: 'Xem hồ sơ học viên', module: 'hoc-vien', src: ['M-01', 'D3:105', 'D3:148-151', 'D3:180', 'BR-QT-02'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Thông tin bé, phụ huynh và các con, ghi chú sức khoẻ, gói học, các buổi đã học, các lần đóng tiền và biên lai. HLV chỉ xem học viên lớp mình.', notes: 'câu hỏi mở OQ-03 (D2:45): HLV có được xem số điện thoại phụ huynh của lớp mình không' },
    { id: 'F-03', name: 'Đăng ký học viên mới', module: 'hoc-vien', src: ['UC-01', 'YC-01', 'M-01', 'BR-HV-01', 'BR-HV-02', 'BR-HV-04'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Tìm phụ huynh theo số điện thoại: có rồi thì gắn bé vào phụ huynh đó, chưa có thì tạo. Nhập họ tên, ngày sinh, giới tính, ghi chú sức khoẻ; hệ thống sinh mã; xong thì sang Bán gói hay dừng.', notes: 'mâu thuẫn: D3:146 (dưới 6 tuổi thiếu ghi chú sức khoẻ thì không cho lưu hồ sơ) với D1:39 (chỉ bắt buộc trước khi xếp lớp)' },
    { id: 'F-04', name: 'Sửa hồ sơ học viên và phụ huynh', module: 'hoc-vien', src: ['D3:106', 'YC-01', 'BR-HV-02'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sửa thông tin bé, ghi chú sức khoẻ, thông tin phụ huynh; số điện thoại phụ huynh vẫn là duy nhất, mã học viên không đổi.' },
    { id: 'F-05', name: 'Cho học viên ngừng học', module: 'hoc-vien', src: ['BR-HV-05', 'A-08'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.ngung_hoc'], spec: 'Chuyển hồ sơ sang ngừng học, không xoá, giữ lịch sử học và đóng tiền.', notes: 'câu hỏi mở OQ-01: hoàn tiền khi phụ huynh xin nghỉ hẳn chưa có chính sách (A-08); tạm thời lễ tân ghi chú hồ sơ và báo quản lý' },
    { id: 'F-06', name: 'Chọn con đang xem', module: 'hoc-vien', src: ['BR-HV-03', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhiều con chọn một bé; lịch, gói, thông báo hiện theo bé đó, không trộn lịch các con.' },

    // ===== Học thử =====
    { id: 'F-07', name: 'Đặt buổi học thử', module: 'hoc-thu', src: ['S-03', 'YC-05', 'BR-LH-06'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.hoc_thu'], spec: 'Tạo hồ sơ học thử, chọn một buổi miễn phí ở lớp còn chỗ, đúng độ tuổi; mỗi bé một lần.' },
    { id: 'F-08', name: 'Ghi cấp độ gợi ý sau buổi học thử', module: 'hoc-thu', src: ['BR-LH-06', 'D7:33'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sau buổi học thử, HLV chọn cấp độ gợi ý: Làm quen nước, Cơ bản, Nâng cao; lễ tân dùng khi bán gói và xếp lớp.' },
    { id: 'F-09', name: 'Theo dõi bé học thử chưa mua gói', module: 'hoc-thu', src: ['BR-LH-06'], roles: ['le-tan'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Danh sách bé đã học thử mà chưa mua gói, cấp độ gợi ý, ngày hết hạn giữ hồ sơ 60 ngày; lễ tân gọi mời mua gói.' },
    { id: 'F-10', name: 'Xoá hồ sơ học thử quá 60 ngày', module: 'hoc-thu', src: ['BR-LH-06'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Hệ thống tự xoá hồ sơ học thử không mua gói sau 60 ngày.' },

    // ===== Khoá học, lớp =====
    { id: 'F-11', name: 'Tạo khoá học', module: 'lop', src: ['UC-03', 'YC-02', 'M-02', 'BR-LH-01', 'BR-LH-05', 'XD-03'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tên, cấp độ, số buổi một tuần, sĩ số tối đa: Làm quen nước 6 bé (theo XD-03), các cấp khác 10 bé.' },
    { id: 'F-12', name: 'Mở lớp', module: 'lop', src: ['UC-03', 'YC-02', 'M-02', 'BR-LH-02', 'BR-LI-01'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoá, HLV chính, các ngày trong tuần, giờ bắt đầu, bể và làn; trùng HLV hay trùng làn thì chỉ ra lớp trùng để đổi giờ hay làn; lưu xong hệ thống sinh buổi.' },
    { id: 'F-13', name: 'Xem danh sách lớp và chỗ trống', module: 'lop', src: ['UC-04', 'YC-03', 'M-02', 'BR-QT-02'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Lọc theo cấp độ, ngày, giờ; mỗi lớp hiện HLV, làn, sĩ số, số chỗ trống và danh sách học viên. HLV chỉ thấy lớp mình phụ trách.' },
    { id: 'F-14', name: 'Xếp học viên vào lớp', module: 'lop', src: ['UC-04', 'YC-03', 'M-02', 'BR-LH-03', 'A-01', 'A-06'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc'], spec: 'Chọn lớp còn chỗ đúng cấp độ (xuống một bậc khi quản lý cho phép); hệ thống sinh buổi theo gói. Chỗ cuối vừa bị lấy thì gợi ý danh sách chờ; anh chị em trùng giờ thì cảnh báo, vẫn lưu được.' },
    { id: 'F-15', name: 'Đưa học viên vào danh sách chờ', module: 'lop', src: ['BR-LH-04', 'M-02', 'A-01'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.cho_cho'], spec: 'Lớp đủ sĩ số thì ghi bé vào danh sách chờ của lớp, theo thứ tự đăng ký.' },
    { id: 'F-16', name: 'Gọi phụ huynh trong danh sách chờ', module: 'lop', src: ['BR-LH-04', 'M-02'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop'], spec: 'Lớp có chỗ trống thì lễ tân thấy danh sách chờ theo thứ tự đăng ký, gọi người đăng ký trước, rồi xếp vào lớp.' },
    { id: 'F-17', name: 'Cho học viên rời lớp', module: 'lop', src: ['BR-QT-04'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.da_roi'], spec: 'Xoá bé khỏi lớp, giữ lịch sử; ghi nhật ký ai làm, lúc nào, trước và sau.' },
    { id: 'F-18', name: 'Đề xuất cho học viên lên cấp độ', module: 'lop', src: ['A-07', 'D3:320'], roles: ['hlv'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'HLV đánh dấu bé đủ sức lên cấp cao hơn; lễ tân thấy đề xuất và chuyển lớp, giữ nguyên số buổi còn lại.', notes: 'câu hỏi mở OQ-02: lên cấp giữa chừng có thu chênh lệch giá không' },

    // ===== Lịch, buổi học =====
    { id: 'F-19', name: 'Xem lịch tuần toàn trung tâm', module: 'lich', src: ['YC-04', 'M-03', 'D3:109'], roles: ['quan-ly', 'le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi'], spec: 'Lưới làn × giờ theo ngày và theo tuần: lớp nào, làn nào, HLV nào, còn bao nhiêu chỗ; bấm ô lớp mở danh sách học viên ở ngăn bên phải.' },
    { id: 'F-20', name: 'Xem lịch dạy', module: 'lich', src: ['D3:110', 'D3:241', 'UC-03', 'BR-QT-02'], roles: ['hlv', 'quan-ly', 'le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Buổi dạy hôm nay và trong tuần của một HLV, gồm buổi dạy thay; HLV chỉ thấy lớp mình, quản lý và lễ tân chọn HLV để xem.' },
    { id: 'F-21', name: 'Sinh buổi học tự động', module: 'lich', src: ['BR-LI-01', 'BR-LI-04', 'M-03'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi.du_kien'], spec: 'Sinh buổi theo khung giờ lớp từ ngày khai giảng tới hết đợt; ngày nghỉ lễ không sinh buổi, buổi rơi vào ngày lễ dời sang tuần sau.' },
    { id: 'F-22', name: 'Cập nhật ngày nghỉ lễ', module: 'lich', src: ['BR-LI-04', 'D7:78-81'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Thêm, sửa, xoá ngày nghỉ lễ của trung tâm; buổi rơi vào ngày đó dời sang tuần sau.', notes: 'vai Quản lý là suy ra: tài liệu không nói ai sửa danh sách nghỉ lễ' },
    { id: 'F-23', name: 'Huỷ buổi do trung tâm', module: 'lich', src: ['A-02', 'A-03', 'XD-04', 'BR-TT-07', 'BR-TB-03', 'YC-14'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_buoi.huy_do_trung_tam'], spec: 'Chọn một buổi hay cả khoảng giờ (bể sự cố) để huỷ một lần, chọn lý do; mỗi buổi được cộng bù một buổi, phụ huynh nhận thông báo khẩn, quản lý được báo ngay. Theo XD-04: lễ tân huỷ.' },
    { id: 'F-24', name: 'Phân công HLV dạy thay', module: 'lich', src: ['A-02', 'D7:94'], roles: ['quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'HLV báo nghỉ trong ngày: chọn HLV khác dạy các buổi trong ngày của người đó, lớp vẫn thuộc HLV cũ; phụ huynh nhận tên HLV dạy thay. Không có người thay thì huỷ buổi.' },
    { id: 'F-25', name: 'Xem lịch học của con', module: 'lich', src: ['UC-06', 'YC-11', 'M-06'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'Màn đầu của app: buổi sắp tới, gần nhất ở trên; buổi đã học kèm có mặt hay vắng; chưa có gói thì hiện số điện thoại quầy và giờ làm việc.' },

    // ===== Đổi lịch =====
    { id: 'F-26', name: 'Đổi một buổi học', module: 'doi-lich', src: ['UC-08', 'M-03', 'BR-LI-02'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Từ hồ sơ học viên chọn Đổi lịch, một buổi; gợi ý lớp cùng cấp độ còn chỗ, lớp cùng HLV lên trước; HLV hai lớp thấy thay đổi.' },
    { id: 'F-27', name: 'Chuyển lớp cố định', module: 'doi-lich', src: ['UC-08', 'M-03', 'BR-LI-02', 'A-07'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc'], spec: 'Chuyển hẳn sang lớp cùng cấp độ còn chỗ, giữ nguyên số buổi còn lại; lên cấp theo đề xuất của HLV cũng làm ở đây.', notes: 'câu hỏi mở OQ-02 (lên cấp có thu chênh lệch không)' },
    { id: 'F-28', name: 'Xếp buổi học bù', module: 'doi-lich', src: ['D7:99-105', 'D7:112', 'BR-DD-03'], roles: ['le-tan'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_diem_danh.da_hoc_bu'], spec: 'Bé vắng có phép được xếp một buổi bù ở lớp cùng cấp độ; học xong buổi bù thì buổi vắng thành đã học bù.', notes: 'chỉ có ở schema; ai xếp và mỗi gói được bao nhiêu buổi bù: tài liệu chưa nói' },
    { id: 'F-29', name: 'Gửi yêu cầu đổi lịch', module: 'doi-lich', src: ['XD-02', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_yeu_cau_doi.cho_xu_ly'], spec: 'Theo XD-02 phụ huynh không tự đổi: chọn buổi muốn đổi, gợi ý ngày hay khung giờ mong muốn, ghi chú; yêu cầu vào danh sách chờ xử lý của lễ tân.' },
    { id: 'F-30', name: 'Xem trạng thái yêu cầu đổi lịch', module: 'doi-lich', src: ['XD-02', 'M-06'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_yeu_cau_doi'], spec: 'Phụ huynh thấy từng yêu cầu: chờ xử lý, đã đổi (kèm buổi mới), bị từ chối kèm lý do.' },
    { id: 'F-31', name: 'Xử lý yêu cầu đổi lịch', module: 'doi-lich', src: ['XD-02', 'UC-08', 'M-03'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_yeu_cau_doi', 'trang_thai_yeu_cau_doi.da_doi', 'trang_thai_yeu_cau_doi.tu_choi'], spec: 'Danh sách yêu cầu chờ xử lý, cũ nhất trên; đổi buổi như Đổi một buổi học, hay từ chối kèm lý do.' },
    { id: 'F-32', name: 'Báo quản lý yêu cầu đổi lịch quá 24 giờ', module: 'doi-lich', src: ['XD-02'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Yêu cầu quá 24 giờ chưa xử lý thì hệ thống báo quản lý.' },

    // ===== Điểm danh =====
    { id: 'F-33', name: 'Điểm danh buổi học', module: 'diem-danh', src: ['UC-05', 'YC-06', 'M-04', 'BR-DD-01', 'BR-DD-03', 'BR-DD-04', 'A-05', 'A-10', 'D3:111'], roles: ['hlv', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.co_mat', 'trang_thai_diem_danh.vang_khong_phep', 'trang_thai_buoi.da_dien_ra'], spec: 'Mở buổi đang diễn ra; bé đã báo nghỉ hiện sẵn vắng có phép; bấm Có mặt tất cả rồi đổi bé vắng; lưu thì trừ buổi. Bé hết buổi, hết hạn bị đánh dấu, không điểm danh có mặt được. Mất mạng thì lưu tạm, tự gửi lại.' },
    { id: 'F-34', name: 'Sửa điểm danh', module: 'diem-danh', src: ['BR-DD-05', 'BR-QT-04', 'M-04', 'D7:114-115'], roles: ['hlv', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh'], spec: 'HLV sửa buổi mình dạy trong 24 giờ sau buổi; quá 24 giờ chỉ quản lý sửa, bắt buộc ghi lý do; mỗi lần sửa ghi nhật ký.' },
    { id: 'F-35', name: 'Chốt điểm danh cuối ngày', module: 'diem-danh', src: ['BR-DD-02', 'M-04'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_khong_phep'], spec: '23:00 mỗi ngày, học viên chưa có trạng thái trong buổi đã qua được ghi vắng không phép và trừ buổi.' },
    { id: 'F-36', name: 'Báo nghỉ một buổi', module: 'diem-danh', src: ['UC-07', 'YC-08', 'M-06', 'BR-DD-03', 'BR-DD-04', 'XD-01', 'A-04'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep'], spec: 'Chọn buổi sắp tới, Báo nghỉ, lý do không bắt buộc. Theo XD-01: trước giờ học ít nhất 2 giờ và chưa quá 3 lần mỗi gói thì vắng có phép; muộn hơn vẫn nhận, ghi vắng không phép, nói rõ bị trừ.' },
    { id: 'F-37', name: 'Ghi báo nghỉ thay phụ huynh', module: 'diem-danh', src: ['D5:18', 'D6:26', 'D4:39'], roles: ['le-tan'], freq: 'ngay', evidence: 'suy', status: 'pham-vi', states: ['trang_thai_diem_danh.vang_co_phep'], spec: 'Phụ huynh gọi điện hay đến quầy báo nghỉ (khoảng 15 % chưa dùng app): lễ tân ghi báo nghỉ cho buổi, cùng luật 2 giờ và 3 lần mỗi gói.' },

    // ===== Gói học, thanh toán =====
    { id: 'F-38', name: 'Bán gói học và thu tiền', module: 'goi-hoc', src: ['UC-02', 'YC-10', 'M-05', 'BR-TT-01', 'BR-TT-02', 'BR-TT-03', 'BR-LH-06', 'A-05', 'A-09'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.cho_xac_nhan_tien', 'trang_thai_goi.dang_dung', 'trang_thai_hoc_vien.dang_hoc'], spec: 'Từ hồ sơ chọn Bán gói: gói 8, 12, 24 buổi của cấp độ bé theo giá hiện hành; tiền mặt hay chuyển khoản; in biên lai có mã. Gói mới nối sau gói còn buổi; bấm hai lần chỉ ghi một khoản; bé học thử mua gói thành học viên chính thức.' },
    { id: 'F-39', name: 'Xác nhận chuyển khoản đã về', module: 'goi-hoc', src: ['UC-02', 'M-05', 'D3:176'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.dang_dung'], spec: 'Danh sách gói chờ xác nhận tiền; lễ tân xác nhận tiền đã về thì gói dùng được.' },
    { id: 'F-40', name: 'Bảo lưu gói học', module: 'goi-hoc', src: ['UC-09', 'YC-09', 'M-07', 'BR-TT-05', 'BR-QT-04'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.bao_luu'], spec: 'Từ gói của bé chọn Bảo lưu: ngày bắt đầu, số ngày; mỗi gói một lần, tối đa 30 ngày; không sinh buổi trong khoảng đó, hạn dùng cộng đúng số ngày; hết bảo lưu thì sinh lại buổi theo lịch cũ.', notes: 'mâu thuẫn: D3:341 (giữ chỗ của học viên trong lớp khi bảo lưu) với D3:346 (hết bảo lưu mà lớp cũ đã đủ sĩ số thì xếp lớp khác)' },
    { id: 'F-41', name: 'Xem danh sách gói học theo trạng thái', module: 'goi-hoc', src: ['D3:331', 'UC-09', 'BR-TT-04'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi'], spec: 'Lọc gói chờ xác nhận tiền, đang dùng, đang bảo lưu, hết buổi, hết hạn; quản lý theo dõi các gói đang bảo lưu.' },
    { id: 'F-42', name: 'Khoá gói hết buổi hay hết hạn', module: 'goi-hoc', src: ['BR-TT-04', 'BR-TT-01', 'A-05'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi.het_buoi', 'trang_thai_goi.het_han'], spec: 'Hệ thống chuyển gói sang hết buổi hay hết hạn; bé không vào lớp được tới khi mua gói mới.' },
    { id: 'F-43', name: 'Gọi mời gia hạn', module: 'goi-hoc', src: ['S-02', 'BR-TT-06'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Danh sách học viên còn từ 2 buổi trở xuống; lễ tân gọi phụ huynh và ghi kết quả cuộc gọi; đồng ý mua thì sang Bán gói.' },
    { id: 'F-44', name: 'Sửa bảng giá gói học', module: 'goi-hoc', src: ['D6:98-106', 'BR-TT-03', 'D7:136-143'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý tự sửa giá theo cấp độ và số buổi, kèm ngày áp dụng; giá mới chỉ áp cho gói bán từ ngày đó, gói đã bán giữ giá cũ.' },
    { id: 'F-45', name: 'Xem số buổi còn lại và hạn gói', module: 'goi-hoc', src: ['UC-06', 'YC-11', 'M-06', 'BR-TT-01'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_goi'], spec: 'Số buổi còn lại, hạn dùng, gói đang bảo lưu nếu có; con số khớp đúng điểm danh.' },
    { id: 'F-46', name: 'Xem lịch sử đóng tiền', module: 'goi-hoc', src: ['UC-06', 'YC-11', 'M-06', 'D3:180'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Ngày, gói, số tiền, mã biên lai của từng lần đóng.' },
    { id: 'F-47', name: 'Áp mã khuyến mãi khi bán gói', module: 'goi-hoc', src: ['CO-01'], roles: ['le-tan', 'quan-ly'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'Đợt hè có khuyến mãi: nhập mã khi bán gói thay cho giảm tay. Giai đoạn 2.' },

    // ===== Hoàn tiền =====
    { id: 'F-48', name: 'Lập đề nghị hoàn tiền', module: 'hoan-tien', src: ['BR-TT-08'], roles: ['le-tan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien.cho_duyet'], spec: 'Gói đã hết hạn mà còn buổi do trung tâm huỷ chưa bù: hệ thống quy ra tiền theo giá một buổi của gói, lễ tân lập đề nghị.' },
    { id: 'F-49', name: 'Duyệt đề nghị hoàn tiền', module: 'hoan-tien', src: ['BR-TT-08', 'BR-QT-04'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien', 'trang_thai_hoan_tien.da_duyet', 'trang_thai_hoan_tien.tu_choi'], spec: 'Danh sách đề nghị chờ duyệt; quản lý duyệt hay từ chối; mỗi lần duyệt ghi nhật ký.' },
    { id: 'F-50', name: 'Ghi ngày đã chi hoàn tiền', module: 'hoan-tien', src: ['BR-TT-08'], roles: ['le-tan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoan_tien.da_chi'], spec: 'Kế toán chi ngoài hệ thống; lễ tân ghi ngày đã chi cho đề nghị đã duyệt.' },

    // ===== Thông báo =====
    { id: 'F-51', name: 'Gửi thông báo cho phụ huynh', module: 'thong-bao', src: ['UC-10', 'YC-12', 'M-09', 'BR-TB-01', 'BR-TB-03'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn người nhận: cả trung tâm, theo lớp, theo cấp độ, hay chọn nhiều phụ huynh; soạn tiêu đề, nội dung; gửi ngay hay hẹn giờ trong 7:00–21:00; thông báo khẩn gửi ngay.' },
    { id: 'F-52', name: 'Xem thông báo', module: 'thong-bao', src: ['UC-10', 'M-06', 'M-09'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Mục Thông báo của app: đọc lại thông báo đã nhận, đánh dấu đã đọc; thông báo khẩn nổi bật.' },
    { id: 'F-53', name: 'Nhắc lịch tự động', module: 'thong-bao', src: ['BR-TB-02', 'M-09'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Gửi nhắc lịch cho phụ huynh trước giờ học 2 tiếng theo mẫu, khi quản lý bật.' },
    { id: 'F-54', name: 'Cấu hình nhắc lịch', module: 'thong-bao', src: ['BR-TB-02', 'M-09', 'D7:224-229'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Bật hay tắt nhắc lịch, sửa nội dung mẫu tin nhắc.' },
    { id: 'F-55', name: 'Cài đặt nhận thông báo', module: 'thong-bao', src: ['BR-TB-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Phụ huynh tắt các loại thông báo thường; thông báo khẩn không tắt được.', notes: 'BR-TB-04 còn mức suy luận, chờ chủ trung tâm xác nhận' },
    { id: 'F-56', name: 'Gửi SMS cho phụ huynh chưa cài app', module: 'thong-bao', src: ['CO-02'], roles: ['quan-ly', 'le-tan'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'Khoảng 15 % phụ huynh lớn tuổi chưa dùng app nhận thông báo qua SMS. Giai đoạn 2.' },

    // ===== Báo cáo =====
    { id: 'F-57', name: 'Xem báo cáo chuyên cần', module: 'bao-cao', src: ['UC-11', 'YC-13', 'S-01'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoảng thời gian, mặc định tháng này; tỉ lệ đi học theo lớp và theo HLV, số buổi vắng không phép.' },
    { id: 'F-58', name: 'Xem báo cáo doanh thu', module: 'bao-cao', src: ['UC-11', 'YC-13', 'S-01', 'BR-QT-03'], roles: ['quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Tổng thu theo tháng, theo loại gói, theo hình thức thanh toán; lễ tân không thấy.' },
    { id: 'F-59', name: 'Xuất báo cáo ra Excel', module: 'bao-cao', src: ['D3:117', 'S-01'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tải báo cáo đang xem thành file Excel để gửi kế toán; chỉ quản lý.' },
    { id: 'F-60', name: 'Đối chiếu tiền thu trong ngày', module: 'bao-cao', src: ['M-05', 'D6:24'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'suy', status: 'pham-vi', spec: 'Cuối ca: các khoản thu tiền mặt và chuyển khoản trong ngày theo người thu, để đối chiếu với tiền trong két.', notes: 'cần xác nhận: tổng thu trong ngày có tính là doanh thu mà lễ tân không được xem (BR-QT-03) không' },

    // ===== Quản trị =====
    { id: 'F-61', name: 'Thêm nhân viên và phân vai', module: 'quan-tri', src: ['UC-12', 'YC-14', 'M-08', 'BR-QT-01', 'BR-QT-02'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Họ tên, số điện thoại, vai Quản lý, Lễ tân hay HLV; với HLV chọn các lớp phụ trách; hệ thống gửi mật khẩu tạm qua SMS.' },
    { id: 'F-62', name: 'Khoá tài khoản nhân viên nghỉ việc', module: 'quan-tri', src: ['UC-12', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Khoá, không xoá, để giữ lịch sử thao tác.' },
    { id: 'F-63', name: 'Mở khoá tài khoản', module: 'quan-tri', src: ['UC-12', 'BR-QT-05', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tài khoản bị khoá do nhập sai mật khẩu 5 lần liền: quản lý mở khoá.' },
    { id: 'F-64', name: 'Tra cứu nhật ký thao tác', module: 'quan-tri', src: ['BR-QT-04', 'M-08', 'D7:247-255'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Khi có khiếu nại: lọc theo người, loại thao tác (sửa điểm danh, duyệt hoàn tiền, bảo lưu, xoá khỏi lớp), thời gian; xem giá trị trước và sau.' },
    { id: 'F-65', name: 'Đăng nhập web quản trị', module: 'quan-tri', src: ['BR-QT-01', 'BR-QT-05'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Số điện thoại và mật khẩu tối thiểu 8 ký tự; sai 5 lần liền thì khoá; lần đầu đổi mật khẩu tạm.' },
    { id: 'F-66', name: 'Đăng nhập app phụ huynh', module: 'quan-tri', src: ['NF-05', 'UC-06'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Số điện thoại đã đăng ký ở quầy và mã OTP, không cần mật khẩu.' },

    // ===== Tiến bộ (giai đoạn 2) =====
    { id: 'F-67', name: 'Ghi nhận xét tiến bộ cuối cấp độ', module: 'tien-bo', src: ['S-04'], roles: ['hlv'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'HLV ghi nhận xét kỹ năng cuối mỗi cấp độ theo mẫu chung. Giai đoạn 2; mẫu nhận xét chưa thống nhất.' },
    { id: 'F-68', name: 'Xem nhận xét tiến bộ của con', module: 'tien-bo', src: ['S-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'Phụ huynh xem nhận xét kỹ năng của HLV trên app. Giai đoạn 2.' },
  ],
  skip: [
    { src: 'D1:28-31', why: 'Tóm tắt số quy tắc, không có việc' },
    { src: 'D1:104-107', why: 'Phát hiện đã gỡ ở XD-01, XD-02; việc nằm ở Báo nghỉ một buổi và Gửi yêu cầu đổi lịch' },
    { src: 'D2:20-23', why: 'Tóm tắt số ca biên, không có việc' },
    { src: 'D2:39-45', why: 'Câu hỏi mở OQ-01..03: ghi ở notes của Cho học viên ngừng học, Xem hồ sơ học viên, Đề xuất lên cấp độ, Chuyển lớp cố định' },
    { src: 'D3:21-30', why: 'Danh sách actor, thành mã vai' },
    { src: 'D3:31-79', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:33-38', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:39-45', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:46-53', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:54-59', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:60-66', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:67-72', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:73-79', why: 'Bảng tóm tắt use case; chức năng trỏ vào đặc tả ở mục 5' },
    { src: 'D3:80-98', why: 'Ma trận actor × use case: vai đã ghi ở roles từng chức năng' },
    { src: 'D4:17-20', why: 'Tóm tắt số hạng mục MoSCoW, không có việc' },
    { src: 'D4:42-45', why: 'Phát hiện: học thử theo BR-LH-06, yêu cầu đổi lịch theo XD-02, đã có chức năng' },
    { src: 'D6:29-35', why: 'Mục tiêu dự án, không có việc riêng' },
    { src: 'D6:36-44', why: 'Bề mặt: thành vai và bề mặt của layout' },
    { src: 'D6:91-97', why: 'Ngoài phạm vi: bán đồ bơi, tính lương HLV' },
  ],
};
