// Bố cục (M2) — Sóng Xanh. Kiểm: node <skills>/sketch-to-map/scripts/map.mjs check <thư-mục-prototype> --shots
window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'quan-tri', name: 'Quản trị', depends: [] },
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'lop', name: 'Lớp học', depends: ['hoc-vien', 'quan-tri'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'lich', name: 'Lịch', depends: ['lop'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'doi-lich', name: 'Đổi lịch', depends: ['lich', 'diem-danh'] },
    { id: 'hoc-thu', name: 'Học thử', depends: ['hoc-vien', 'lop', 'lich'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien', 'lop', 'lich'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', depends: ['goi-hoc', 'lich'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
    { id: 'tien-bo', name: 'Tiến bộ', depends: ['lop'] },
  ],
  screens: [
    // ----- Web quản trị -----
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true, zones: ['Form đăng nhập'] },
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'hoc-vien', roles: ['le-tan'],
      bands: [
        { name: 'Tìm học viên', items: ['F-01'] },
        { name: 'Việc nhanh', items: ['F-03', 'F-38', 'F-07', 'F-37'] },
        { name: 'Cần xử lý', items: ['F-31', 'F-39'] },
        { name: 'Cần gọi', items: ['F-43', 'F-16'] },
      ] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      bands: [
        { name: 'Hôm nay ở bể', items: ['F-19'] },
        { name: 'Cần quyết', items: ['F-49', 'F-31'] },
        { name: 'HLV nghỉ hôm nay', items: ['F-24'] },
        { name: 'Số liệu tháng này', items: ['F-58', 'F-57'] },
        { name: 'Việc nhanh', items: ['F-51', 'F-23'] },
      ] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [
        { name: 'Buổi đang diễn ra', items: ['F-33'] },
        { name: 'Lịch dạy tuần này', items: ['F-20'] },
        { name: 'Buổi vừa dạy', items: ['F-34'] },
        { name: 'Bé học thử hôm nay', items: ['F-08'] },
      ] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Thông tin', 'Lịch học', 'Gói học'] },
    { id: 'lop', name: 'Lớp học', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'lop', pick: true,
      zones: ['Thông tin lớp', 'Học viên trong lớp', 'Danh sách chờ'] },
    { id: 'lich', name: 'Lịch tuần', surface: 'web', module: 'lich', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ', 'Lưới làn và giờ', 'Ngăn chi tiết lớp'] },
    { id: 'doi-lich', name: 'Đổi lịch và học bù', surface: 'web', module: 'doi-lich', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Yêu cầu từ phụ huynh', 'Buổi cần học bù'] },
    { id: 'goi-hoc', name: 'Gói và thu tiền', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Thanh công cụ', 'Lọc theo trạng thái'], tabs: ['Gói học', 'Hoàn tiền'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ', 'Đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ'], tabs: ['Chuyên cần', 'Thu trong ngày', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Bộ lọc', 'Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Bảng giá', 'Khoá học', 'Ngày nghỉ lễ', 'Nhắc lịch'] },

    // ----- App phụ huynh -----
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'quan-tri', roles: ['phu-huynh'], entry: true, zones: ['Form đăng nhập'] },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'lich', roles: ['phu-huynh'],
      bands: [
        { name: 'Chọn con', items: ['F-06'] },
        { name: 'Buổi sắp tới', items: ['F-25', 'F-36', 'F-29'] },
        { name: 'Số buổi còn lại', items: ['F-45'] },
        { name: 'Yêu cầu đổi lịch', items: ['F-30'] },
      ] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'], zones: ['Gói đang dùng', 'Lịch sử đóng tiền', 'Nhận xét tiến bộ'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'quan-tri', roles: ['phu-huynh'], zones: ['Con của tôi', 'Nhận thông báo'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['quay', 'lich', 'doi-lich'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'goi-hoc'] },
      { name: 'Liên lạc và số liệu', items: ['thong-bao', 'bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich', 'doi-lich'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'goi-hoc'] },
      { name: 'Liên lạc và số liệu', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    // Học viên
    'F-01': [{ screen: 'quay', zone: 'Tìm học viên', tier: 1, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' }],
    'F-02': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'trang' },
    'F-03': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-04': { screen: 'ho-so', tab: 'Thông tin', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 4, mo: 'hop-thoai' },
    'F-06': { screen: 'app-lich', zone: 'Chọn con', tier: 2, mo: 'tai-cho' },
    // Học thử
    'F-07': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-08': { screen: 'buoi-day', zone: 'Bé học thử hôm nay', tier: 2, mo: 'hop-thoai' },
    'F-09': { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' },
    // Lớp
    'F-11': { screen: 'cai-dat', tab: 'Khoá học', tier: 2, mo: 'ngan-truot' },
    'F-12': { screen: 'lop', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-13': { screen: 'lop', zone: 'Bảng lớp', tier: 2, mo: 'tai-cho' },
    'F-14': { screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'ngan-truot' },
    'F-15': { screen: 'lop', zone: 'Bảng lớp', tier: 4, mo: 'hop-thoai' },
    'F-16': [{ screen: 'quay', zone: 'Cần gọi', tier: 2, mo: 'tai-cho' }, { screen: 'lop-chi-tiet', zone: 'Danh sách chờ', tier: 2, mo: 'tai-cho' }],
    'F-17': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'hop-thoai' },
    'F-18': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'hop-thoai' },
    // Lịch
    'F-19': [{ screen: 'lich', zone: 'Lưới làn và giờ', tier: 2, mo: 'trang' }, { screen: 'tong-quan', zone: 'Hôm nay ở bể', tier: 2, mo: 'tai-cho' }],
    'F-20': [{ screen: 'buoi-day', zone: 'Lịch dạy tuần này', tier: 2, mo: 'tai-cho' }, { screen: 'lich', zone: 'Thanh công cụ', tier: 2, mo: 'tai-cho' }],
    'F-22': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'tai-cho' },
    'F-23': { screen: 'lich', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-24': { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'ngan-truot' },
    'F-25': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 2, mo: 'tai-cho' },
    // Đổi lịch
    'F-26': [{ screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' }, { screen: 'doi-lich', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' }],
    'F-27': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'ngan-truot' },
    'F-28': { screen: 'doi-lich', zone: 'Buổi cần học bù', tier: 2, mo: 'ngan-truot' },
    'F-29': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-30': { screen: 'app-lich', zone: 'Yêu cầu đổi lịch', tier: 2, mo: 'tai-cho' },
    'F-31': [{ screen: 'quay', zone: 'Cần xử lý', tier: 2, mo: 'ngan-truot' }, { screen: 'doi-lich', zone: 'Yêu cầu từ phụ huynh', tier: 1, mo: 'ngan-truot' }],
    // Điểm danh
    'F-33': [{ screen: 'buoi-day', zone: 'Buổi đang diễn ra', tier: 1, mo: 'tai-cho' }, { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'ngan-truot' }],
    'F-34': [{ screen: 'buoi-day', zone: 'Buổi vừa dạy', tier: 4, mo: 'ngan-truot' }, { screen: 'lich', zone: 'Ngăn chi tiết lớp', tier: 4, mo: 'ngan-truot' }],
    'F-36': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'sheet' },
    'F-37': { screen: 'quay', zone: 'Việc nhanh', tier: 2, mo: 'hop-thoai' },
    // Gói học, thu tiền
    'F-38': [{ screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'ngan-truot' }, { screen: 'goi-hoc', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' }],
    'F-39': [{ screen: 'quay', zone: 'Cần xử lý', tier: 2, mo: 'tai-cho' }, { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'hop-thoai' }],
    'F-40': { screen: 'ho-so', tab: 'Gói học', tier: 4, mo: 'hop-thoai' },
    'F-41': { screen: 'goi-hoc', tab: 'Gói học', tier: 2, mo: 'tai-cho' },
    'F-43': { screen: 'quay', zone: 'Cần gọi', tier: 2, mo: 'tai-cho' },
    'F-44': { screen: 'cai-dat', tab: 'Bảng giá', tier: 2, mo: 'tai-cho' },
    'F-45': [{ screen: 'app-goi', zone: 'Gói đang dùng', tier: 2, mo: 'tai-cho' }, { screen: 'app-lich', zone: 'Số buổi còn lại', tier: 2, mo: 'tai-cho' }],
    'F-46': { screen: 'app-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-47': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 4, mo: 'ngan-truot' },
    // Hoàn tiền
    'F-48': { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'hop-thoai' },
    'F-49': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-50': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    // Thông báo
    'F-51': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-52': { screen: 'app-thong-bao', zone: 'Danh sách thông báo', tier: 2, mo: 'tai-cho' },
    'F-54': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 2, mo: 'tai-cho' },
    'F-55': { screen: 'app-tai-khoan', zone: 'Nhận thông báo', tier: 2, mo: 'tai-cho' },
    'F-56': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 3, mo: 'ngan-truot' },
    // Báo cáo
    'F-57': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Số liệu tháng này', tier: 2, mo: 'tai-cho' }],
    'F-58': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Số liệu tháng này', tier: 2, mo: 'tai-cho' }],
    'F-59': { screen: 'bao-cao', zone: 'Thanh công cụ', tier: 3, mo: 'tai-cho' },
    'F-60': { screen: 'bao-cao', tab: 'Thu trong ngày', tier: 2, mo: 'tai-cho' },
    // Quản trị
    'F-61': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-62': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-63': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-64': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 2, mo: 'tai-cho' },
    'F-65': { screen: 'dang-nhap', zone: 'Form đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-66': { screen: 'app-dang-nhap', zone: 'Form đăng nhập', tier: 1, mo: 'tai-cho' },
    // Tiến bộ (giai đoạn sau)
    'F-67': { screen: 'lop-chi-tiet', zone: 'Học viên trong lớp', tier: 4, mo: 'ngan-truot' },
    'F-68': { screen: 'app-goi', zone: 'Nhận xét tiến bộ', tier: 2, mo: 'tai-cho' },
  },
  shortcuts: [
    { from: 'quay', to: 'F-03', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-38', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-07', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-14', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-27', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-49', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-31', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-24', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-51', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-23', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới đến quầy cho con học', steps: ['F-01', 'F-03', 'F-38', 'F-14'] },
    { role: 'le-tan', name: 'Phụ huynh gọi xin đổi buổi', steps: ['F-01', 'F-02', 'F-26'] },
    { role: 'le-tan', name: 'Đầu ca chiều ở quầy', steps: ['F-39', 'F-31', 'F-43'] },
    { role: 'quan-ly', name: 'HLV báo nghỉ buổi sáng', steps: ['F-19', 'F-24'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số', steps: ['F-58', 'F-57', 'F-59'] },
    { role: 'quan-ly', name: 'Mở lớp cho đợt mới', steps: ['F-11', 'F-12'] },
    { role: 'hlv', name: 'Dạy một buổi ở bể', steps: ['F-20', 'F-33', 'F-34'] },
    { role: 'hlv', name: 'Buổi học thử', steps: ['F-33', 'F-08'] },
    { role: 'phu-huynh', name: 'Bé ốm, báo nghỉ', steps: ['F-06', 'F-25', 'F-36'] },
    { role: 'phu-huynh', name: 'Xin đổi buổi học', steps: ['F-25', 'F-29', 'F-30'] },
    { role: 'phu-huynh', name: 'Xem gói còn bao nhiêu', steps: ['F-45', 'F-46'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Mẹ bé Minh Anh đang đứng ở quầy, muốn mua tiếp 12 buổi cho bé và trả tiền mặt.', feature: 'F-38' },
    { role: 'le-tan', say: 'Một phụ huynh dẫn con 7 tuổi tới lần đầu, muốn cho bé theo học ở trung tâm.', feature: 'F-03' },
    { role: 'le-tan', say: 'Bố bé Bảo Châu gọi điện: thứ Sáu này bé bận, xin cho bé học sáng thứ Bảy thay vào.', feature: 'F-26' },
    { role: 'le-tan', say: 'Đầu ca chiều, ba phụ huynh đã nhắn qua app xin dời giờ học tuần này và đang chờ quầy trả lời.', feature: 'F-31' },
    { role: 'le-tan', say: 'Kế toán báo khoản 1.680.000 ₫ của phụ huynh bé Gia Huy đã vào tài khoản sáng nay.', feature: 'F-39' },
    { role: 'le-tan', say: 'Bơm lọc bể lớn hỏng lúc 15:00; các lớp từ 16:00 tới 19:00 chiều nay không học được.', feature: 'F-23' },
    { role: 'hlv', say: '17:30, lớp của bạn ở làn 3 bắt đầu: chín bé tới, bé Khoa không tới.', feature: 'F-33' },
    { role: 'quan-ly', say: '7 giờ sáng, HLV Tuấn nhắn bị ốm; hôm nay anh có ba lớp buổi chiều.', feature: 'F-24' },
    { role: 'phu-huynh', say: 'Bé Na sốt từ sáng, chiều nay không đi bơi được.', feature: 'F-36' },
    { role: 'phu-huynh', say: 'Tối nay bạn muốn biết gói của con còn học được tới bao giờ.', feature: 'F-45' },
  ],
};
