window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'hom-nay-le-tan' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'hom-nay-quan-ly' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'hom-nay-hlv' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'trang-chu' },
  ],
  modules: [
    { id: 'quan-tri', name: 'Quản trị', depends: [] },
    { id: 'hoc-vien', name: 'Học viên', depends: ['quan-tri'] },
    { id: 'lop', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'lich', name: 'Lịch và buổi học', depends: ['lop'] },
    { id: 'goi-tien', name: 'Gói học và tiền', depends: ['hoc-vien'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-tien'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['lich'] },
    { id: 'app-phu-huynh', name: 'App phụ huynh', depends: ['lich', 'diem-danh', 'goi-tien', 'thong-bao'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-tien'] },
  ],
  screens: [
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['le-tan', 'quan-ly', 'hlv'], entry: true, zones: ['Đăng nhập'] },
    { id: 'hom-nay-le-tan', name: 'Hôm nay', surface: 'web', module: 'lich', roles: ['le-tan'],
      bands: [{ name: 'Cần xử lý hôm nay', items: ['F-16', 'F-31'] }, { name: 'Việc nhanh ở quầy', items: ['F-01', 'F-26', 'F-11', 'F-06'] }] },
    { id: 'hom-nay-quan-ly', name: 'Tổng quan hôm nay', surface: 'web', module: 'lich', roles: ['quan-ly'],
      bands: [{ name: 'Cần xem hôm nay', items: ['F-30'] }, { name: 'Việc nhanh', items: ['F-18', 'F-51', 'F-46'] }] },
    { id: 'hom-nay-hlv', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [{ name: 'Các buổi hôm nay', items: ['F-14'] }, { name: 'Việc nhanh ở bể', items: ['F-22', 'F-07'] }] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Buổi học', 'Gói học', 'Thanh toán', 'Nhận xét'] },
    { id: 'lop', name: 'Lớp học', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly'], zones: ['Lọc lớp', 'Bảng lớp và chỗ trống'], tabs: ['Các lớp', 'Danh sách chờ'] },
    { id: 'lich', name: 'Lịch', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Lưới lịch theo làn và giờ'] },
    { id: 'diem-danh', name: 'Điểm danh', surface: 'web', module: 'diem-danh', roles: ['quan-ly', 'hlv'], pick: true, zones: ['Chọn buổi', 'Danh sách học viên của buổi'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', surface: 'web', module: 'goi-tien', roles: ['le-tan', 'quan-ly'], zones: ['Bảng gói học', 'Chờ xác nhận tiền'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', surface: 'web', module: 'goi-tien', roles: ['le-tan', 'quan-ly'], zones: ['Bảng đề nghị hoàn tiền'] },
    { id: 'bang-gia', name: 'Bảng giá', surface: 'web', module: 'goi-tien', roles: ['quan-ly'], zones: ['Bảng giá hiện hành'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['le-tan', 'quan-ly'], zones: ['Thông báo đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['le-tan', 'quan-ly'], zones: ['Chọn khoảng thời gian', 'Số liệu'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Nhắc lịch tự động'], tabs: ['Nhắc lịch', 'Ngày nghỉ lễ'] },
    { id: 'dang-nhap-app', name: 'Đăng nhập', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], entry: true, zones: ['Số điện thoại và mã xác nhận'] },
    { id: 'trang-chu', name: 'Trang chủ', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'],
      bands: [{ name: 'Buổi sắp tới của con', items: ['F-40', 'F-44'] }, { name: 'Việc nhanh', items: ['F-42', 'F-43'] }] },
    { id: 'goi-cua-con', name: 'Gói và đóng tiền', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Lịch sử đóng tiền'] },
    { id: 'thong-bao-app', name: 'Thông báo', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'tai-khoan', name: 'Tài khoản', surface: 'app', module: 'app-phu-huynh', roles: ['phu-huynh'], zones: ['Thông tin phụ huynh'], tabs: ['Thông tin', 'Nhận xét của con'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [{ name: 'Hằng ngày', items: ['hom-nay-le-tan', 'hoc-vien', 'lop', 'lich', 'goi-hoc'] }, { name: 'Tiền, thông báo, báo cáo', items: ['hoan-tien', 'thong-bao', 'bao-cao'] }] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['hom-nay-quan-ly', 'lich', 'diem-danh'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop'] },
      { name: 'Gói và tiền', items: ['goi-hoc', 'hoan-tien', 'bang-gia'] },
      { name: 'Thông báo và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['hom-nay-hlv', 'diem-danh', 'lich', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['trang-chu', 'goi-cua-con', 'thong-bao-app', 'tai-khoan'] }] },
  ],
  place: {
    'F-53': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-01': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 2, mo: 'ngan-truot' },
    'F-02': { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' },
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'tai-cho' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-06': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 2, mo: 'ngan-truot' },
    'F-07': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 2, mo: 'hop-thoai' },
    'F-08': { screen: 'lop', zone: 'Bảng lớp và chỗ trống', tier: 3, mo: 'ngan-truot' },
    'F-09': { screen: 'lop', zone: 'Bảng lớp và chỗ trống', tier: 2, mo: 'ngan-truot' },
    'F-10': { screen: 'lop', tab: 'Các lớp', tier: 2, mo: 'tai-cho' },
    'F-11': { screen: 'lop', tab: 'Các lớp', tier: 1, mo: 'ngan-truot' },
    'F-12': { screen: 'lop', tab: 'Danh sách chờ', tier: 2, mo: 'tai-cho' },
    'F-13': { screen: 'lop', tab: 'Các lớp', tier: 3, mo: 'hop-thoai' },
    'F-14': [{ screen: 'lich', zone: 'Lưới lịch theo làn và giờ', tier: 1, mo: 'tai-cho' }, { screen: 'hom-nay-hlv', zone: 'Các buổi hôm nay', tier: 2, mo: 'tai-cho' }],
    'F-15': [{ screen: 'lich', zone: 'Lưới lịch theo làn và giờ', tier: 2, mo: 'ngan-truot' }, { screen: 'ho-so', tab: 'Buổi học', tier: 2, mo: 'ngan-truot' }],
    'F-16': { screen: 'hom-nay-le-tan', zone: 'Cần xử lý hôm nay', tier: 1, mo: 'ngan-truot' },
    'F-17': { screen: 'lich', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-18': { screen: 'lich', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-19': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'tai-cho' },
    'F-20': { screen: 'lich', zone: 'Lưới lịch theo làn và giờ', tier: 2, mo: 'ngan-truot' },
    'F-22': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 1, mo: 'tai-cho' },
    'F-23': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 2, mo: 'hop-thoai' },
    'F-24': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 2, mo: 'tai-cho' },
    'F-26': { screen: 'goi-hoc', zone: 'Bảng gói học', tier: 1, mo: 'ngan-truot' },
    'F-27': { screen: 'goi-hoc', zone: 'Chờ xác nhận tiền', tier: 2, mo: 'tai-cho' },
    'F-28': { screen: 'ho-so', tab: 'Thanh toán', tier: 2, mo: 'tai-cho' },
    'F-29': { screen: 'goi-hoc', zone: 'Bảng gói học', tier: 2, mo: 'hop-thoai' },
    'F-30': { screen: 'hom-nay-quan-ly', zone: 'Cần xem hôm nay', tier: 2, mo: 'tai-cho' },
    'F-31': { screen: 'hom-nay-le-tan', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'tai-cho' },
    'F-32': { screen: 'hoan-tien', zone: 'Bảng đề nghị hoàn tiền', tier: 1, mo: 'ngan-truot' },
    'F-33': { screen: 'hoan-tien', zone: 'Bảng đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-34': { screen: 'hoan-tien', zone: 'Bảng đề nghị hoàn tiền', tier: 2, mo: 'hop-thoai' },
    'F-35': { screen: 'bang-gia', zone: 'Bảng giá hiện hành', tier: 1, mo: 'tai-cho' },
    'F-38': { screen: 'dang-nhap-app', zone: 'Số điện thoại và mã xác nhận', tier: 1, mo: 'tai-cho' },
    'F-39': { screen: 'trang-chu', zone: 'Buổi sắp tới của con', tier: 2, mo: 'tai-cho' },
    'F-40': { screen: 'trang-chu', zone: 'Buổi sắp tới của con', tier: 1, mo: 'tai-cho' },
    'F-41': { screen: 'goi-cua-con', zone: 'Lịch sử đóng tiền', tier: 1, mo: 'tai-cho' },
    'F-42': { screen: 'trang-chu', zone: 'Buổi sắp tới của con', tier: 2, mo: 'sheet' },
    'F-43': { screen: 'trang-chu', zone: 'Buổi sắp tới của con', tier: 2, mo: 'sheet' },
    'F-44': { screen: 'trang-chu', zone: 'Buổi sắp tới của con', tier: 2, mo: 'tai-cho' },
    'F-45': { screen: 'thong-bao-app', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-46': { screen: 'thong-bao', zone: 'Thông báo đã gửi', tier: 1, mo: 'ngan-truot' },
    'F-47': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 1, mo: 'tai-cho' },
    'F-50': { screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' },
    'F-51': { screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' },
    'F-52': { screen: 'bao-cao', zone: 'Số liệu', tier: 3, mo: 'hop-thoai' },
    'F-54': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 1, mo: 'ngan-truot' },
    'F-55': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 2, mo: 'ngan-truot' },
    'F-56': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-57': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 3, mo: 'hop-thoai' },
    'F-58': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 1, mo: 'tai-cho' },
    'F-59': { screen: 'ho-so', tab: 'Nhận xét', tier: 2, mo: 'ngan-truot' },
    'F-60': { screen: 'tai-khoan', tab: 'Nhận xét của con', tier: 2, mo: 'tai-cho' },
    'F-61': { screen: 'goi-hoc', zone: 'Bảng gói học', tier: 3, mo: 'hop-thoai' },
    'F-62': { screen: 'thong-bao', zone: 'Thông báo đã gửi', tier: 3, mo: 'hop-thoai' },
  },
  shortcuts: [
    { from: 'hom-nay-le-tan', to: 'F-01', mo: 'ngan-truot' },
    { from: 'hom-nay-le-tan', to: 'F-26', mo: 'ngan-truot' },
    { from: 'hom-nay-le-tan', to: 'F-11', mo: 'ngan-truot' },
    { from: 'hom-nay-le-tan', to: 'F-06', mo: 'ngan-truot' },
    { from: 'hom-nay-quan-ly', to: 'F-18', mo: 'hop-thoai' },
    { from: 'hom-nay-quan-ly', to: 'F-51', mo: 'ngan-truot' },
    { from: 'hom-nay-quan-ly', to: 'F-46', mo: 'ngan-truot' },
    { from: 'hom-nay-hlv', to: 'F-22', mo: 'ngan-truot' },
    { from: 'hom-nay-hlv', to: 'F-07', mo: 'hop-thoai' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới đến mua gói và xếp lớp', steps: ['F-01', 'F-26', 'F-11'] },
    { role: 'le-tan', name: 'Phụ huynh xin đổi buổi', steps: ['F-16', 'F-15'] },
    { role: 'quan-ly', name: 'Mở đợt lớp mới', steps: ['F-08', 'F-09', 'F-46'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số liệu', steps: ['F-50', 'F-51', 'F-52'] },
    { role: 'hlv', name: 'Buổi dạy hôm nay', steps: ['F-14', 'F-22', 'F-24'] },
    { role: 'phu-huynh', name: 'Con ốm xin nghỉ', steps: ['F-39', 'F-40', 'F-42'] },
    { role: 'phu-huynh', name: 'Xin đổi buổi học', steps: ['F-43', 'F-44'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một phụ huynh dắt con đến học lần đầu, muốn mua gói 12 buổi.', feature: 'F-26' },
    { role: 'le-tan', say: 'Chị phụ huynh gọi báo bé không đi được tuần này, nhờ chuyển sang lớp ngày thứ Bảy.', feature: 'F-15' },
    { role: 'le-tan', say: 'Đầu giờ chiều, kiểm tra có phụ huynh nào xin đổi buổi mà chưa ai trả lời.', feature: 'F-16' },
    { role: 'le-tan', say: 'Một lớp vừa có chỗ trống, cần biết gọi phụ huynh nào trước.', feature: 'F-12' },
    { role: 'quan-ly', say: 'Cuối tháng chủ trung tâm muốn biết đã thu được bao nhiêu tiền.', feature: 'F-51' },
    { role: 'quan-ly', say: 'Bơm lọc hỏng, bể đóng cửa cả buổi chiều, mọi lớp trong khoảng đó phải nghỉ.', feature: 'F-18' },
    { role: 'hlv', say: 'Buổi 17:30 vừa bắt đầu, cần ghi lại bé nào có mặt, bé nào vắng.', feature: 'F-22' },
    { role: 'hlv', say: 'Sáng đến bể, cần biết hôm nay mình dạy những lớp nào, giờ nào.', feature: 'F-14' },
    { role: 'phu-huynh', say: 'Bé bị sốt sáng nay, muốn xin nghỉ buổi chiều.', feature: 'F-42' },
    { role: 'phu-huynh', say: 'Muốn biết con còn bao nhiêu buổi và gói hết hạn khi nào.', feature: 'F-40' },
  ],
};
