window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'quan-ly', name: 'Quản lý trung tâm', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'buoi-hom-nay' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-hom-nay' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên và phụ huynh', depends: [] },
    { id: 'lop-hoc', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien', 'lop-hoc'] },
    { id: 'lich-hoc', name: 'Lịch và buổi học', depends: ['lop-hoc', 'goi-hoc'] },
    { id: 'diem-danh', name: 'Điểm danh và báo nghỉ', depends: ['lich-hoc', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien', 'lich-hoc'] },
    { id: 'quan-tri', name: 'Báo cáo và quản trị', depends: ['diem-danh', 'goi-hoc'] },
  ],
  screens: [
    // Web: vào trước trang chủ
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true, zones: ['Đăng nhập', 'Đổi mật khẩu tạm'] },
    // Web: trang chủ theo vai
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'hoc-vien', roles: ['le-tan'],
      bands: [
        { name: 'Tìm học viên', items: ['F-30'] },
        { name: 'Việc ở quầy', items: ['F-32', 'F-08', 'F-58', 'F-05', 'F-66'] },
        { name: 'Yêu cầu đổi lịch chờ xử lý', items: ['F-49', 'F-44', 'F-50'] },
        { name: 'Chờ xác nhận chuyển khoản', items: ['F-09'] },
        { name: 'Sắp hết buổi', items: ['F-22', 'F-23'] },
      ] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      bands: [
        { name: 'Cần chú ý', items: ['F-90', 'F-25'] },
        { name: 'Hôm nay ở bể', items: ['F-52', 'F-53'] },
        { name: 'Tháng này', items: ['F-72', 'F-71'] },
        { name: 'Việc nhanh', items: ['F-84'] },
      ] },
    { id: 'buoi-hom-nay', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [
        { name: 'Điểm danh buổi đang dạy', items: ['F-01', 'F-02', 'F-67', 'F-65'] },
        { name: 'Lịch dạy tuần này', items: ['F-42'] },
      ] },
    // Web: lịch và buổi
    { id: 'lich-tuan', name: 'Lịch tuần', surface: 'web', module: 'lich-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Lưới làn và giờ', 'Ngăn chi tiết lớp'], tabs: ['Theo làn', 'Theo HLV'] },
    { id: 'buoi-hoc', name: 'Buổi học', surface: 'web', module: 'diem-danh', roles: ['quan-ly', 'le-tan'], parent: 'lich-tuan', pick: true,
      zones: ['Đầu buổi', 'Điểm danh'] },
    { id: 'yeu-cau-doi-lich', name: 'Yêu cầu đổi lịch', surface: 'web', module: 'lich-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Lọc theo trạng thái', 'Danh sách yêu cầu'] },
    // Web: học viên
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Thanh công cụ', 'Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['quan-ly', 'le-tan', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Gói học', 'Lịch và điểm danh', 'Đóng tiền', 'Phụ huynh'] },
    // Web: lớp
    { id: 'lop', name: 'Lớp học', surface: 'web', module: 'lop-hoc', roles: ['quan-ly', 'le-tan', 'hlv'],
      zones: ['Thanh công cụ', 'Lọc theo cấp độ, ngày, giờ', 'Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop-hoc', roles: ['quan-ly', 'le-tan', 'hlv'], parent: 'lop', pick: true,
      zones: ['Đầu lớp'], tabs: ['Học viên', 'Danh sách chờ'] },
    // Web: gói và tiền
    { id: 'thu-tien', name: 'Thu tiền', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Khoản thu hôm nay', 'Chờ xác nhận chuyển khoản', 'Đối chiếu cuối ngày'] },
    { id: 'goi-hoc', name: 'Gói học', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'],
      zones: ['Lọc theo trạng thái'], tabs: ['Gói', 'Hoàn tiền'] },
    // Web: thông báo, báo cáo, quản trị
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ', 'Đã gửi và đang hẹn giờ'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'quan-tri', roles: ['quan-ly', 'le-tan'],
      zones: ['Thanh công cụ'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'],
      tabs: ['Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch', 'Khuyến mãi', 'Nhật ký thao tác'] },
    // App phụ huynh
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'hoc-vien', roles: ['phu-huynh'], entry: true, zones: ['Số điện thoại và mã OTP'] },
    { id: 'app-hom-nay', name: 'Hôm nay', surface: 'app', module: 'lich-hoc', roles: ['phu-huynh'],
      bands: [
        { name: 'Con đang xem', items: ['F-37'] },
        { name: 'Buổi học sắp tới', items: ['F-43', 'F-04', 'F-47'] },
        { name: 'Số buổi còn lại', items: ['F-12'] },
      ] },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'lich-hoc', roles: ['phu-huynh'],
      tabs: ['Sắp tới', 'Đã học', 'Yêu cầu đổi lịch'] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'],
      zones: ['Gói đang dùng', 'Các lần đóng tiền'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'],
      zones: ['Thông báo đã nhận'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'hoc-vien', roles: ['phu-huynh'],
      zones: ['Cài đặt thông báo'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['quay', 'lich-tuan', 'hoc-vien', 'lop', 'yeu-cau-doi-lich'] },
      { name: 'Gói và thu tiền', items: ['thu-tien', 'goi-hoc'] },
      { name: 'Thông báo và báo cáo', items: ['thong-bao', 'bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich-tuan', 'hoc-vien', 'lop', 'yeu-cau-doi-lich'] },
      { name: 'Gói và thu tiền', items: ['thu-tien', 'goi-hoc'] },
      { name: 'Thông báo và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-hom-nay', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-hom-nay', 'app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    // diem-danh
    'F-01': [{ screen: 'buoi-hom-nay', zone: 'Điểm danh buổi đang dạy', tier: 1, mo: 'tai-cho' }, { screen: 'buoi-hoc', zone: 'Điểm danh', tier: 1, mo: 'tai-cho' }],
    'F-02': [{ screen: 'buoi-hom-nay', zone: 'Điểm danh buổi đang dạy', tier: 4, mo: 'tai-cho' }, { screen: 'buoi-hoc', zone: 'Điểm danh', tier: 4, mo: 'tai-cho' }],
    'F-04': { screen: 'app-lich', tab: 'Sắp tới', tier: 4, mo: 'sheet' },
    'F-05': { screen: 'quay', zone: 'Việc ở quầy', tier: 2, mo: 'hop-thoai' },
    'F-06': { screen: 'buoi-hoc', zone: 'Điểm danh', tier: 4, mo: 'ngan-truot' },
    'F-07': { screen: 'app-lich', tab: 'Đã học', tier: 2, mo: 'tai-cho' },
    // goi-hoc
    'F-08': { screen: 'thu-tien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-09': { screen: 'thu-tien', zone: 'Chờ xác nhận chuyển khoản', tier: 4, mo: 'tai-cho' },
    'F-10': { screen: 'thu-tien', zone: 'Đối chiếu cuối ngày', tier: 2, mo: 'tai-cho' },
    'F-11': [{ screen: 'ho-so', tab: 'Đóng tiền', tier: 2, mo: 'tai-cho' }, { screen: 'app-goi', zone: 'Các lần đóng tiền', tier: 2, mo: 'tai-cho' }],
    'F-12': [{ screen: 'ho-so', tab: 'Gói học', tier: 2, mo: 'tai-cho' }, { screen: 'app-goi', zone: 'Gói đang dùng', tier: 1, mo: 'tai-cho' }, { screen: 'app-hom-nay', zone: 'Số buổi còn lại', tier: 2, mo: 'tai-cho' }],
    'F-16': { screen: 'goi-hoc', tab: 'Gói', tier: 4, mo: 'hop-thoai' },
    'F-18': { screen: 'goi-hoc', tab: 'Gói', tier: 1, mo: 'tai-cho' },
    'F-21': { screen: 'cai-dat', tab: 'Bảng giá', tier: 3, mo: 'ngan-truot' },
    'F-22': { screen: 'quay', zone: 'Sắp hết buổi', tier: 2, mo: 'tai-cho' },
    'F-23': { screen: 'quay', zone: 'Sắp hết buổi', tier: 4, mo: 'hop-thoai' },
    'F-24': { screen: 'goi-hoc', tab: 'Gói', tier: 4, mo: 'ngan-truot' },
    'F-25': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-26': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-27': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 2, mo: 'tai-cho' },
    'F-28': { screen: 'thu-tien', zone: 'Thanh công cụ', tier: 4, mo: 'tai-cho' },
    'F-29': { screen: 'cai-dat', tab: 'Khuyến mãi', tier: 3, mo: 'ngan-truot' },
    // hoc-vien
    'F-30': [{ screen: 'quay', zone: 'Tìm học viên', tier: 2, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }],
    'F-31': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'tai-cho' },
    'F-32': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-33': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-34': { screen: 'ho-so', tab: 'Phụ huynh', tier: 3, mo: 'ngan-truot' },
    'F-35': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-37': { screen: 'app-hom-nay', zone: 'Con đang xem', tier: 2, mo: 'tai-cho' },
    'F-38': { screen: 'app-dang-nhap', zone: 'Số điện thoại và mã OTP', tier: 1, mo: 'trang' },
    // lich-hoc
    'F-40': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 3, mo: 'hop-thoai' },
    'F-41': { screen: 'lich-tuan', tab: 'Theo làn', tier: 1, mo: 'tai-cho' },
    'F-42': [{ screen: 'buoi-hom-nay', zone: 'Lịch dạy tuần này', tier: 2, mo: 'tai-cho' }, { screen: 'lich-tuan', tab: 'Theo HLV', tier: 2, mo: 'tai-cho' }],
    'F-43': [{ screen: 'app-hom-nay', zone: 'Buổi học sắp tới', tier: 2, mo: 'tai-cho' }, { screen: 'app-lich', tab: 'Sắp tới', tier: 1, mo: 'tai-cho' }],
    'F-44': { screen: 'yeu-cau-doi-lich', zone: 'Danh sách yêu cầu', tier: 4, mo: 'ngan-truot' },
    'F-47': { screen: 'app-lich', tab: 'Sắp tới', tier: 4, mo: 'sheet' },
    'F-48': { screen: 'app-lich', tab: 'Yêu cầu đổi lịch', tier: 2, mo: 'tai-cho' },
    'F-49': [{ screen: 'quay', zone: 'Yêu cầu đổi lịch chờ xử lý', tier: 2, mo: 'tai-cho' }, { screen: 'yeu-cau-doi-lich', zone: 'Danh sách yêu cầu', tier: 1, mo: 'tai-cho' }],
    'F-50': { screen: 'yeu-cau-doi-lich', zone: 'Danh sách yêu cầu', tier: 4, mo: 'hop-thoai' },
    'F-52': { screen: 'lich-tuan', tab: 'Theo HLV', tier: 4, mo: 'ngan-truot' },
    'F-53': { screen: 'lich-tuan', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    // lop-hoc
    'F-55': { screen: 'lop', zone: 'Thanh công cụ', tier: 3, mo: 'ngan-truot' },
    'F-56': { screen: 'lop', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-57': { screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'tai-cho' },
    'F-58': { screen: 'lop', zone: 'Bảng lớp', tier: 4, mo: 'ngan-truot' },
    'F-59': { screen: 'lop', zone: 'Bảng lớp', tier: 4, mo: 'hop-thoai' },
    'F-60': { screen: 'lop', zone: 'Bảng lớp', tier: 4, mo: 'hop-thoai' },
    'F-61': { screen: 'lop-chi-tiet', tab: 'Danh sách chờ', tier: 4, mo: 'hop-thoai' },
    'F-62': [{ screen: 'lop-chi-tiet', tab: 'Học viên', tier: 1, mo: 'tai-cho' }, { screen: 'lich-tuan', zone: 'Ngăn chi tiết lớp', tier: 2, mo: 'ngan-truot' }],
    'F-63': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 4, mo: 'ngan-truot' },
    'F-64': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 4, mo: 'hop-thoai' },
    'F-65': { screen: 'buoi-hom-nay', zone: 'Điểm danh buổi đang dạy', tier: 4, mo: 'hop-thoai' },
    'F-66': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-67': { screen: 'buoi-hom-nay', zone: 'Điểm danh buổi đang dạy', tier: 4, mo: 'hop-thoai' },
    'F-69': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 4, mo: 'ngan-truot' },
    'F-70': { screen: 'app-lich', tab: 'Đã học', tier: 2, mo: 'tai-cho' },
    // quan-tri
    'F-71': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-72': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-73': { screen: 'bao-cao', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-74': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'trang' },
    'F-76': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-77': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'ngan-truot' },
    'F-78': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-79': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-81': { screen: 'dang-nhap', zone: 'Đổi mật khẩu tạm', tier: 2, mo: 'tai-cho' },
    'F-83': { screen: 'cai-dat', tab: 'Nhật ký thao tác', tier: 3, mo: 'tai-cho' },
    // thong-bao
    'F-84': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-86': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 3, mo: 'tai-cho' },
    'F-87': { screen: 'app-thong-bao', zone: 'Thông báo đã nhận', tier: 1, mo: 'tai-cho' },
    'F-89': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 2, mo: 'tai-cho' },
    'F-90': { screen: 'tong-quan', zone: 'Cần chú ý', tier: 2, mo: 'tai-cho' },
    'F-91': { screen: 'thong-bao', zone: 'Đã gửi và đang hẹn giờ', tier: 2, mo: 'tai-cho' },
    'F-92': { screen: 'thong-bao', zone: 'Đã gửi và đang hẹn giờ', tier: 4, mo: 'hop-thoai' },
  },
  shortcuts: [
    { from: 'quay', to: 'F-32', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-08', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-58', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-66', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-44', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-50', mo: 'hop-thoai' },
    { from: 'quay', to: 'F-09', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-25', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-52', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-53', mo: 'hop-thoai' },
    { from: 'tong-quan', to: 'F-84', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-08', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-16', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-58', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-63', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-44', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-05', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-06', mo: 'ngan-truot' },
    { from: 'lop-chi-tiet', to: 'F-58', mo: 'ngan-truot' },
    { from: 'app-hom-nay', to: 'F-04', mo: 'sheet' },
    { from: 'app-hom-nay', to: 'F-47', mo: 'sheet' },
  ],
  flows: [
    { role: 'le-tan', name: 'Bé mới tới đăng ký học', steps: ['F-32', 'F-58', 'F-08', 'F-09'] },
    { role: 'le-tan', name: 'Phụ huynh xin đổi buổi trên app', steps: ['F-49', 'F-44'] },
    { role: 'le-tan', name: 'Mời gia hạn bé sắp hết buổi', steps: ['F-22', 'F-23', 'F-08'] },
    { role: 'quan-ly', name: 'HLV báo nghỉ đột xuất', steps: ['F-42', 'F-52'] },
    { role: 'quan-ly', name: 'Bể có sự cố', steps: ['F-53', 'F-90'] },
    { role: 'quan-ly', name: 'Cuối tháng xem kết quả', steps: ['F-71', 'F-72', 'F-73'] },
    { role: 'hlv', name: 'Dạy một ca ở bể', steps: ['F-42', 'F-01', 'F-02'] },
    { role: 'hlv', name: 'Bé học thử', steps: ['F-01', 'F-67'] },
    { role: 'phu-huynh', name: 'Bé ốm, báo nghỉ', steps: ['F-37', 'F-43', 'F-04'] },
    { role: 'phu-huynh', name: 'Xem con còn bao nhiêu buổi', steps: ['F-37', 'F-12', 'F-11'] },
    { role: 'phu-huynh', name: 'Xin đổi lịch', steps: ['F-43', 'F-47', 'F-48'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một người mẹ dẫn bé gái 6 tuổi tới quầy, muốn cho bé theo học từ tuần sau.', feature: 'F-32' },
    { role: 'le-tan', say: 'Bố của một bé gọi điện: chiều nay bé sốt, không tới bể được.', feature: 'F-05' },
    { role: 'le-tan', say: 'Một phụ huynh nhắn đã trả tiền gói học qua ngân hàng sáng nay, nhờ quầy kiểm tra giúp.', feature: 'F-09' },
    { role: 'le-tan', say: 'Trên app, một phụ huynh xin cho con học thứ Bảy thay cho thứ Năm tuần này.', feature: 'F-44' },
    { role: 'le-tan', say: 'Hết ca chiều, bạn cần biết hôm nay quầy nhận bao nhiêu tiền mặt để bàn giao cho ca sau.', feature: 'F-10' },
    { role: 'hlv', say: 'Lớp 17 giờ ở làn 3 vừa xuống nước; bạn cần ghi lại bé nào tới, bé nào không.', feature: 'F-01' },
    { role: 'quan-ly', say: 'Một HLV nhắn sáng nay bị ốm, chiều nay người đó có ba lớp.', feature: 'F-52' },
    { role: 'quan-ly', say: 'Chủ trung tâm hỏi tháng 9 trung tâm thu được bao nhiêu tiền.', feature: 'F-72' },
    { role: 'phu-huynh', say: 'Con bạn bị ho, bạn muốn cho trung tâm biết thứ Năm này bé không đi học.', feature: 'F-04' },
    { role: 'phu-huynh', say: 'Bạn muốn biết con còn mấy buổi nữa thì phải đóng tiền tiếp.', feature: 'F-12' },
  ],
};
