window.PART = { features: [], skip: [
  { src: 'D1:6-27', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D1:28-31', why: 'Tóm tắt, không có việc' },
  { src: 'D1:104-107', why: 'Nhận xét của người soạn, không có việc' },
  { src: 'D2:5-19', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D2:20-23', why: 'Tóm tắt, không có việc' },
  { src: 'D2:39-45', why: 'Câu hỏi mở: chép vào notes của chức năng liên quan' },
  { src: 'D3:5-8', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D5:5-8', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D6:7-20', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D6:21-30', why: 'Danh sách actor, không có việc' },
  { src: 'D6:80-98', why: 'Ma trận actor × use case: việc đã ở đặc tả từng use case' },
  { src: 'D7:6-16', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D7:17-20', why: 'Tóm tắt, không có việc' },
  { src: 'D7:42-45', why: 'Nhận xét của người soạn, không có việc' },
  { src: 'D8:6-13', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D9:7-18', why: 'Quy ước ký hiệu, không có việc' },
  { src: 'D9:19-28', why: 'Bối cảnh, không có việc' },
  { src: 'D9:29-35', why: 'Mục tiêu, không có việc' },
  { src: 'D9:36-44', why: 'Bề mặt: dùng khi bố cục, không có việc' },
  { src: 'D9:81-90', why: 'Yêu cầu phi chức năng: ràng buộc, ghi vào spec' },
  { src: 'D9:91-97', why: 'Ngoài phạm vi, không có việc' },
] };
