window.PART = {
  module: 'hoc-vien',
  features: [
    { name: 'Đăng ký học viên mới', src: ['UC-01', 'M-01', 'YC-01', 'BR-HV-01', 'BR-HV-02', 'BR-HV-04', 'D5:11-85'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.dang_hoc'], spec: 'Tìm phụ huynh theo SĐT: có rồi thì hiện các con đang học và gắn bé vào, chưa có thì tạo (họ tên, SĐT duy nhất, quan hệ). Nhập họ tên, ngày sinh, giới tính, ghi chú sức khoẻ (dưới 6 tuổi bỏ trống thì không lưu); sinh mã SX-0001 không đổi, không dùng lại; xong sang bán gói hoặc dừng.', notes: 'dừng ở bước 5, chưa mua gói thì bé ở trạng thái nào: enum D10:19-23 chỉ có học thử, đang học, ngừng học' },
    { name: 'Tìm kiếm và danh sách học viên', src: ['UC-01', 'M-01', 'YC-01', 'D5:87-161'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Tìm theo tên, mã hoặc SĐT phụ huynh, ra kết quả từ ký tự thứ ba, gõ không dấu vẫn ra; lọc theo trạng thái học thử, đang học, ngừng học. Lễ tân, quản lý thấy mọi học viên; HLV chỉ học viên lớp mình (D6:105).' },
    { name: 'Xem hồ sơ học viên', src: ['UC-01', 'M-01', 'D6:105', 'D5:163-237'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien'], spec: 'Trang chi tiết: thông tin bé, ghi chú sức khoẻ, phụ huynh và anh chị em, gói học, lớp đang học, các buổi đã học, cấp độ gợi ý sau học thử, nhãn trạng thái. HLV chỉ mở được học viên lớp mình.', notes: 'OQ-03 chưa chốt: HLV có được xem SĐT phụ huynh của lớp mình không (D2:45)' },
    { name: 'Sửa hồ sơ học viên', src: ['D6:106', 'BR-HV-02', 'BR-HV-04'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sửa thông tin bé và phụ huynh đi kèm; giữ ràng buộc như lúc tạo: SĐT phụ huynh duy nhất, dưới 6 tuổi phải có ghi chú sức khoẻ; mã học viên không sửa được. HLV không sửa.', notes: 'đổi SĐT phụ huynh: SĐT là tài khoản đăng nhập app (D10:14); trùng số của phụ huynh khác thì gộp hay chặn, tài liệu chưa nói' },
    { name: 'Chuyển học viên sang ngừng học', src: ['BR-HV-05', 'D10:19-23'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.ngung_hoc', 'trang_thai_xep_lop.da_roi'], spec: 'Học viên nghỉ hẳn: không xoá hồ sơ, chuyển trạng thái ngừng học, giữ lịch sử gói, buổi học, điểm danh; hồ sơ vẫn tìm và mở được, lọc riêng theo trạng thái.', notes: 'rời lớp đang học (xep_lop về da_roi) suy từ D10:61-65; vai làm lấy theo D6:106' },
    { name: 'Chọn con đang xem trên app', src: ['BR-HV-03', 'D5:239-313'], roles: ['phu-huynh'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh có nhiều con chọn một bé để xem; lịch, số buổi, đóng tiền, thông báo hiện theo bé đang chọn, không trộn lịch các con; mỗi con lịch và gói riêng.' },
  ],
  skip: [],
};
