window.PART = {
  module: 'lop',
  features: [
    { name: 'Quản lý khoá học', src: ['UC-03', 'M-02', 'YC-02', 'BR-LH-01', 'BR-LH-05', 'XD-03', 'D5:317-391'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tạo hoặc chọn khoá: tên, cấp độ (Làm quen nước, Cơ bản, Nâng cao), số buổi một tuần, sĩ số tối đa: Làm quen nước 6 bé theo XD-03, các cấp khác 10 bé.', notes: 'mâu thuẫn: D5:361 «Chỉ lễ tân … mới thấy nút của "quản lý khoá học"» với D6:107 «Tạo khoá học, mở lớp: Lễ tân —»' },
    { name: 'Mở lớp', src: ['UC-03', 'M-02', 'YC-02', 'BR-LH-02', 'D5:393-467'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Chọn khoá, HLV chính, các ngày trong tuần, giờ bắt đầu (buổi 45 phút), bể và làn. Trùng HLV hoặc làn với lớp khác thì chỉ ra lớp bị trùng để đổi giờ, đổi làn. Lưu xong hệ thống sinh buổi học của lớp (module lich), HLV thấy lớp trong lịch dạy.', notes: 'mâu thuẫn: D5:399 «Chỉ lễ tân … mới thấy nút của "mở lớp"» với D6:107 «Tạo khoá học, mở lớp: Lễ tân —»' },
    { name: 'Xem danh sách lớp và chỗ trống', src: ['UC-04', 'M-02', 'YC-03', 'BR-LH-05', 'D6:209', 'D5:469-543'], roles: ['le-tan', 'quan-ly', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Lọc lớp theo cấp độ, ngày, giờ; mỗi lớp hiện HLV, khung giờ, bể và làn, sĩ số hiện tại, số chỗ trống, số bé đang chờ; mở lớp thấy học viên đang học. HLV chỉ thấy lớp mình.' },
    { name: 'Xếp học viên vào lớp', src: ['UC-04', 'M-02', 'YC-03', 'BR-LH-03', 'BR-LH-04', 'BR-HV-04', 'A-01', 'A-06', 'D5:545-619'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop.dang_hoc', 'trang_thai_xep_lop.cho_cho'], spec: 'Bé có gói còn buổi, dưới 6 tuổi phải có ghi chú sức khoẻ; chọn lớp đúng cấp độ còn chỗ, hệ thống sinh buổi học của bé đến hết gói. Lớp đủ thì vào danh sách chờ; hai người giành chỗ cuối thì người lưu sau được báo, gợi ý danh sách chờ; anh chị em trùng giờ thì cảnh báo, phụ huynh đồng ý vẫn lưu.' },
    { name: 'Cho phép xếp học viên xuống một bậc', src: ['BR-LH-03'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Lớp thấp hơn cấp độ của bé một bậc chỉ xếp được khi quản lý cho phép; lễ tân xếp thì cần quản lý duyệt; thấp hơn hai bậc hay cao hơn cấp độ thì chặn.' },
    { name: 'Danh sách chờ của lớp', src: ['BR-LH-04', 'M-02', 'D6:188', 'D10:61-74', 'D5:621-695'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_xep_lop', 'trang_thai_xep_lop.dang_hoc'], spec: 'Lớp có chỗ trống thì lễ tân thấy danh sách chờ theo thứ tự đăng ký để gọi phụ huynh, ai đăng ký trước gọi trước; phụ huynh nhận thì xếp vào lớp. Quản lý xem số bé chờ theo cấp độ để quyết định mở lớp.', notes: 'phụ huynh từ chối chỗ hay xin rút khỏi danh sách chờ thì xử lý sao (xuống cuối hay rời): tài liệu chưa nói' },
    { name: 'Đặt buổi học thử', src: ['BR-LH-06', 'YC-05', 'S-03', 'D10:19-23', 'D5:697-771'], roles: ['le-tan', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hoc_vien.hoc_thu'], spec: 'Mỗi bé một buổi miễn phí ở lớp còn chỗ, đúng độ tuổi; tạo hồ sơ trạng thái học thử, bé đã học thử thì không đặt lần hai. Mua gói (module goi-hoc) thì thành học viên đang học, giữ kết quả học thử.' },
    { name: 'Ghi cấp độ gợi ý sau buổi học thử', src: ['BR-LH-06', 'D10:33'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Sau buổi học thử, HLV ghi cấp độ gợi ý cho bé (Làm quen nước, Cơ bản, Nâng cao); lễ tân thấy ở hồ sơ để tư vấn và xếp lớp khi phụ huynh mua gói.' },
    { name: 'Dọn hồ sơ học thử quá 60 ngày', src: ['BR-LH-06'], roles: [], freq: 'ngay', evidence: 'suy', status: 'pham-vi', spec: 'Bé học thử mà không mua gói thì hồ sơ học thử chỉ giữ 60 ngày; hệ thống tự xử lý hồ sơ quá hạn mỗi ngày.', notes: 'hết 60 ngày thì xoá hẳn hay chỉ ẩn khỏi danh sách: tài liệu chưa nói' },
    { name: 'Ghi nhận xét tiến bộ cuối cấp độ', src: ['S-04', 'D3:1539-1613'], roles: ['hlv'], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'Cuối mỗi cấp độ, HLV ghi nhận xét kỹ năng của từng bé theo một mẫu chung; giai đoạn 2 vì HLV chưa thống nhất mẫu nhận xét.', notes: 'mâu thuẫn: D3:1541 «Vai liên quan: lễ tân, quản lý» với D7:37 «HLV ghi nhận xét kỹ năng cuối mỗi cấp độ, phụ huynh xem trên app»' },
    { name: 'Xem đánh giá tiến bộ của con', src: ['S-04', 'D3:1539-1613'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'hoan', spec: 'Phụ huynh xem trên app nhận xét kỹ năng cuối mỗi cấp độ của bé đang chọn; giai đoạn 2.' },
  ],
  skip: [],
};
