window.PART = {
  module: 'quan-tri',
  features: [
    { name: 'Thêm nhân viên', src: ['UC-12', 'M-08', 'YC-14', 'BR-QT-01', 'D6:118', 'D3:1233-1307', 'D10:239-245'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhập họ tên, số điện thoại (không trùng), vai: Quản lý, Lễ tân hay HLV; HLV thì gán tiếp lớp phụ trách. Hệ thống gửi mật khẩu tạm qua SMS cho nhân viên. Phụ huynh không có tài khoản web.', notes: 'câu hỏi: D3:1305 «bỏ trống quyền ... tô đỏ ô quyền» mà D10:239-245 nhan_vien chỉ có vai_tro: phân quyền chỉ là chọn vai theo ma trận D6:103-118, hay chỉnh từng quyền?' },
    { name: 'Gán lớp phụ trách cho HLV', src: ['UC-12', 'BR-QT-02', 'M-08'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Chọn các lớp HLV phụ trách (mỗi HLV 3–6 lớp); HLV chỉ thấy các lớp này và học viên của các lớp đó.', notes: 'câu hỏi: UC-12 bước 2 gán lớp ở tài khoản HLV, mà mở lớp (UC-03, module lop) cũng báo kết quả cho HLV (D6:88): chọn HLV ở mở lớp, ở đây, hay cả hai?' },
    { name: 'Xem danh sách nhân viên', src: ['UC-12', 'D3:1233-1307'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Danh sách nhân viên: họ tên, số điện thoại, vai, lớp phụ trách (HLV), đang hoạt động hay bị khoá; lọc theo vai và trạng thái khoá.' },
    { name: 'Sửa thông tin nhân viên', src: ['UC-12', 'D3:1245'], roles: ['quan-ly'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Sửa họ tên, số điện thoại (không trùng), đổi vai của nhân viên; giá trị cũ được giữ để đối chiếu.' },
    { name: 'Khoá tài khoản nhân viên', src: ['UC-12', 'D6:411', 'D10:244'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Nhân viên nghỉ việc thì quản lý khoá tài khoản, không xoá, để giữ lịch sử; tài khoản khoá không đăng nhập được.' },
    { name: 'Mở khoá tài khoản nhân viên', src: ['UC-12', 'BR-QT-05', 'D6:412', 'D10:244'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tài khoản bị hệ thống khoá sau 5 lần nhập sai mật khẩu liền thì quản lý mở khoá để nhân viên đăng nhập lại.' },
    { name: 'Đăng nhập web quản trị', src: ['BR-QT-01', 'BR-QT-05', 'UC-12'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Quản lý, lễ tân, HLV đăng nhập bằng số điện thoại và mật khẩu, vào đúng phần việc của vai (HLV chỉ lớp mình). Nhập sai 5 lần liền thì hệ thống khoá tài khoản (BR-QT-05, TC I).' },
    { name: 'Đổi mật khẩu', src: ['UC-12', 'BR-QT-05'], roles: ['quan-ly', 'le-tan', 'hlv'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Lần đầu đăng nhập bằng mật khẩu tạm nhận qua SMS thì đặt mật khẩu mới, tối thiểu 8 ký tự; về sau đổi lại được.' },
    { name: 'Xem nhật ký thao tác', src: ['BR-QT-04', 'M-08', 'D3:1309-1383', 'D10:247-255'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Tra cứu khi có khiếu nại: ai làm, lúc nào, giá trị trước và sau của mỗi lần sửa điểm danh, duyệt hoàn tiền, tạm dừng gói, xoá học viên khỏi lớp (hệ thống tự ghi); lọc theo người, ngày, đối tượng.', notes: 'mâu thuẫn: D1:101 «Quản lý tra cứu được» với D3:1311 «Vai liên quan: quản lý, lễ tân» và D3:1335 «Chỉ lễ tân ... mới thấy nút»: lễ tân có xem nhật ký không?' },
    { name: 'Đăng nhập app bằng số điện thoại và OTP', src: ['NF-05', 'UC-06', 'D3:1385-1460'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Phụ huynh nhập số điện thoại, nhận mã OTP và nhập mã để vào app phụ huynh.', notes: 'mâu thuẫn: D3:1387 «Vai liên quan: quản lý, lễ tân» với D1:98 «Phụ huynh chỉ dùng app»; tạm ghi vai phụ huynh' },
  ],
  skip: [],
};
