window.PART = {
  module: 'thong-bao',
  features: [
    { name: 'Gửi thông báo cho phụ huynh', src: ['UC-10', 'M-09', 'YC-12', 'BR-TB-01', 'BR-TB-03', 'D6:114', 'D3:697-771'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Chọn người nhận (cả trung tâm, theo lớp, theo cấp độ, chọn nhiều phụ huynh), soạn tiêu đề và nội dung, gửi ngay hay hẹn giờ trong khung 7:00–21:00; đánh dấu khẩn thì gửi ngay, bỏ qua khung giờ. HLV không gửi được.' },
    { name: 'Xem thông báo đã gửi', src: ['UC-10', 'D10:209-222'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'suy', status: 'pham-vi', spec: 'Danh sách thông báo đã gửi và đang hẹn giờ: tiêu đề, người gửi, nhóm nhận, giờ gửi, cờ khẩn, số phụ huynh đã đọc; huỷ thông báo hẹn giờ chưa tới giờ gửi.' },
    { name: 'Xem thông báo trên app', src: ['UC-10', 'D6:356', 'D3:773-847', 'D10:218-222'], roles: ['phu-huynh'], freq: 'tuan', evidence: 'ro', status: 'pham-vi', spec: 'Mục Thông báo của app: thông báo nhận được, mới nhất trước, chưa đọc thì nổi bật; mở xem đủ nội dung thì đánh dấu đã đọc. Gồm thông báo của trung tâm, tin nhắc lịch và thông báo khẩn.' },
    { name: 'Bật, tắt nhận thông báo', src: ['BR-TB-04'], roles: ['phu-huynh'], freq: 'hiem', evidence: 'suy', status: 'pham-vi', spec: 'Phụ huynh tắt hay bật nhận thông báo thường trên app; thông báo khẩn (huỷ buổi) luôn được gửi, không tắt được.', notes: 'câu hỏi: suy từ D1:92 «Phụ huynh không tắt được thông báo khẩn» (TC I); tắt được loại nào (nhắc lịch, thông báo chung) chưa rõ' },
    { name: 'Cấu hình nhắc lịch tự động', src: ['BR-TB-02', 'M-09', 'D3:849-923', 'D10:224-229'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi', spec: 'Bật hay tắt việc tự nhắc lịch cho phụ huynh và sửa nội dung mẫu của tin nhắc; mặc định nhắc trước giờ học 2 tiếng.', notes: 'mâu thuẫn: D1:90 «Quản lý bật hoặc tắt việc nhắc» với D3:869 «Chỉ lễ tân ... mới thấy nút»; câu hỏi: D10:227 có truoc_phut (mặc định 120) mà D1:90 chỉ nói bật, tắt, sửa mẫu: có cho đổi số phút nhắc không?' },
    { name: 'Gửi nhắc lịch trước giờ học', src: ['BR-TB-02', 'D6:29', 'M-09'], roles: [], freq: 'ngay', evidence: 'ro', status: 'pham-vi', spec: 'Khi việc nhắc đang bật, hệ thống gửi tin nhắc theo mẫu cho phụ huynh của từng buổi học, trước giờ học 2 tiếng; tin nằm trong mục Thông báo của app.', notes: 'câu hỏi: D1:89 «hẹn giờ chỉ gửi trong khung 7:00–21:00» mà buổi trước 9:00 có giờ nhắc trước 7:00: gửi lúc 7:00, tối hôm trước, hay bỏ nhắc?' },
    { name: 'Gửi SMS cho phụ huynh chưa cài app', src: ['CO-02', 'D3:925-999'], roles: ['quan-ly', 'le-tan'], freq: 'tuan', evidence: 'ro', status: 'hoan', spec: 'Gửi thông báo qua SMS cho phụ huynh chưa cài app (khoảng 15 %, phần lớn lớn tuổi), cùng cách chọn nhóm nhận như thông báo trên app. GĐ2.' },
  ],
  skip: [],
};
