// Ví dụ features.js cho test và cho người đọc khuôn: phòng khám nha hư cấu "Nha khoa Mộc", 2 bề mặt, 4 vai.
// Không phải đề đo: đề đo r7-map là một trung tâm bơi, không chép gì từ đây sang đó.
window.FEATURES = {
  project: 'Nha khoa Mộc',
  features: [
    { id: 'F-01', name: 'Đặt lịch hẹn', module: 'lich-hen', src: ['UC-01'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Chọn bệnh nhân, dịch vụ, bác sĩ, ghế và giờ; ghế đã có hẹn thì không chọn được. Gửi tin nhắc qua app.' },
    { id: 'F-02', name: 'Xem lịch hẹn theo ngày và ghế', module: 'lich-hen', src: ['UC-02'], roles: ['le-tan', 'bac-si', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hen'],
      spec: 'Lưới ghế × giờ của một ngày, đổi ngày; bác sĩ chỉ thấy lịch của mình.' },
    { id: 'F-03', name: 'Dời lịch hẹn', module: 'lich-hen', src: ['UC-03'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Chọn giờ mới còn trống, giữ dịch vụ và bác sĩ; báo bệnh nhân qua app.' },
    { id: 'F-04', name: 'Huỷ lịch hẹn', module: 'lich-hen', src: ['UC-03', 'BR-LH-02'], roles: ['le-tan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi',
      spec: 'Ghi lý do; huỷ trước 2 giờ không tính lỡ hẹn.' },
    { id: 'F-05', name: 'Tiếp nhận bệnh nhân đến khám', module: 'lich-hen', src: ['UC-04'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi', states: ['trang_thai_hen.da_toi'],
      spec: 'Đánh dấu đã tới; bệnh nhân vào hàng chờ của bác sĩ.' },
    { id: 'F-06', name: 'Thêm bệnh nhân mới', module: 'benh-nhan', src: ['UC-05'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Họ tên, ngày sinh, số điện thoại, tiền sử dị ứng; trùng số điện thoại thì gợi ý hồ sơ cũ.' },
    { id: 'F-07', name: 'Tìm bệnh nhân', module: 'benh-nhan', src: ['UC-05'], roles: ['le-tan', 'bac-si', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Theo tên, số điện thoại, mã hồ sơ; ra kết quả từ ký tự thứ ba.' },
    { id: 'F-08', name: 'Hồ sơ bệnh nhân', module: 'benh-nhan', src: ['UC-06'], roles: ['le-tan', 'bac-si', 'quan-ly'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Thông tin, dị ứng nổi rõ, lịch sử khám, kế hoạch điều trị, thanh toán.' },
    { id: 'F-09', name: 'Ghi phiếu khám', module: 'kham', src: ['UC-07'], roles: ['bac-si'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Sơ đồ răng, chẩn đoán, thủ thuật đã làm; lưu xong tính phí theo bảng giá.' },
    { id: 'F-10', name: 'Lập kế hoạch điều trị', module: 'kham', src: ['UC-08'], roles: ['bac-si'], freq: 'tuan', evidence: 'ro', status: 'pham-vi',
      spec: 'Nhiều buổi, mỗi buổi một thủ thuật; đặt hẹn cho buổi kế tiếp.' },
    { id: 'F-11', name: 'Kê đơn thuốc', module: 'kham', src: ['UC-07'], roles: ['bac-si'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Chọn thuốc, liều, số ngày; cảnh báo khi trùng dị ứng đã ghi.' },
    { id: 'F-12', name: 'Thu tiền và in hoá đơn', module: 'thu-tien', src: ['UC-09'], roles: ['le-tan'], freq: 'ngay', evidence: 'ro', status: 'pham-vi',
      spec: 'Các thủ thuật chưa thu, tiền mặt hay chuyển khoản, in hoá đơn; bấm hai lần chỉ ghi một khoản.' },
    { id: 'F-13', name: 'Hoàn tiền', module: 'thu-tien', src: ['BR-TT-04'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Chỉ quản lý; bắt ghi lý do; ghi nhật ký.' },
    { id: 'F-14', name: 'Xem công nợ của bệnh nhân', module: 'thu-tien', src: ['BR-TT-02'], roles: ['le-tan', 'quan-ly'], freq: 'tuan', evidence: 'suy', status: 'pham-vi',
      spec: 'Quy tắc cho trả góp kế hoạch điều trị, nên cần chỗ xem số còn nợ.' },
    { id: 'F-15', name: 'Báo cáo doanh thu', module: 'bao-cao', src: ['UC-10'], roles: ['quan-ly'], freq: 'tuan', evidence: 'ro', status: 'pham-vi',
      spec: 'Theo ngày, tuần, tháng; theo bác sĩ và dịch vụ.' },
    { id: 'F-16', name: 'Xuất báo cáo ra Excel', module: 'bao-cao', src: ['UC-10'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Xuất đúng kỳ và bộ lọc đang xem.' },
    { id: 'F-17', name: 'Quản lý tài khoản nhân viên', module: 'quan-tri', src: ['UC-11'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Thêm, khoá, đổi vai; không xoá.' },
    { id: 'F-18', name: 'Sửa bảng giá dịch vụ', module: 'quan-tri', src: ['UC-11'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Giá mới áp từ ngày chọn; giữ lịch sử giá.' },
    { id: 'F-19', name: 'Cài nhắc hẹn tự động', module: 'quan-tri', src: ['BR-LH-05'], roles: ['quan-ly'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Bật tắt, nhắc trước bao nhiêu giờ, mẫu tin.' },
    { id: 'F-20', name: 'Đặt lịch hẹn trên app', module: 'lich-hen', src: ['UC-12'], roles: ['benh-nhan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi',
      spec: 'Chọn dịch vụ, ngày, khung giờ còn trống; lễ tân xác nhận.' },
    { id: 'F-21', name: 'Xem lịch hẹn của tôi', module: 'lich-hen', src: ['UC-12'], roles: ['benh-nhan'], freq: 'tuan', evidence: 'ro', status: 'pham-vi',
      spec: 'Hẹn sắp tới nổi đầu; hẹn đã qua.' },
    { id: 'F-22', name: 'Xem hoá đơn', module: 'thu-tien', src: ['UC-13'], roles: ['benh-nhan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Danh sách hoá đơn, mở một hoá đơn.' },
    { id: 'F-23', name: 'Đánh giá sau buổi khám', module: 'kham', src: ['UC-14'], roles: ['benh-nhan'], freq: 'hiem', evidence: 'ro', status: 'hoan',
      spec: 'Chấm 1–5 sao, góp ý; giai đoạn sau.' },
    { id: 'F-24', name: 'Tích điểm thành viên', module: 'thu-tien', src: ['UC-15'], roles: ['le-tan', 'benh-nhan'], freq: 'tuan', evidence: 'ro', status: 'hoan',
      spec: 'Mỗi 100.000 ₫ một điểm; giai đoạn sau.' },
    { id: 'F-25', name: 'Đăng nhập app bằng số điện thoại', module: 'quan-tri', src: ['UC-12'], roles: ['benh-nhan'], freq: 'hiem', evidence: 'ro', status: 'pham-vi',
      spec: 'Số điện thoại và mã OTP 6 số; gửi lại sau 60 giây.' },
  ],
  skip: [
    { src: 'D1:2-5', why: 'Giới thiệu chung về phòng khám, không có việc' },
  ],
};
