// Ví dụ layout.js đi cùng features.example.js (phòng khám nha hư cấu). map.mjs check trên cặp này sạch: test giữ như vậy.
window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web phòng khám', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App bệnh nhân', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'hom-nay' },
    { id: 'bac-si', name: 'Bác sĩ', surface: 'web', home: 'ca-kham' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'benh-nhan', name: 'Bệnh nhân', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'benh-nhan', name: 'Bệnh nhân', depends: [] },
    { id: 'lich-hen', name: 'Lịch hẹn', depends: ['benh-nhan'] },
    { id: 'kham', name: 'Khám', depends: ['benh-nhan', 'lich-hen'] },
    { id: 'thu-tien', name: 'Thu tiền', depends: ['benh-nhan'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['thu-tien', 'lich-hen'] },
    { id: 'quan-tri', name: 'Quản trị', depends: [] },
  ],
  screens: [
    { id: 'hom-nay', name: 'Hôm nay', surface: 'web', module: 'lich-hen', roles: ['le-tan'],
      bands: [{ name: 'Bệnh nhân sắp tới', items: ['F-05'] }, { name: 'Việc nhanh', items: ['F-01', 'F-06', 'F-12'] }] },
    { id: 'ca-kham', name: 'Ca khám hôm nay', surface: 'web', module: 'kham', roles: ['bac-si'],
      bands: [{ name: 'Bệnh nhân chờ khám', items: ['F-09'] }] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      bands: [{ name: 'Doanh thu hôm nay', items: ['F-15'] }, { name: 'Cần duyệt', items: ['F-13'] }] },
    { id: 'lich', name: 'Lịch hẹn', surface: 'web', module: 'lich-hen', roles: ['le-tan', 'bac-si', 'quan-ly'],
      zones: ['Thanh công cụ', 'Lưới ghế và giờ', 'Ngăn chi tiết hẹn'] },
    { id: 'benh-nhan', name: 'Bệnh nhân', surface: 'web', module: 'benh-nhan', roles: ['le-tan', 'bac-si', 'quan-ly'],
      zones: ['Tìm và lọc', 'Bảng bệnh nhân'] },
    { id: 'ho-so', name: 'Hồ sơ bệnh nhân', surface: 'web', module: 'benh-nhan', roles: ['le-tan', 'bac-si', 'quan-ly'],
      parent: 'benh-nhan', pick: true, zones: ['Đầu hồ sơ'], tabs: ['Lịch sử khám', 'Kế hoạch điều trị', 'Thanh toán'] },
    { id: 'phieu-kham', name: 'Phiếu khám', surface: 'web', module: 'kham', roles: ['bac-si'], parent: 'ho-so',
      zones: ['Sơ đồ răng', 'Chẩn đoán và thủ thuật', 'Thanh dưới'] },
    { id: 'thu-tien', name: 'Thu tiền', surface: 'web', module: 'thu-tien', roles: ['le-tan', 'quan-ly'],
      zones: ['Chờ thu', 'Đã thu hôm nay'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['quan-ly'], zones: ['Kỳ và bộ lọc', 'Biểu đồ và bảng'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Nhân viên', 'Bảng giá', 'Nhắc hẹn'] },
    { id: 'app-lich', name: 'Lịch hẹn', surface: 'app', module: 'lich-hen', roles: ['benh-nhan'], zones: ['Hẹn sắp tới', 'Hẹn đã qua'],
      bands: [{ name: 'Hẹn của tôi', items: ['F-21', 'F-20'] }] },
    { id: 'app-hoa-don', name: 'Hoá đơn', surface: 'app', module: 'thu-tien', roles: ['benh-nhan'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'quan-tri', roles: ['benh-nhan'] },
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'quan-tri', roles: ['benh-nhan'], entry: true },
  ],
  nav: [
    { roles: ['le-tan'], groups: [{ name: '', items: ['hom-nay', 'lich', 'benh-nhan', 'thu-tien'] }] },
    { roles: ['bac-si'], groups: [{ name: '', items: ['ca-kham', 'lich', 'benh-nhan'] }] },
    { roles: ['quan-ly'], groups: [{ name: '', items: ['tong-quan', 'lich', 'benh-nhan', 'thu-tien', 'bao-cao', 'cai-dat'] }] },
    { roles: ['benh-nhan'], groups: [{ name: '', items: ['app-lich', 'app-hoa-don', 'app-tai-khoan'] }] },
  ],
  place: {
    'F-01': { screen: 'lich', zone: 'Thanh công cụ', tier: 1, mo: 'hop-thoai' },
    'F-02': { screen: 'lich', zone: 'Lưới ghế và giờ', tier: 2, mo: 'trang' },
    'F-03': { screen: 'lich', zone: 'Ngăn chi tiết hẹn', tier: 4, mo: 'ngan-truot' },
    'F-04': { screen: 'lich', zone: 'Ngăn chi tiết hẹn', tier: 4, mo: 'hop-thoai' },
    'F-05': { screen: 'hom-nay', zone: 'Bệnh nhân sắp tới', tier: 1, mo: 'tai-cho' },
    'F-06': { screen: 'benh-nhan', zone: 'Tìm và lọc', tier: 1, mo: 'ngan-truot' },
    'F-07': { screen: 'benh-nhan', zone: 'Tìm và lọc', tier: 2, mo: 'tai-cho' },
    'F-08': { screen: 'ho-so', tier: 2, mo: 'trang' },
    'F-09': { screen: 'phieu-kham', tier: 1, mo: 'trang' },
    'F-10': { screen: 'ho-so', tab: 'Kế hoạch điều trị', tier: 2, mo: 'ngan-truot' },
    'F-11': { screen: 'phieu-kham', zone: 'Chẩn đoán và thủ thuật', tier: 2, mo: 'hop-thoai' },
    'F-12': { screen: 'thu-tien', zone: 'Chờ thu', tier: 1, mo: 'ngan-truot' },
    'F-13': { screen: 'thu-tien', zone: 'Đã thu hôm nay', tier: 3, mo: 'hop-thoai' },
    'F-14': { screen: 'ho-so', tab: 'Thanh toán', tier: 2, mo: 'tai-cho' },
    'F-15': [
      { screen: 'bao-cao', zone: 'Biểu đồ và bảng', tier: 2, mo: 'trang' },
      { screen: 'tong-quan', zone: 'Doanh thu hôm nay', tier: 2, mo: 'tai-cho' },
    ],
    'F-16': { screen: 'bao-cao', zone: 'Kỳ và bộ lọc', tier: 3, mo: 'hop-thoai' },
    'F-17': { screen: 'cai-dat', tab: 'Nhân viên', tier: 3, mo: 'tai-cho' },
    'F-18': { screen: 'cai-dat', tab: 'Bảng giá', tier: 3, mo: 'tai-cho' },
    'F-19': { screen: 'cai-dat', tab: 'Nhắc hẹn', tier: 3, mo: 'tai-cho' },
    'F-20': { screen: 'app-lich', zone: 'Hẹn sắp tới', tier: 1, mo: 'sheet' },
    'F-21': { screen: 'app-lich', zone: 'Hẹn sắp tới', tier: 2, mo: 'trang' },
    'F-22': { screen: 'app-hoa-don', tier: 2, mo: 'trang' },
    'F-23': { screen: 'app-lich', zone: 'Hẹn đã qua', tier: 4, mo: 'sheet' },
    'F-24': [
      { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'tai-cho' },
      { screen: 'app-tai-khoan', tier: 2, mo: 'tai-cho' },
    ],
    'F-25': { screen: 'app-dang-nhap', tier: 1, mo: 'trang' },
  },
  shortcuts: [
    { from: 'hom-nay', to: 'F-01', mo: 'hop-thoai' },
    { from: 'hom-nay', to: 'F-06', mo: 'ngan-truot' },
    { from: 'hom-nay', to: 'F-12', mo: 'ngan-truot' },
    { from: 'ca-kham', to: 'F-09', mo: 'trang', ve: 'Lưu phiếu xong thì về Ca khám hôm nay, báo đã lưu; có nút Quay lại' },
    { from: 'tong-quan', to: 'F-13', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-01', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-12', mo: 'ngan-truot' },
    { from: 'phieu-kham', to: 'F-01', mo: 'hop-thoai' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới tới khám lần đầu', steps: ['F-06', 'F-01', 'F-05', 'F-12'] },
    { role: 'bac-si', name: 'Khám một bệnh nhân', steps: ['F-08', 'F-09', 'F-11', 'F-10'] },
    { role: 'quan-ly', name: 'Xem doanh thu cuối tháng', steps: ['F-15', 'F-16'] },
    { role: 'benh-nhan', name: 'Đặt hẹn qua app', steps: ['F-25', 'F-20', 'F-21'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một bệnh nhân gọi xin hẹn khám răng chiều thứ Sáu.', feature: 'F-01' },
    { role: 'le-tan', say: 'Bệnh nhân hẹn 9 giờ vừa tới quầy.', feature: 'F-05' },
    { role: 'le-tan', say: 'Bệnh nhân khám xong ra quầy trả tiền.', feature: 'F-12' },
    { role: 'le-tan', say: 'Bệnh nhân gọi báo bận, xin dời buổi hẹn sang tuần sau.', feature: 'F-03' },
    { role: 'bac-si', say: 'Bệnh nhân tiếp theo đã vào ghế; bạn ghi kết quả khám.', feature: 'F-09' },
    { role: 'bac-si', say: 'Bạn kê thuốc giảm đau cho bệnh nhân vừa nhổ răng.', feature: 'F-11' },
    { role: 'quan-ly', say: 'Cuối tuần bạn muốn xem doanh thu tuần này.', feature: 'F-15' },
    { role: 'benh-nhan', say: 'Bạn muốn đặt lịch cạo vôi răng tuần sau.', feature: 'F-20' },
  ],
};
