// Bố cục (M2) · Sóng Xanh. Kiểm: map.mjs check <thư-mục-prototype> --shots
window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'quay' },
    { id: 'hlv', name: 'HLV', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'tai-khoan', name: 'Tài khoản và quyền', depends: [] },
    { id: 'lop', name: 'Khoá học và lớp', depends: ['hoc-vien', 'tai-khoan'] },
    { id: 'lich', name: 'Lịch và buổi học', depends: ['lop'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien', 'lop', 'lich'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['hoc-vien', 'lich'] },
    { id: 'hoc-thu', name: 'Học thử', depends: ['lop', 'lich', 'diem-danh'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
    { id: 'danh-gia', name: 'Đánh giá tiến bộ', depends: ['hoc-vien', 'lop'] },
  ],
  screens: [
    // Web quản trị
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'tai-khoan', roles: ['quan-ly', 'le-tan', 'hlv'], entry: true, zones: ['Đăng nhập'] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      bands: [{ name: 'Cần quản lý xử lý', items: ['F-53', 'F-39'] }, { name: 'Lịch hôm nay', items: ['F-23'] }, { name: 'Tháng này', items: ['F-58', 'F-57'] }] },
    { id: 'quay', name: 'Quầy hôm nay', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly'],
      bands: [{ name: 'Tìm học viên', items: ['F-01'] }, { name: 'Việc nhanh', items: ['F-02', 'F-33', 'F-18', 'F-31'] }, { name: 'Cần xử lý hôm nay', items: ['F-20', 'F-34', 'F-12', 'F-37'] }, { name: 'Cuối ca', items: ['F-42'] }] },
    { id: 'lich', name: 'Lịch tuần', surface: 'web', module: 'lich', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ', 'Lưới làn × giờ', 'Ngăn lớp'] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Lịch học', 'Gói và đóng tiền'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Lọc', 'Bảng lớp'] },
    { id: 'lop-chi-tiet', name: 'Chi tiết lớp', surface: 'web', module: 'lop', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'lop', pick: true,
      zones: ['Đầu lớp'], tabs: ['Học viên', 'Danh sách chờ'] },
    { id: 'goi-hoc', name: 'Gói học', surface: 'web', module: 'goi-hoc', roles: ['quan-ly', 'le-tan'], zones: ['Lọc theo trạng thái'], tabs: ['Gói học', 'Hoàn tiền', 'Khuyến mãi'] },
    { id: 'hoc-thu', name: 'Học thử', surface: 'web', module: 'hoc-thu', roles: ['le-tan'], zones: ['Thanh công cụ', 'Bảng khách học thử'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ', 'Thông báo đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['quan-ly', 'le-tan'], zones: ['Thanh công cụ'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhan-vien', name: 'Nhân viên', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], zones: ['Thanh công cụ', 'Bảng nhân viên'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], zones: ['Lọc', 'Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'tai-khoan', roles: ['quan-ly'], tabs: ['Khoá học', 'Bảng giá', 'Ngày nghỉ lễ', 'Nhắc lịch'] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'lich', roles: ['hlv'],
      bands: [{ name: 'Buổi dạy trong ngày', items: ['F-17'] }, { name: 'Lớp của tôi', items: ['F-09'] }] },
    { id: 'diem-danh', name: 'Điểm danh buổi', surface: 'web', module: 'diem-danh', roles: ['hlv', 'quan-ly'], parent: 'buoi-day', pick: true,
      zones: ['Đầu buổi', 'Danh sách học viên'] },
    // App phụ huynh
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'tai-khoan', roles: ['phu-huynh'], entry: true, zones: ['Đăng nhập'] },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'lich', roles: ['phu-huynh'],
      bands: [{ name: 'Con đang xem', items: ['F-06'] }, { name: 'Buổi sắp tới', items: ['F-26', 'F-30', 'F-21'] }, { name: 'Đã học', items: ['F-32', 'F-66'] }] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'], zones: ['Gói đang dùng', 'Lịch sử đóng tiền'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'], zones: ['Hộp thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'tai-khoan', roles: ['phu-huynh'], zones: ['Cài đặt thông báo'] },
  ],
  nav: [
    { roles: ['quan-ly'], groups: [
      { name: 'Hôm nay', items: ['tong-quan', 'quay', 'lich'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'goi-hoc'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhan-vien', 'nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['le-tan'], groups: [
      { name: 'Hôm nay', items: ['quay', 'lich'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'goi-hoc', 'hoc-thu'] },
      { name: 'Liên lạc và báo cáo', items: ['thong-bao', 'bao-cao'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'lop', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    'F-01': [{ screen: 'quay', zone: 'Tìm học viên', tier: 1, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }],
    'F-02': { screen: 'hoc-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'tai-cho' },
    'F-04': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 3, mo: 'hop-thoai' },
    'F-06': { screen: 'app-lich', zone: 'Con đang xem', tier: 2, mo: 'tai-cho' },
    'F-07': { screen: 'cai-dat', tab: 'Khoá học', tier: 2, mo: 'ngan-truot' },
    'F-08': { screen: 'lop', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-09': [{ screen: 'lop', zone: 'Bảng lớp', tier: 1, mo: 'tai-cho' }, { screen: 'buoi-day', zone: 'Lớp của tôi', tier: 2, mo: 'tai-cho' }],
    'F-10': [{ screen: 'lop-chi-tiet', zone: 'Đầu lớp', tier: 1, mo: 'ngan-truot' }, { screen: 'lop', zone: 'Bảng lớp', tier: 4, mo: 'ngan-truot' }],
    'F-11': { screen: 'lop-chi-tiet', tab: 'Danh sách chờ', tier: 2, mo: 'hop-thoai' },
    'F-12': [{ screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' }, { screen: 'lop-chi-tiet', tab: 'Danh sách chờ', tier: 4, mo: 'ngan-truot' }],
    'F-13': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 4, mo: 'hop-thoai' },
    'F-14': { screen: 'lop-chi-tiet', tab: 'Học viên', tier: 4, mo: 'ngan-truot' },
    'F-15': { screen: 'diem-danh', zone: 'Danh sách học viên', tier: 4, mo: 'hop-thoai' },
    'F-16': { screen: 'lich', zone: 'Lưới làn × giờ', tier: 1, mo: 'tai-cho' },
    'F-17': { screen: 'buoi-day', zone: 'Buổi dạy trong ngày', tier: 1, mo: 'tai-cho' },
    'F-18': { screen: 'ho-so', tab: 'Lịch học', tier: 4, mo: 'ngan-truot' },
    'F-19': { screen: 'lich', zone: 'Ngăn lớp', tier: 4, mo: 'ngan-truot' },
    'F-20': { screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' },
    'F-21': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-22': { screen: 'lich', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-23': { screen: 'lich', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-24': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 2, mo: 'tai-cho' },
    'F-26': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-27': { screen: 'diem-danh', zone: 'Danh sách học viên', tier: 1, mo: 'tai-cho' },
    'F-28': [{ screen: 'diem-danh', zone: 'Đầu buổi', tier: 2, mo: 'tai-cho' }, { screen: 'lich', zone: 'Ngăn lớp', tier: 4, mo: 'ngan-truot' }],
    'F-30': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 4, mo: 'sheet' },
    'F-31': { screen: 'lich', zone: 'Ngăn lớp', tier: 4, mo: 'hop-thoai' },
    'F-32': { screen: 'app-lich', zone: 'Đã học', tier: 2, mo: 'tai-cho' },
    'F-33': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'ngan-truot' },
    'F-34': [{ screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'tai-cho' }, { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'tai-cho' }],
    'F-35': { screen: 'goi-hoc', zone: 'Lọc theo trạng thái', tier: 1, mo: 'tai-cho' },
    'F-36': { screen: 'ho-so', tab: 'Gói và đóng tiền', tier: 4, mo: 'hop-thoai' },
    'F-37': { screen: 'quay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' },
    'F-38': { screen: 'goi-hoc', tab: 'Gói học', tier: 4, mo: 'hop-thoai' },
    'F-39': [{ screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' }, { screen: 'tong-quan', zone: 'Cần quản lý xử lý', tier: 2, mo: 'hop-thoai' }],
    'F-40': { screen: 'goi-hoc', tab: 'Hoàn tiền', tier: 4, mo: 'hop-thoai' },
    'F-41': { screen: 'cai-dat', tab: 'Bảng giá', tier: 2, mo: 'tai-cho' },
    'F-42': { screen: 'quay', zone: 'Cuối ca', tier: 2, mo: 'ngan-truot' },
    'F-43': { screen: 'app-goi', zone: 'Gói đang dùng', tier: 1, mo: 'tai-cho' },
    'F-44': { screen: 'app-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-45': { screen: 'goi-hoc', tab: 'Khuyến mãi', tier: 2, mo: 'tai-cho' },
    'F-46': { screen: 'hoc-thu', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-47': { screen: 'diem-danh', zone: 'Danh sách học viên', tier: 4, mo: 'hop-thoai' },
    'F-48': { screen: 'hoc-thu', zone: 'Bảng khách học thử', tier: 1, mo: 'tai-cho' },
    'F-49': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 1, mo: 'ngan-truot' },
    'F-50': { screen: 'thong-bao', zone: 'Thông báo đã gửi', tier: 2, mo: 'tai-cho' },
    'F-51': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 2, mo: 'tai-cho' },
    'F-53': { screen: 'tong-quan', zone: 'Cần quản lý xử lý', tier: 1, mo: 'tai-cho' },
    'F-54': { screen: 'app-thong-bao', zone: 'Hộp thông báo', tier: 1, mo: 'tai-cho' },
    'F-55': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 2, mo: 'tai-cho' },
    'F-56': { screen: 'thong-bao', zone: 'Thanh công cụ', tier: 3, mo: 'ngan-truot' },
    'F-57': [{ screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-58': [{ screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }, { screen: 'tong-quan', zone: 'Tháng này', tier: 2, mo: 'tai-cho' }],
    'F-59': { screen: 'bao-cao', zone: 'Thanh công cụ', tier: 2, mo: 'hop-thoai' },
    'F-60': { screen: 'dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-61': { screen: 'app-dang-nhap', zone: 'Đăng nhập', tier: 1, mo: 'tai-cho' },
    'F-62': { screen: 'nhan-vien', zone: 'Thanh công cụ', tier: 2, mo: 'ngan-truot' },
    'F-63': { screen: 'nhan-vien', zone: 'Bảng nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-64': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 1, mo: 'tai-cho' },
    'F-65': { screen: 'diem-danh', zone: 'Danh sách học viên', tier: 4, mo: 'hop-thoai' },
    'F-66': { screen: 'app-lich', zone: 'Đã học', tier: 2, mo: 'tai-cho' },
  },
  shortcuts: [
    { from: 'quay', to: 'F-02', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-33', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-18', mo: 'ngan-truot' },
    { from: 'quay', to: 'F-31', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-10', mo: 'ngan-truot' },
    { from: 'lich', to: 'F-10', mo: 'ngan-truot' },
    { from: 'lich', to: 'F-27', mo: 'trang', ve: 'Lưu điểm danh xong thì về Lịch tuần đúng ô buổi vừa mở, báo đã lưu; nút Quay lại giữ tuần và ô đang chọn' },
    { from: 'goi-hoc', to: 'F-36', mo: 'hop-thoai' },
    { from: 'goi-hoc', to: 'F-37', mo: 'ngan-truot' },
    { from: 'tong-quan', to: 'F-23', mo: 'ngan-truot' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới tới quầy cho con học', steps: ['F-02', 'F-33', 'F-10'] },
    { role: 'le-tan', name: 'Phụ huynh gọi xin dời một buổi', steps: ['F-01', 'F-03', 'F-18'] },
    { role: 'le-tan', name: 'Đầu ca xử lý việc tồn', steps: ['F-20', 'F-34', 'F-37'] },
    { role: 'quan-ly', name: 'Mở lớp đầu đợt', steps: ['F-07', 'F-08', 'F-16'] },
    { role: 'quan-ly', name: 'HLV báo ốm buổi sáng', steps: ['F-16', 'F-23'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số', steps: ['F-58', 'F-57', 'F-59'] },
    { role: 'hlv', name: 'Dạy một buổi ở bể', steps: ['F-17', 'F-27', 'F-47'] },
    { role: 'phu-huynh', name: 'Bé ốm, xin nghỉ buổi chiều', steps: ['F-06', 'F-26', 'F-30'] },
    { role: 'phu-huynh', name: 'Xin đổi sang buổi khác', steps: ['F-26', 'F-21'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Một mẹ dẫn bé 5 tuổi tới quầy lần đầu, muốn cho bé học bơi ở trung tâm.', feature: 'F-02' },
    { role: 'le-tan', say: 'Bố bé Bin vừa trả tiền gói 8 buổi cấp Cơ bản; giờ cần tìm cho bé một lớp chiều thứ Ba, thứ Năm còn chỗ.', feature: 'F-10' },
    { role: 'le-tan', say: 'Mẹ bé Na gọi điện: thứ Tư này bé bận, xin cho bé học hôm thứ Năm thay.', feature: 'F-18' },
    { role: 'le-tan', say: 'Sáng nay ngân hàng báo đã nhận khoản chuyển khoản hôm qua của nhà bé Minh.', feature: 'F-34' },
    { role: 'le-tan', say: 'Đầu ca chiều, có mấy phụ huynh nhờ đổi buổi qua app từ tối qua mà chưa ai trả lời.', feature: 'F-20' },
    { role: 'le-tan', say: 'Rảnh tay đầu giờ chiều, bạn muốn gọi cho các nhà sắp dùng hết buổi để mời mua tiếp.', feature: 'F-37' },
    { role: 'hlv', say: '17:30, lớp của bạn ở làn 3 vừa xuống nước; cần ghi lại bé nào tới, bé nào không.', feature: 'F-27' },
    { role: 'quan-ly', say: 'Bạn muốn biết chiều thứ Bảy làn nào còn trống để mở thêm một lớp cho bé 4–6 tuổi.', feature: 'F-16' },
    { role: 'phu-huynh', say: 'Bé nhà bạn sốt từ sáng, chiều nay không đi bơi được.', feature: 'F-30' },
    { role: 'phu-huynh', say: 'Bạn muốn biết bé còn mấy buổi nữa thì phải đóng tiền gói mới.', feature: 'F-43' },
  ],
};
