window.LAYOUT = {
  surfaces: [
    { id: 'web', name: 'Web quản trị', kind: 'web', dir: 'admin', ctrlK: true },
    { id: 'app', name: 'App phụ huynh', kind: 'app', dir: 'app' },
  ],
  roles: [
    { id: 'le-tan', name: 'Lễ tân', surface: 'web', home: 'hom-nay' },
    { id: 'quan-ly', name: 'Quản lý', surface: 'web', home: 'tong-quan' },
    { id: 'hlv', name: 'Huấn luyện viên', surface: 'web', home: 'buoi-day' },
    { id: 'phu-huynh', name: 'Phụ huynh', surface: 'app', home: 'app-lich' },
  ],
  modules: [
    { id: 'hoc-vien', name: 'Học viên', depends: [] },
    { id: 'lop-hoc', name: 'Khoá học và lớp', depends: ['hoc-vien'] },
    { id: 'goi-hoc', name: 'Gói học và thu tiền', depends: ['hoc-vien'] },
    { id: 'lich', name: 'Lịch và buổi học', depends: ['lop-hoc'] },
    { id: 'diem-danh', name: 'Điểm danh', depends: ['lich', 'goi-hoc'] },
    { id: 'thong-bao', name: 'Thông báo', depends: ['lich'] },
    { id: 'bao-cao', name: 'Báo cáo', depends: ['diem-danh', 'goi-hoc'] },
    { id: 'quan-tri', name: 'Quản trị', depends: [] },
  ],
  screens: [
    { id: 'dang-nhap', name: 'Đăng nhập', surface: 'web', module: 'quan-tri', roles: ['le-tan', 'quan-ly', 'hlv'], entry: true },
    { id: 'hom-nay', name: 'Hôm nay', surface: 'web', module: 'lich', roles: ['le-tan'],
      bands: [{ name: 'Việc nhanh', items: ['F-38', 'F-01', 'F-11', 'F-02'] }, { name: 'Cần xử lý hôm nay', items: ['F-21', 'F-39'] }] },
    { id: 'tong-quan', name: 'Tổng quan', surface: 'web', module: 'bao-cao', roles: ['quan-ly'],
      bands: [{ name: 'Cần duyệt', items: ['F-49'] }, { name: 'Số của tháng', items: ['F-61', 'F-60'] }] },
    { id: 'buoi-day', name: 'Buổi dạy hôm nay', surface: 'web', module: 'diem-danh', roles: ['hlv'],
      bands: [{ name: 'Buổi dạy hôm nay', items: ['F-30'] }, { name: 'Học thử cần ghi', items: ['F-07'] }] },
    { id: 'diem-danh', name: 'Điểm danh', surface: 'web', module: 'diem-danh', roles: ['hlv', 'quan-ly'], zones: ['Danh sách học viên của buổi', 'Thanh lưu'] },
    { id: 'lich', name: 'Lịch', surface: 'web', module: 'lich', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Thanh công cụ', 'Lưới làn và giờ', 'Ngăn chi tiết buổi'] },
    { id: 'hoc-vien', name: 'Học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], zones: ['Tìm và lọc', 'Bảng học viên'] },
    { id: 'ho-so', name: 'Hồ sơ học viên', surface: 'web', module: 'hoc-vien', roles: ['le-tan', 'quan-ly', 'hlv'], parent: 'hoc-vien', pick: true,
      zones: ['Đầu hồ sơ'], tabs: ['Thông tin', 'Gói và đóng tiền', 'Lịch học'] },
    { id: 'lop', name: 'Lớp', surface: 'web', module: 'lop-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Bộ lọc lớp', 'Danh sách lớp và chỗ trống', 'Ngăn danh sách chờ'] },
    { id: 'khoa-hoc', name: 'Khoá học và lớp mở', surface: 'web', module: 'lop-hoc', roles: ['quan-ly'], zones: ['Danh sách khoá', 'Danh sách lớp đã mở'] },
    { id: 'goi-thu-tien', name: 'Gói và thu tiền', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Chờ xác nhận tiền', 'Thu hôm nay', 'Gói đang bảo lưu'] },
    { id: 'gia-han', name: 'Gọi mời gia hạn', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Học viên sắp hết buổi'] },
    { id: 'hoan-tien', name: 'Hoàn tiền', surface: 'web', module: 'goi-hoc', roles: ['le-tan', 'quan-ly'], zones: ['Danh sách đề nghị'] },
    { id: 'thong-bao', name: 'Thông báo', surface: 'web', module: 'thong-bao', roles: ['le-tan', 'quan-ly'], zones: ['Soạn và gửi', 'Đã gửi'] },
    { id: 'bao-cao', name: 'Báo cáo', surface: 'web', module: 'bao-cao', roles: ['quan-ly', 'le-tan'], tabs: ['Chuyên cần', 'Doanh thu'] },
    { id: 'nhat-ky', name: 'Nhật ký thao tác', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], zones: ['Bộ lọc', 'Bảng nhật ký'] },
    { id: 'cai-dat', name: 'Cài đặt', surface: 'web', module: 'quan-tri', roles: ['quan-ly'], tabs: ['Nhân viên', 'Bảng giá', 'Nhắc lịch', 'Ngày nghỉ lễ'] },
    { id: 'app-dang-nhap', name: 'Đăng nhập', surface: 'app', module: 'quan-tri', roles: ['phu-huynh'], entry: true },
    { id: 'app-lich', name: 'Lịch học', surface: 'app', module: 'diem-danh', roles: ['phu-huynh'], zones: ['Chọn con', 'Yêu cầu đổi lịch'],
      bands: [{ name: 'Buổi sắp tới', items: ['F-35'] }, { name: 'Việc nhanh', items: ['F-34', 'F-22'] }] },
    { id: 'app-goi', name: 'Gói học', surface: 'app', module: 'goi-hoc', roles: ['phu-huynh'], zones: ['Số buổi còn lại', 'Lịch sử đóng tiền'] },
    { id: 'app-thong-bao', name: 'Thông báo', surface: 'app', module: 'thong-bao', roles: ['phu-huynh'], zones: ['Danh sách thông báo'] },
    { id: 'app-tai-khoan', name: 'Tài khoản', surface: 'app', module: 'quan-tri', roles: ['phu-huynh'], zones: ['Cài đặt thông báo', 'Tiến bộ của con'] },
  ],
  nav: [
    { roles: ['le-tan'], groups: [
      { name: 'Hằng ngày', items: ['hom-nay', 'lich', 'hoc-vien', 'lop'] },
      { name: 'Tiền', items: ['goi-thu-tien', 'gia-han', 'hoan-tien'] },
      { name: 'Thông báo và báo cáo', items: ['thong-bao', 'bao-cao'] },
    ] },
    { roles: ['quan-ly'], groups: [
      { name: 'Hằng ngày', items: ['tong-quan', 'lich', 'diem-danh'] },
      { name: 'Học viên và lớp', items: ['hoc-vien', 'lop', 'khoa-hoc'] },
      { name: 'Tiền', items: ['goi-thu-tien', 'gia-han', 'hoan-tien'] },
      { name: 'Thông báo và báo cáo', items: ['thong-bao', 'bao-cao'] },
      { name: 'Quản trị', items: ['nhat-ky', 'cai-dat'] },
    ] },
    { roles: ['hlv'], groups: [{ name: '', items: ['buoi-day', 'diem-danh', 'lich', 'hoc-vien'] }] },
    { roles: ['phu-huynh'], groups: [{ name: '', items: ['app-lich', 'app-goi', 'app-thong-bao', 'app-tai-khoan'] }] },
  ],
  place: {
    'F-01': { screen: 'hom-nay', zone: 'Việc nhanh', tier: 2, mo: 'ngan-truot' },
    'F-02': [{ screen: 'hom-nay', zone: 'Việc nhanh', tier: 2, mo: 'tai-cho' }, { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 1, mo: 'tai-cho' }],
    'F-03': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 1, mo: 'trang' },
    'F-04': { screen: 'ho-so', tab: 'Thông tin', tier: 2, mo: 'ngan-truot' },
    'F-05': { screen: 'ho-so', zone: 'Đầu hồ sơ', tier: 4, mo: 'hop-thoai' },
    'F-06': { screen: 'hoc-vien', zone: 'Tìm và lọc', tier: 3, mo: 'ngan-truot' },
    'F-07': { screen: 'buoi-day', zone: 'Học thử cần ghi', tier: 2, mo: 'hop-thoai' },
    'F-08': { screen: 'app-lich', zone: 'Chọn con', tier: 2, mo: 'tai-cho' },
    'F-09': { screen: 'khoa-hoc', zone: 'Danh sách khoá', tier: 2, mo: 'hop-thoai' },
    'F-10': { screen: 'khoa-hoc', zone: 'Danh sách lớp đã mở', tier: 1, mo: 'ngan-truot' },
    'F-11': [{ screen: 'hom-nay', zone: 'Việc nhanh', tier: 2, mo: 'ngan-truot' }, { screen: 'lop', zone: 'Danh sách lớp và chỗ trống', tier: 1, mo: 'ngan-truot' }],
    'F-12': { screen: 'lop', zone: 'Ngăn danh sách chờ', tier: 4, mo: 'hop-thoai' },
    'F-13': { screen: 'lop', zone: 'Ngăn danh sách chờ', tier: 2, mo: 'tai-cho' },
    'F-14': { screen: 'lop', zone: 'Danh sách lớp và chỗ trống', tier: 4, mo: 'hop-thoai' },
    'F-15': { screen: 'lop', zone: 'Danh sách lớp và chỗ trống', tier: 4, mo: 'hop-thoai' },
    'F-16': { screen: 'lich', zone: 'Lưới làn và giờ', tier: 1, mo: 'tai-cho' },
    'F-17': { screen: 'lich', zone: 'Lưới làn và giờ', tier: 2, mo: 'tai-cho' },
    'F-18': { screen: 'lich', zone: 'Ngăn chi tiết buổi', tier: 2, mo: 'ngan-truot' },
    'F-19': { screen: 'lich', zone: 'Ngăn chi tiết buổi', tier: 4, mo: 'ngan-truot' },
    'F-20': { screen: 'ho-so', tab: 'Lịch học', tier: 4, mo: 'ngan-truot' },
    'F-21': [{ screen: 'hom-nay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'ngan-truot' }, { screen: 'lich', zone: 'Ngăn chi tiết buổi', tier: 2, mo: 'ngan-truot' }],
    'F-22': { screen: 'app-lich', zone: 'Việc nhanh', tier: 2, mo: 'sheet' },
    'F-23': { screen: 'app-lich', zone: 'Yêu cầu đổi lịch', tier: 2, mo: 'tai-cho' },
    'F-25': { screen: 'lich', zone: 'Ngăn chi tiết buổi', tier: 3, mo: 'hop-thoai' },
    'F-26': { screen: 'lich', zone: 'Thanh công cụ', tier: 3, mo: 'hop-thoai' },
    'F-29': { screen: 'cai-dat', tab: 'Ngày nghỉ lễ', tier: 3, mo: 'tai-cho' },
    'F-30': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 1, mo: 'trang' },
    'F-31': { screen: 'diem-danh', zone: 'Danh sách học viên của buổi', tier: 4, mo: 'hop-thoai' },
    'F-34': { screen: 'app-lich', zone: 'Việc nhanh', tier: 2, mo: 'sheet' },
    'F-35': { screen: 'app-lich', zone: 'Buổi sắp tới', tier: 1, mo: 'tai-cho' },
    'F-36': { screen: 'app-goi', zone: 'Số buổi còn lại', tier: 1, mo: 'tai-cho' },
    'F-37': { screen: 'app-goi', zone: 'Lịch sử đóng tiền', tier: 2, mo: 'tai-cho' },
    'F-38': [{ screen: 'hom-nay', zone: 'Việc nhanh', tier: 1, mo: 'ngan-truot' }, { screen: 'goi-thu-tien', zone: 'Thu hôm nay', tier: 1, mo: 'ngan-truot' }],
    'F-39': [{ screen: 'hom-nay', zone: 'Cần xử lý hôm nay', tier: 2, mo: 'tai-cho' }, { screen: 'goi-thu-tien', zone: 'Chờ xác nhận tiền', tier: 2, mo: 'tai-cho' }],
    'F-40': { screen: 'goi-thu-tien', zone: 'Thu hôm nay', tier: 2, mo: 'tai-cho' },
    'F-41': { screen: 'goi-thu-tien', zone: 'Gói đang bảo lưu', tier: 3, mo: 'hop-thoai' },
    'F-42': { screen: 'goi-thu-tien', zone: 'Gói đang bảo lưu', tier: 2, mo: 'tai-cho' },
    'F-45': { screen: 'cai-dat', tab: 'Bảng giá', tier: 3, mo: 'ngan-truot' },
    'F-46': { screen: 'gia-han', zone: 'Học viên sắp hết buổi', tier: 1, mo: 'tai-cho' },
    'F-47': { screen: 'gia-han', zone: 'Học viên sắp hết buổi', tier: 2, mo: 'hop-thoai' },
    'F-48': { screen: 'hoan-tien', zone: 'Danh sách đề nghị', tier: 2, mo: 'ngan-truot' },
    'F-49': [{ screen: 'tong-quan', zone: 'Cần duyệt', tier: 1, mo: 'ngan-truot' }, { screen: 'hoan-tien', zone: 'Danh sách đề nghị', tier: 4, mo: 'hop-thoai' }],
    'F-50': { screen: 'hoan-tien', zone: 'Danh sách đề nghị', tier: 4, mo: 'hop-thoai' },
    'F-51': { screen: 'hoan-tien', zone: 'Danh sách đề nghị', tier: 1, mo: 'tai-cho' },
    'F-53': { screen: 'goi-thu-tien', zone: 'Thu hôm nay', tier: 3, mo: 'hop-thoai' },
    'F-54': { screen: 'thong-bao', zone: 'Soạn và gửi', tier: 1, mo: 'ngan-truot' },
    'F-56': { screen: 'cai-dat', tab: 'Nhắc lịch', tier: 3, mo: 'tai-cho' },
    'F-57': { screen: 'app-thong-bao', zone: 'Danh sách thông báo', tier: 1, mo: 'tai-cho' },
    'F-58': { screen: 'app-tai-khoan', zone: 'Cài đặt thông báo', tier: 3, mo: 'tai-cho' },
    'F-59': { screen: 'thong-bao', zone: 'Soạn và gửi', tier: 3, mo: 'hop-thoai' },
    'F-60': [{ screen: 'tong-quan', zone: 'Số của tháng', tier: 2, mo: 'tai-cho' }, { screen: 'bao-cao', tab: 'Chuyên cần', tier: 1, mo: 'tai-cho' }],
    'F-61': [{ screen: 'tong-quan', zone: 'Số của tháng', tier: 2, mo: 'tai-cho' }, { screen: 'bao-cao', tab: 'Doanh thu', tier: 2, mo: 'tai-cho' }],
    'F-62': { screen: 'bao-cao', tab: 'Doanh thu', tier: 3, mo: 'hop-thoai' },
    'F-63': { screen: 'cai-dat', tab: 'Nhân viên', tier: 3, mo: 'ngan-truot' },
    'F-64': { screen: 'cai-dat', tab: 'Nhân viên', tier: 4, mo: 'ngan-truot' },
    'F-65': { screen: 'cai-dat', tab: 'Nhân viên', tier: 4, mo: 'hop-thoai' },
    'F-66': { screen: 'nhat-ky', zone: 'Bảng nhật ký', tier: 1, mo: 'tai-cho' },
    'F-67': { screen: 'dang-nhap', tier: 1, mo: 'trang' },
    'F-68': { screen: 'app-dang-nhap', tier: 1, mo: 'trang' },
    'F-69': { screen: 'hoc-vien', zone: 'Bảng học viên', tier: 3, mo: 'ngan-truot' },
    'F-70': { screen: 'app-tai-khoan', zone: 'Tiến bộ của con', tier: 3, mo: 'tai-cho' },
  },
  shortcuts: [
    { from: 'hoc-vien', to: 'F-01', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-38', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-11', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-41', mo: 'hop-thoai' },
    { from: 'ho-so', to: 'F-18', mo: 'ngan-truot' },
    { from: 'ho-so', to: 'F-19', mo: 'ngan-truot' },
    { from: 'buoi-day', to: 'F-30', mo: 'trang', ve: 'Lưu điểm danh xong thì về Buổi dạy hôm nay, báo đã lưu; có nút Quay lại giữ nguyên danh sách' },
  ],
  flows: [
    { role: 'le-tan', name: 'Khách mới tới mua gói', steps: ['F-02', 'F-01', 'F-38', 'F-11'] },
    { role: 'le-tan', name: 'Phụ huynh xin dời buổi qua app', steps: ['F-21', 'F-18'] },
    { role: 'quan-ly', name: 'Cuối tháng xem số và duyệt hoàn tiền', steps: ['F-49', 'F-61', 'F-60'] },
    { role: 'hlv', name: 'Điểm danh một buổi', steps: ['F-30', 'F-31'] },
    { role: 'phu-huynh', name: 'Bé ốm, báo nghỉ rồi xin buổi khác', steps: ['F-35', 'F-34', 'F-22', 'F-23'] },
  ],
  tasks: [
    { role: 'le-tan', say: 'Phụ huynh đưa tiền mặt mua gói 12 buổi cho bé đã có hồ sơ.', feature: 'F-38' },
    { role: 'le-tan', say: 'Một bé mới đến, phụ huynh chưa từng tới trung tâm.', feature: 'F-01' },
    { role: 'le-tan', say: 'Bé vừa mua gói, cần chọn lớp Cơ bản chiều thứ Ba cho bé.', feature: 'F-11' },
    { role: 'le-tan', say: 'Một phụ huynh nhắn qua app xin dời buổi thứ Tư sang tuần sau.', feature: 'F-21' },
    { role: 'le-tan', say: 'Bơm lọc hỏng lúc 14:00, các buổi chiều nay không thể bơi.', feature: 'F-26' },
    { role: 'hlv', say: 'Buổi 17:30 bắt đầu, có bé có mặt và có bé vắng.', feature: 'F-30' },
    { role: 'phu-huynh', say: 'Bé ốm sáng nay, chiều có buổi học.', feature: 'F-34' },
    { role: 'phu-huynh', say: 'Muốn biết con còn mấy buổi.', feature: 'F-36' },
    { role: 'quan-ly', say: 'Cuối tháng, chủ trung tâm muốn biết tháng này thu được bao nhiêu.', feature: 'F-61' },
    { role: 'quan-ly', say: 'Lễ tân báo có một đề nghị hoàn tiền đang chờ quyết định.', feature: 'F-49' },
  ],
};
